### ISSUE TITLE
wifi bug

### ISSUE THREAD

**Issue by nawirwii** [ophub/amlogic-s9xxx-openwrt#100]
please fix wifi bug,can connect with hotspot thering..thx

**Comment by ophub** [comment]
What device and which openwrt firmware to flash

**Comment by nawirwii** [comment]
Amlogic Meson GXL (S905X) P212 Development Board HG680P

**Comment by ophub** [comment]
Which model is your usb wifi? The models that openwrt can support are as described in the list:


https://github.com/ophub/amlogic-s9xxx-openwrt/blob/88c305bfbb7681224c2bd7b3ff54def022f98623/router-config/lede-master/.config#L83
