### ISSUE TITLE
s905x can't install "openwrt-install"

### ISSUE THREAD

**Issue by zaiyin** [ophub/amlogic-s9xxx-openwrt#101]
root@OpenWrt:~# openwrt-install
AUTO_MAINLINE_UBOOT:
SPECIFY_SOC:
SPECIFY_DTB:
/usr/bin/openwrt-install: line 56: [[: 1
0
0: syntax error in expression (error token is "0
0")
Root file system not found!!!
root@OpenWrt:~#

How to fix?

**Comment by ophub** [comment]
Thank you for reporting the bug, the installation error message has been fixed. Please download the latest version in releases. Flash the new openwrt into usb and try again.

`Or go to openwrt → system menu → Amlogic Service → [Online Download Update] to update the plug-in first, and then install it`


It is recommended that you install openwrt like this:
`Log in to the default IP: 192.168.1.1 → Login in to openwrt → system menu → Amlogic Service → Install OpenWrt`
