### ISSUE TITLE
Cannot install to MMC of H96 pro+(2G+16G)

### ISSUE THREAD

**Issue by derekxi2021** [ophub/amlogic-s9xxx-openwrt#104]
Tried to install openwrt to MMC of H96 pro+(2G+16G). Tried boot on USB(openwrt_s912_k5.13.6_2021.08.01.1456.img.gz), firstly, can intall sucessfully by select Octopus-Planet dtb. But can not boot openwrt by emmc sucessfully. Tried openwrt_s912_k5.4.136_2021.08.01.1457.img.gz, the system hanged and rebooted during copy "usr" stage and cannot boot openwrt without usb disk. I also tried meson-gxm_q201_2g.dtb, the issues are same as Octopus-Planet dtb.

**Comment by ophub** [comment]
Flash the usb again, or change the firmware, such as today's 5.4.137 and try again.
