### ISSUE TITLE
把文件包放到其他位置，在编译的时候下载，容易出错。还不如像之前那样放一起同步。

### ISSUE THREAD

**Issue by vpei** [ophub/amlogic-s9xxx-openwrt#105]
把文件包放到其他位置，在编译的时候下载，容易出错。还不如像之前那样放一起同步。

svn: E170013: Unable to connect to a repository at URL 'https://github.com/ophub/luci-app-amlogic/trunk/luci-app-amlogic/root/usr/bin'
svn: E000104: 执行上下文错误: 连接被对方重设

**Comment by vpei** [comment]
这个网址手动打开也报错，提示不存在。

**Comment by vpei** [comment]
建议同步最新的几个，其他的都存放在另一位置。

**Comment by ophub** [comment]
This is the address in svn co format. No errors will be reported when compiling and packaging on github.com. Are you packing locally? When using, as long as the computer can access github.com normally.

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-openwrt/actions

I just tested it, packaging and installation are all normal.

**Comment by ophub** [comment]
sudo apt-get update
sudo apt-get install subversion

# view
svn --version
