### ISSUE TITLE
luci-openvpn

### ISSUE THREAD

**Issue by riyuejz** [ophub/amlogic-s9xxx-openwrt#11]
![Screenshot_2021-02-22-05-47-23-356_com android chrome](https://user-images.githubusercontent.com/50128745/108641436-d6765c00-74d1-11eb-852a-5b18a2a19b1b.jpg)

after installing luci-openvpn openvpn-openssl I tried to add the ovpn config profile instead like this ... s905x hg680p

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-openwrt/actions/runs/588047358

I just added openvpn to the package, and I will test it after the compilation.

**Comment by riyuejz** [comment]
ok I will wait for the results

**Comment by riyuejz** [comment]
don't forget to add a new ovpn client config whether it works or not .. thanks for all the help 🙏

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-openwrt/blob/main/router_config/.config

I added the client and server in lines 333 and 334, and tested it after the compilation was completed.

**Comment by ophub** [comment]
Compilation is complete, I tested Services > OpenVPN, and  the VPN > OpenVPN-Server,All the pages are displayed normally.

**Comment by ophub** [comment]
router_config/.config
lines 333 and 334

CONFIG_PACKAGE_luci-app-openvpn=y
CONFIG_PACKAGE_luci-app-openvpn-server=y

**Comment by riyuejz** [comment]
Have you tried adding .ovpn configuration to openvpn client manually? the page is an error if you add the OVPN configuration manually ...

**Comment by ophub** [comment]
![Snip20210222_4](https://user-images.githubusercontent.com/68696949/108685123-b923ab00-752e-11eb-8be9-5e93e679726d.png)

I don’t know how to use openvpn, but I added one based on his default, but no errors were reported.

**Comment by riyuejz** [comment]
![Screenshot_2021-02-22-16-36-00-382_com android chrome](https://user-images.githubusercontent.com/50128745/108689944-50d3ca00-752c-11eb-8074-467f185e217e.jpg)
thanks .. this version works well 🙏
