### ISSUE TITLE
Not compatible with node npm

### ISSUE THREAD

**Issue by onwingslnz** [ophub/amlogic-s9xxx-openwrt#118]
node and node-npm can be installed. 
But there are errors while runs node and npm:

Error relocating /usr/bin/node: _ZNSt19_Sp_make_shared_tag5_S_eqERKSt9type_info: symbol not found
Error relocating /usr/bin/node: _ZNSt19basic_ostringstreamIcSt11char_traitsIcESaIcEEC1Ev: symbol not found
Error relocating /usr/bin/node: _ZNSt18basic_stringstreamIcSt11char_traitsIcESaIcEEC1Ev: symbol not found

**Comment by ophub** [comment]
#
# Node.js
#
CONFIG_PACKAGE_node=y

#
# Configuration
#
# CONFIG_NODEJS_10 is not set
# CONFIG_NODEJS_12 is not set
CONFIG_NODEJS_14=y
# CONFIG_NODEJS_ICU_NONE is not set
CONFIG_NODEJS_ICU_SMALL=y
# CONFIG_NODEJS_ICU_SYSTEM is not set
# end of Configuration

# CONFIG_PACKAGE_node-arduino-firmata is not set
# CONFIG_PACKAGE_node-cylon is not set
# CONFIG_PACKAGE_node-cylon-firmata is not set
# CONFIG_PACKAGE_node-cylon-gpio is not set
# CONFIG_PACKAGE_node-cylon-i2c is not set
# CONFIG_PACKAGE_node-hid is not set
# CONFIG_PACKAGE_node-homebridge is not set
# CONFIG_PACKAGE_node-javascript-obfuscator is not set
CONFIG_PACKAGE_node-npm=y
# CONFIG_PACKAGE_node-serialport is not set
# CONFIG_PACKAGE_node-serialport-bindings is not set
# end of Node.js

#
