### ISSUE TITLE
error compiling 3rd party repo

### ISSUE THREAD

**Issue by kokenot** [ophub/amlogic-s9xxx-openwrt#119]
i tried several time compiling 3rd party repo but failed. already done what u said from this post #117. ssh then run the command to pull package inside container and it 'success' but after continue compiling the firmware i've got an error. 
here is the error
![IMG_20210911_191411](https://user-images.githubusercontent.com/26756586/132946067-e539af5a-fbd1-4479-9c4c-9aafd8e4c209.jpg)

**Comment by ophub** [comment]
Two ways:
1. Local `make menuconfig` gets the complete `.config` and replaces the files in the warehouse.

2. Manually change `.config` to change gradually. Add a small amount each time, and gradually change the fine-tuning.

**Comment by kokenot** [comment]
diy-part2.sh must be run again inside container after I replace the config?

**Comment by ophub** [comment]
The first execution of diy-part1.sh and diy-part2.sh is to `git clone` the plug-in introduced in this file to the local.

**Comment by kokenot** [comment]
ok i will setup the local environment first and let you know the result

**Comment by kokenot** [comment]
issue solve. compiling on local machine.

**Comment by ophub** [comment]
Congratulations. The complete .config file generated locally can overwrite the simplified .config file on github for compilation on github.
