### ISSUE TITLE
Fiberhome HG680P(S905x) No Wifi

### ISSUE THREAD

**Issue by r3yr3** [ophub/amlogic-s9xxx-openwrt#12]
Please add wlan driver for Fiberhome HG680P(S905x) with 
driver rtl8188f

**Comment by ophub** [comment]
In line 177 of the `router_config/.config file`, I added:
`CONFIG_PACKAGE_kmod-rtl8xxxu=y`

According to the explanation on the official website of openwrt.org, this driver should be used for `Realtek 8723/8188/8191/8192 WiFi` :
[https://openwrt.org/packages/pkgdata/kmod-rtl8xxxu](https://openwrt.org/packages/pkgdata/kmod-rtl8xxxu)

I don’t have this STB, you can give me feedback after testing.

**Comment by r3yr3** [comment]
still can't detect wifi, maybe the kernel doesn't match
Thanks for your efforts.
