### ISSUE TITLE
add package version

### ISSUE THREAD

**Issue by riyuejz** [ophub/amlogic-s9xxx-openwrt#121]
how do I add a package to the .config file with a certain version of the package.
here I want to add the ffmpeg package with version 4.2.4

**Comment by ophub** [comment]
You can run the `make menuconfig` command locally, choose to adjust various software packages, and then save to get a personalized customized `.config` configuration file. Just overwrite this file with the file with the same name on github.

**Comment by riyuejz** [comment]
ok, I'll give it a try.. thanks for the help
