### ISSUE TITLE
some bug when installing on emmc B860

### ISSUE THREAD

**Issue by Manssizz** [ophub/amlogic-s9xxx-openwrt#125]
hi... previously i wanna say big thanks for you. 
but i got some error.
1. error while installing on emmc with dynamic script (openwrt-install-amlogic). 
**Fixed** with replace all text `/dev/${EMMC_NAME}` with static var `/dev/mmcblk2`
https://github.com/ophub/luci-app-amlogic/blob/b62cc1129bdd99c4315434d8361ace3f324ae9ac/luci-app-amlogic/root/usr/bin/openwrt-install-amlogic#L426
2. After successful install on emmc, i got this error with some data not copied. missing file is `/opt` dir. Because my docker and adguard config missing
```
[   89.097215] BTRFS warning (device mmcblk2p2): csum failed root 5 ino 4946 off 1054920704 csum 0x8941f998 expected csum 0x7ae8ac16 mirror 1
[   89.109538] BTRFS warning (device mmcblk2p2): csum failed root 5 ino 4946 off 1054920704 csum 0x8941f998 expected csum 0x7ae8ac16 mirror 1
[   98.538140] BTRFS warning (device mmcblk2p2): csum failed root 5 ino 4946 off 1054920704 csum 0x8941f998 expected csum 0x7ae8ac16 mirror 1
[   98.550195] BTRFS warning (device mmcblk2p2): csum failed root 5 ino 4946 off 1054920704 csum 0x8941f998 expected csum 0x7ae8ac16 mirror 1
[  106.108437] BTRFS warning (device mmcblk2p2): csum failed root 5 ino 4946 off 1054920704 csum 0x8941f998 expected csum 0x7ae8ac16 mirror 1
[  106.120311] BTRFS warning (device mmcblk2p2): csum failed root 5 ino 4946 off 1054920704 csum 0x8941f998 expected csum 0x7ae8ac16 mirror 1
[  241.887367] BTRFS warning (device mmcblk2p2): csum failed root 5 ino 4946 off 1054920704 csum 0x8941f998 expected csum 0x7ae8ac16 mirror 1
[  241.899441] BTRFS warning (device mmcblk2p2): csum failed root 5 ino 4946 off 1054920704 csum 0x8941f998 expected csum 0x7ae8ac16 mirror 1
[  341.299876] BTRFS warning (device mmcblk2p2): csum failed root 5 ino 4946 off 1054920704 csum 0x8941f998 expected csum 0x7ae8ac16 mirror 1
[  341.311558] BTRFS warning (device mmcblk2p2): csum failed root 5 ino 4946 off 1054920704 csum 0x8941f998 expected csum 0x7ae8ac16 mirror 1
```

**Comment by ophub** [comment]
`openwrt-install-amlogic` is an installation command that will format the EMMC of the device, and all data will be cleared and repartitioned. If you want to upgrade, use the `openwrt-update-amlogic` command, you can choose to keep the data or a new installation.

`/opt` is in the rootfs partition. This is the system partition. Don't put `docker` here. Its log grows very fast. If the log is full, the system will not start.
The `/mnt/mmcblk2p4` in the system is the largest partition, and the data that needs to be retained for a long time is stored here (the data will not be lost during the update).
