### ISSUE TITLE
enable wifi

### ISSUE THREAD

**Issue by kokenot** [ophub/amlogic-s9xxx-openwrt#129]
how can I enable wireless feature . there is no wireless menu inside luci control panel

**Comment by ophub** [comment]
What equipment are you? Unlimited use is enabled by default, but some devices do not have wireless drivers, such as x96max+

**Comment by kokenot** [comment]
> What equipment are you? Unlimited use is enabled by default, but some devices do not have wireless drivers, such as x96max+

I can see wireless menu when using compiling script from openwrt_packit. I do know some device don't have driver for built in wifi. but we can use usb wifi as alternative. the problem is wireless menu is missing from luci panel. is it hide or any trick to enable it back?

**Comment by ophub** [comment]
If there is a corresponding external wireless device driver, it will be automatically listed and displayed in the wireless management module.

**Comment by kokenot** [comment]
what i mean is,there is no wireless menu in luci, even if i plug in the usb device. usb wifi driver is detected. also the wireless menu can't show. missing in luci.

**Comment by ophub** [comment]
In my device, wireless is automatically displayed. I don't know the reason for your question. Sorry for not being able to help you.
