### ISSUE TITLE
s905X2 device not booted on B860H-V5 telkom

### ISSUE THREAD

**Issue by nationpwned** [ophub/amlogic-s9xxx-openwrt#132]
hello ophub,
i have downloaded and burn s905x2 on my device b860h-V5 rooted but unluckily not booted,
i see in env.ext file the dtb use meson-g12a-x96-max.dtb

i try to browse and got info that this device use g12a_u212_2g
someone on indonesian's fb group provide the dts of this device, here is the link : https://www.mediafire.com/file/xnt75n4nqbfamn3/g12a_u212_2g.dts/file

and when i check that was true that this device use g12a_u212_2g
![dtb](https://user-images.githubusercontent.com/17819957/135741623-690e0e71-2f56-434e-8a58-32ba470a8ba4.png)

can u help me to make this device booted on openwrt?
thanks before

**Comment by ophub** [comment]
Edit `/boot/uEnv.txt`, Try this dtb for 2G memory: `meson-g12a-x96-max-rmii.dtb`

Try it with the 5.4 kernel first: https://github.com/ophub/amlogic-s9xxx-openwrt/releases/download/openwrt_s9xxx_lede_2021.10.02.2109/openwrt_s905x2_k5.4.150_2021.10.02.2057.img.gz

**Comment by wormalaska** [comment]
same case like nationpwned
![image](https://user-images.githubusercontent.com/60564200/135749203-8d88c133-c970-439d-855c-1fbf310d4a5c.png)

so i tried https://github.com/ophub/amlogic-s9xxx-openwrt/releases/download/openwrt_s9xxx_lede_2021.10.02.2109/openwrt_s905x2_k5.4.150_2021.10.02.2057.img.gz

blackscreen only 
not showup

**Comment by ophub** [comment]
I don’t know how your screen came from. How did you execute the ls command without starting?

You write the openwrt of the 5.4 kernel s905x2 into the USB disk, insert the USB disk into the box, and plug in the power to start.

It will start after a minute, connect the keyboard to your box, and press Enter to see the banner. Or you can directly visit the browser.

**Comment by ophub** [comment]
Take a screenshot of /boot/uEnv.txt, take a screenshot to see the startup process, insert the U disk, power on, and take a screenshot of the startup screen one minute later. I don’t know what you are doing in the picture above.

**Comment by nationpwned** [comment]
> Edit `/boot/uEnv.txt`, Try this dtb for 2G memory: `meson-g12a-x96-max-rmii.dtb`
> 
> Try it with the 5.4 kernel first: https://github.com/ophub/amlogic-s9xxx-openwrt/releases/download/openwrt_s9xxx_lede_2021.10.02.2109/openwrt_s905x2_k5.4.150_2021.10.02.2057.img.gz

none of g12a dtb work, 
i tried to change uboot with s905x2-s922 uboot renamed as uboot.ext also wont boot and enter to andorid tv.
i've tried 5.4 and 5.10 also wont boot

any idea how to make this device work?

**Comment by nationpwned** [comment]
just info, b860h-v5 doesnt have reset button, what i did : adb connect 192.x.x.x.x, adb shell, su, reboot update.

**Comment by ophub** [comment]
You do what I say, answer my question.

**Comment by nationpwned** [comment]
> You do what I say, answer my question. I did not teach you these operations.
![env ext](https://user-images.githubusercontent.com/17819957/135753832-3991a1c0-5a37-46ad-8e5a-bea8841211f6.png)

after reboot update, nothing happen except entering to android tv

**Comment by ophub** [comment]
Do not change if you use the 5.4 kernel, except uEnv.txt, do not change anything else.

**Comment by nationpwned** [comment]
> Do not change if you use the 5.4 kernel, except uEnv.txt, do not change anything else.

first time i tried is just change the dtb, after trying all g12a and none of those work, i tried change uboot, and now i just burn new image on my sd card..

**Comment by ophub** [comment]
Insert the USB disk, press and hold the reset button, power on, release the reset button after 5 seconds, you can start from usb.

**Comment by ophub** [comment]
Use usb disk, not tf card.

**Comment by ophub** [comment]
5.4 The kernel has nothing to do with u-boot, as long as you choose the right dtb, you can use it.

**Comment by nationpwned** [comment]
ok, i use usb disk, but the still entering to android tv,
i tried press 3 seconds, 5 seconds and more but still entering to android tv

**Comment by ophub** [comment]
Try those few next to each other. `meson-g12a-*.dtb`

**Comment by nationpwned** [comment]
> Try those few next to each other. `meson-g12a-*.dtb`

i have already done it, but no good result, still entering to android tv

**Comment by ophub** [comment]
If your own dtb can't be started, you can go to the [armbian](https://forum.armbian.com) forum, find the s905x2 armbian system that suits your box, and copy his dtb to use.

**Comment by ophub** [comment]
I don't think you have a dtb problem, but you have not booted from the USB flash drive, and you have entered the original Android tv system every time.

**Comment by nationpwned** [comment]
> I don't think you have a dtb problem, but you have not booted from the USB flash drive, and you have entered the original Android tv system every time. You can boot from the USB disk first, and then try dtb.
> 
> https://github.com/ophub/amlogic-s9xxx-openwrt/blob/main/router-config/README.md#1010-turn-on-the-usb-disk-boot-mode-of-the-amlogic-s9xxx-stb

ok, i will try to browe the entire net, and if this device work, i will give you info how this device work..
by the way thank you very much,
you did a brilliant job.
greeting from Indonesia

**Comment by ophub** [comment]
You're welcome. There are many ways to set the box to boot from usb. As long as you enter the usb and start it, you are ready to debug.
