### ISSUE TITLE
Box cannot boot via pendrive

### ISSUE THREAD

**Issue by kokenot** [ophub/amlogic-s9xxx-openwrt#133]
is there any other way to boot the openwrt in the box? I have another x96 max plus that failed to boot openwrt via pendrive. model name show on setting android setting is x96 max plus a1. I'm using similar technique by pressing reset + power on, but still it cannot boot. this board version is different from my previous x96Max Plus. already change different firmware and different pendrive. no luck at all. the box only show recovery android if I insert hdmi to monitor. there is no sign of Black and White text booting process. by the way I'm using your 5.4 kernel s905x3 firmware

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-openwrt/blob/main/router-config/README.md#1010-turn-on-the-usb-disk-boot-mode-of-the-amlogic-s9xxx-stb

**Comment by kokenot** [comment]
tq I will look into it

**Comment by kokenot** [comment]
box can boot. problem the dtb is not compatible with the on board network cipset. this is the network cipset. other brand and not realtek. how can I get dtb version for this network cipset? or is there any trick to pull dtb file from stock firmware? 
![IMG_20211006_191446_773](https://user-images.githubusercontent.com/26756586/136193325-d0ba9885-0835-4329-abaa-6172a402b378.jpg)

**Comment by ophub** [comment]
I did not find the introduction of `x96 max plus a1` equipment on the Internet. Can you see what model of its `soc` is?
