### ISSUE TITLE
ssr++

### ISSUE THREAD

**Issue by ramasedang** [ophub/amlogic-s9xxx-openwrt#14]
Sir, can you extract the ssr++, i want instal it to another Firmware openwrt

**Comment by ophub** [comment]
https://github.com/coolsnowwolf/lede/blob/master/feeds.conf.default
In the openwrt compiled source code, a third-party library is introduced. In line 11, Manually remove#.

Or refer to the custom script below, on line 11, remove # when the script is compiled.
https://github.com/ophub/amlogic-s9xxx-openwrt/blob/main/router_config/diy-part1.sh
