### ISSUE TITLE
Kernel module not found

### ISSUE THREAD

**Issue by aeroslubis** [ophub/amlogic-s9xxx-openwrt#140]
After compiling custom kernel module *.ko file not in the /lib/modules/*/ directory, but the opkg status is installed. Any idea why?

**Comment by ophub** [comment]
Send a screenshot of the error message?
Do you mean that you compiled the kernel file yourself? An error occurs when I package openwrt with my own kernel file?

**Comment by ophub** [comment]
You are in the openwrt system when you compile, so in your openwrt-armvirt-64-default-rootfs.tar.gz file. But you replaced the kernel file with flippy-64, so if it is in the /lib/modules/ directory, it will be replaced.

**Comment by aeroslubis** [comment]
Is there an alternative to flippys kernel for amlogic s9xxx?
