### ISSUE TITLE
awk: cmd. line:1: Invalid argument

### ISSUE THREAD

**Issue by kokenot** [ophub/amlogic-s9xxx-openwrt#145]
how to eliminate this error on terminal status?

Install: OpenWrt → System → Amlogic Service → Install
 Update: OpenWrt → System → Amlogic Service → Update
 Amlogic SoC: s905w
 OpenWrt Kernel: 5.4.150-flippy-65+o
 Packaged Date: 2021-10-13
 -----------------------------------------------------
**awk: cmd. line:1: Invalid argument**
 Device Model: Oranth Tanix TX3 Mini
 Architecture: AArch64 : Cortex-A53 x 4
 Load Average: 0.91 0.69 0.29   Uptime:  3m 7s
Frequency:  500 Mhz
 Memory Usage: 9% of 803MB      IP Address:  192.168.1.1 192.168.8.104
 Boot Storage: 18% of 242.7M    SYS Storage:   36% of 973.0M 

also, how do i show temperature at status -> overview section ?
compiling using openwrt_packit script has the temperature status feature, but there is none script to build for s905w.

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-openwrt/blob/main/make#L242
![Snip20211013_5](https://user-images.githubusercontent.com/68696949/137138912-d4b447b8-134e-4d11-b84a-3d28c7fad5c1.png)

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-openwrt/issues/146#issuecomment-944868759
