### ISSUE TITLE
Group Discuss

### ISSUE THREAD

**Issue by adisubagja** [ophub/amlogic-s9xxx-openwrt#15]
Can you make a telegram group chat for discussion,report,etc ?

**Comment by ophub** [comment]
My mother didn't let me play on the phone or chat, I only had to finish my homework and study online for a while.

**Comment by adisubagja** [comment]
Ookay no problem, thanks for telling me.
I hope when already finish ur study our can make support group chat bro 😊
Thanks you very much bro

**Comment by ophub** [comment]
Thank you.
