### ISSUE TITLE
third-party software packages

### ISSUE THREAD

**Issue by kyliezero** [ophub/amlogic-s9xxx-openwrt#156]
I need help to add this package, I have tried this way but it doesn't work

`# diy-part2.sh`
svn co https://github.com/Kiougar/luci-wrtbwmon package/luci-app-wrtbwmon
svn co https://github.com/pyrovski/wrtbwmon package/wrtbwmon

`# .config`
CONFIG_PACKAGE_luci-app-wrtbwmon
CONFIG_PACKAGE_wrtbwmon

`#Source`
https://github.com/pyrovski/wrtbwmon
https://github.com/Kiougar/luci-wrtbwmon

**Comment by ophub** [comment]
The two websites you provided have only ipk installations, without compiling the source code, they cannot be compiled.

https://github.com/coolsnowwolf/lede/tree/master/package/lean/luci-app-wrtbwmon

This software is already included in the source code of lede, so you can use it directly.
`ONFIG_PACKAGE_luci-app-wrtbwmon=y`
