### ISSUE TITLE
This step has been truncated due to its large size. Download the full logs from the  menu once the workflow run has completed.

### ISSUE THREAD

**Issue by thecupangin** [ophub/amlogic-s9xxx-openwrt#158]
hi, i try to build with action on github, but failed and show error log "This step has been truncated due to its large size. Download the full logs from the  menu once the workflow run has completed." how to solve ya?
![image](https://user-images.githubusercontent.com/93725433/140459683-74366c23-7d3a-4fa2-8436-4ba4f80934bf.png)

**Comment by ophub** [comment]
```
Server space usage before starting to compile: 
Filesystem     Type  Size  Used Avail Use% Mounted on
/dev/root      ext4   84G   67G   17G  80% / 
```

The available space of github is `84G`. I used `67G` when compiling `openwrt-armvirt-64-default-rootfs.tar.gz`. If you choose more packages, you need more space. I suggest you run my default configuration first, and then add it gradually. Also leave enough space for the `packaged OpenWrt firmware` below.

**Comment by thecupangin** [comment]
add more space? how to add more space?

**Comment by ophub** [comment]
The free user of github is 84G, and the space for paid users is large.

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-openwrt/runs/4112221095?check_suite_focus=true#step:15:181

Enough for normal use.

**Comment by thecupangin** [comment]
let me try your original script, use lede ya? not openwrt 21.02

**Comment by thecupangin** [comment]
![image](https://user-images.githubusercontent.com/93725433/140478533-d7589f56-0b64-4c68-9ede-7c6262f7ff19.png)
![image](https://user-images.githubusercontent.com/93725433/140478580-ee16d064-3cd7-4ccf-a519-ec8ecef67fe1.png)

using default script, without adding new packages, still same issue

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-openwrt/actions/runs/1424485467

https://github.com/ophub/amlogic-s9xxx-openwrt/actions/runs/1423854741

I tested both branches today, no problem. You synchronize, try to compile it first.

**Comment by thecupangin** [comment]
![image](https://user-images.githubusercontent.com/93725433/140489267-8f30b364-6698-4d5a-afe0-26218c7db599.png)
 re-fork, fresh & up to date, hopefully work

**Comment by thecupangin** [comment]
![image](https://user-images.githubusercontent.com/93725433/140499385-2b80df41-20b9-41fe-8298-7a29add58ea8.png)
the problem still same, fresh fork, no edit

**Comment by ophub** [comment]
You try to compile the lede branch.

**Comment by thecupangin** [comment]
![image](https://user-images.githubusercontent.com/93725433/140505996-9f9fa5c1-ff68-4434-ad7c-8331fa85479e.png)
trying LEDE branch

**Comment by thecupangin** [comment]
![image](https://user-images.githubusercontent.com/93725433/140519808-6dc63ba0-592d-4a06-9c69-24d12d4e0197.png)
LEDE still same bro. what's wrong ya?

**Comment by ophub** [comment]
https://www.google.com/search?q=github+This+step+has+been+truncated+due+to+its+large+size


I see that you have compiled it. Many records of this problem have been searched in google. Github’s prompts on the big log will continue to be executed.

**Comment by thecupangin** [comment]
why close?
