### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by ramasedang** [ophub/amlogic-s9xxx-openwrt#16]
sir, can u add docker to the firmware S905x (b860h/hg680p)

**Comment by ophub** [comment]
Hello, all the firmware has included `luci-app-docker` and `docker-compose`. The docker web management uses `portainer`. The activation method is to enter `ttyd` and enter the command: `/etc/docker-web` to activate it. The access URL is `IP: 9999`


The firmware default configuration includes instructions for docker see: https://github.com/ophub/amlogic-s9xxx-openwrt/blob/main/router_config/.config
In Line 393:
CONFIG_PACKAGE_luci-app-docker=y
In Line 537:
CONFIG_PACKAGE_docker-compose=y
