### ISSUE TITLE
workflows build fail!

### ISSUE THREAD

**Issue by kyliezero** [ophub/amlogic-s9xxx-openwrt#162]
why does my built always fail? I've tried the build several times still the same, it's a waste of time, really really annoying! -_-
![Screenshot_2021-11-13_20-58-05](https://user-images.githubusercontent.com/87708571/141646748-73bb885a-a6ed-49de-b0b1-3aa33e799d57.png)

**Comment by ophub** [comment]
I will compile it now and have a look.
https://github.com/ophub/amlogic-s9xxx-openwrt/actions

**Comment by ophub** [comment]
Can compile normally

**Comment by kyliezero** [comment]
> I will compile it now and have a look. https://github.com/ophub/amlogic-s9xxx-openwrt/actions

I see it runs smoothly, is it possible that because I added diy-part2.sh there is a problem?
I tried to add the package openclash & passwall with this command into diy-part2.sh

`svn co https://github.com/xiaorouji/openwrt-passwall/trunk package/openwrt-passwall`
`svn co https://github.com/vernesong/OpenClash/trunk/luci-app-openclash package/openwrt-openclash
pushd package/openwrt-openclash/tools/po2lmo && make && sudo make install 2>/dev/null && popd`
