### ISSUE TITLE
change location temperature for 860v1 dtb

### ISSUE THREAD

**Issue by Manssizz** [ophub/amlogic-s9xxx-openwrt#165]
hi... 
can u add conditional for pick temp location? 
because b860 dtb use this location for checking temp unit
`cpu_temp="$(awk '{ printf("%.1f °C", $0 / 1000) }' /sys/class/hwmon/hwmon0/temp1_input)"`
for now, i use manual changing with mark your script as comment and add these script. 
thx!

**Comment by ophub** [comment]
Where to display, screenshot
```
cat /boot/uEnv.txt
cat /etc/flippy-openwrt-release
echo $(awk '{ printf("%.1f °C", $0 / 1000) }' /sys/class/hwmon/hwmon0/temp1_input)
echo $(sensors | grep -Eo '\+[0-9]+.+C' | sed ':a;N;$!ba;s/\n/ /g;s/+//g')
echo $(awk '{ printf("%.1f °C", $0 / 1000) }' /sys/class/thermal/thermal_zone0/temp)
```
The above commands are executed one by one, and the screenshots are given to me.

**Comment by Manssizz** [comment]
Ah sorry i forgot write file location
On `/etc/profile.d/30-sysinfo.sh` have line code with `cpu_temp="$(awk '{ printf("%.1f °C", $0 / 1000) }' 
/sys/class/thermal/thermal_zone0/temp)"`
I replace with
`cpu_temp="$(awk '{ printf("%.1f °C", $0 / 1000) }' /sys/class/hwmon/hwmon0/temp1_input)"`

![Screenshot_20211115-123941](https://user-images.githubusercontent.com/23637327/141728625-a123aac7-19be-45ad-b03d-2b6dc4846180.png)

**Comment by ophub** [comment]
0fc863a

You try, feedback the result.

**Comment by Manssizz** [comment]
it works! thank you
![Screenshot_20211116_003017](https://user-images.githubusercontent.com/23637327/141827299-9e46888c-5749-42ad-882a-98e44005f7a3.png)
