### ISSUE TITLE
Install To EMMC

### ISSUE THREAD

**Issue by adisubagja** [ophub/amlogic-s9xxx-openwrt#167]
I have two device b860h and then have different model emmc
first i trying install on emmc ( Model MMC DG4008 ) This works as well perfectly but on emmc ( Model MMC 8GTF4R ) Installed but can't boot ? why any solution for this ?

**Comment by ophub** [comment]
It is better to use on USB, with more space and complete functions.

**Comment by adisubagja** [comment]
![Screenshot_20211120-064631~2](https://user-images.githubusercontent.com/15952175/142704865-a0f1c0d3-8126-4a78-a24e-f0fc27872d47.jpg)
Yes but i want to intall to emmc this screenshoot done installed but can't boot

**Comment by ophub** [comment]
Connect the monitor to see what prompt message is.

**Comment by adisubagja** [comment]
Hmmm ok,
Thanks will try again im must buy monitor first :D
