### ISSUE TITLE
X96 Max Plus error on booting

### ISSUE THREAD

**Issue by Syarizal79** [ophub/amlogic-s9xxx-openwrt#168]
![IMG_20211120_231422](https://user-images.githubusercontent.com/94752560/142731922-b69eb550-1ccd-4fdd-993b-91e5b900883c.jpg)

I use thumb drive for flash but while booting to X96 Max Plus it stuck on this error

**Comment by ophub** [comment]
This is a success. The device is connected to the computer, and your browser visits 192.168.1.1
