### ISSUE TITLE
Hk1-Box Wifi bug when device connected to USB3 port

### ISSUE THREAD

**Issue by dvinz** [ophub/amlogic-s9xxx-openwrt#169]
Hi,

Model | HK1 Box/Vontar X3
Firmware Version | OpenWrt  R2021.11.19  / 	LuCI Master (git-21.320.49600-21168d4)
Kernel Version | 5.10.80-flippy-67+

When a USB3 device is connected (usb3 network adapter), Wifi are disconnected.

**Comment by ophub** [comment]
I don’t understand what the built-in wifi has to do with your external USB device. Did you connect a USB wifi conflict?

Try it yourself.
