### ISSUE TITLE
Req...

### ISSUE THREAD

**Issue by riyuejz** [ophub/amlogic-s9xxx-openwrt#17]
next update can you add the rclone package from https://github.com/ElonH/Rclone-OpenWrt 🙏

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-openwrt/blob/main/router_config/.config
I added this plug-in on `line 404`.
`CONFIG_PACKAGE_luci-app-rclone=y`

the new firmware is being compiled, please pay attention. 
https://github.com/ophub/amlogic-s9xxx-openwrt/actions/runs/602000028

**Comment by ramasedang** [comment]
@ophub so helpfull, tanks bro

**Comment by ramasedang** [comment]
So, if I want to use package in the list I must recompile it? Or just opkg install...

**Comment by ophub** [comment]
luci-app-rclone has been compiled to the latest firmware, you can download and install.

Other packages that are not available can also be installed online like this: 

System > Package > Update, then select the package and install it.
Most of the packages that are not precompiled can be installed in this way, and some need to install dependent packages first.

The software package to be used is recommended to be selected at compile time.

**Comment by ramasedang** [comment]
"System > Package > Update, then select the package and install it.
Most of the packages that are not precompiled can be installed in this way, and some need to install dependent packages first."

**Comment by ophub** [comment]
![Uploading EE80B556-1C48-48FF-9B00-DD7130AF231B.png…]()

**Comment by ophub** [comment]
![2D42DD8E-4FC6-42DC-894C-23B350080EB7](https://user-images.githubusercontent.com/68696949/109295870-72a1b980-786a-11eb-8dcd-6a91dce9480a.png)

**Comment by ramasedang** [comment]
@ophub 
i try instal luci-app-softethervpn...... 

 "You can add them by yourself. For example, modify # CONFIG_PACKAGE_luci-app-acme is not set to CONFIG_PACKAGE_luci-app-acme=y"

where i can edit the config? in firmware or before compiled

![Screenshot (119)](https://user-images.githubusercontent.com/76695790/109297665-f3f64d80-7864-11eb-8dd7-125ed9da1794.png)

![Screenshot (120)](https://user-images.githubusercontent.com/76695790/109297671-f8bb0180-7864-11eb-93da-a3be6af292a0.png)

**Comment by ophub** [comment]
![fork_button](https://user-images.githubusercontent.com/68696949/109303990-85ba8680-7876-11eb-83c9-aeaf415d8878.jpg)

Click the `fork` button to copy my repo to your personal center, and then you can compile it in your own repo. For related functions, see the instructions on the official github.com websit.

https://docs.github.com/en/github/getting-started-with-github/fork-a-repo

**Comment by ramasedang** [comment]
Thanks for your help 🙏

**Comment by ophub** [comment]
Some software can be installed directly in the mirror server. For example, after clicking the update list, search for `luci-app-nlbwmon`, and this software package will have.

The mirror server can also retrieve the latest version of the installed software package, depending on the mirror server you set up. There are many openwrt mirror sites in various countries. You can find it on Google.com

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-openwrt/tree/main/router_config

Here is a description of personalized customization.

In the readme.md of various places, I have introduced each function as detailed as possible. You can check the readme.md in each module. If there is something unclear, you can open an `issue` at any time.
