### ISSUE TITLE
Wireguard not found

### ISSUE THREAD

**Issue by dvinz** [ophub/amlogic-s9xxx-openwrt#170]
Hi,

How install wireguard, luci-app-wireguard ?

Best regard

**Comment by ophub** [comment]
https://github.com/openwrt/luci/tree/master/applications/luci-app-wireguard

https://github.com/ophub/amlogic-s9xxx-openwrt/blob/main/router-config/README.md#42-diy-script-operation-diy-part1sh-and-diy-part2sh
