### ISSUE TITLE
Support device X96Max Plus2 T

### ISSUE THREAD

**Issue by adisik** [ophub/amlogic-s9xxx-openwrt#175]
I have X96Max Plus2 T with 1000М Ethernet RTL8211F chip and WIFI AM7256. 
Is it possible to install an Openwrt on this hardware?

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-openwrt/issues/138

RTL8211F can use.

**Comment by adisik** [comment]
My board

![20211127_142748](https://user-images.githubusercontent.com/12948757/143735025-c0603b95-42e2-4d6f-b011-bcc9eff03146.jpg)

**Comment by adisik** [comment]
Messages, when i try boot from USB flash with openwrt image:
![20211127_175809](https://user-images.githubusercontent.com/12948757/143735082-c3bb219c-c392-4b83-b5af-d34818006ee6.jpg)
![20211127_165451](https://user-images.githubusercontent.com/12948757/143735087-df459b40-d9bb-4305-ad65-867f6e4f7e68.jpg)

**Comment by adisik** [comment]
@ophub , As I understand it, Openwrt not loaded correct?

**Comment by ophub** [comment]
This is the start, right? Connect the keyboard and press Enter to see the banner.

https://github.com/ophub/amlogic-s9xxx-openwrt/blob/main/router-config/README.md#1010-turn-on-the-usb-disk-boot-mode-of-the-amlogic-s9xxx-stb

**Comment by test012012** [comment]
Hi @adisik .I have the same board. Could you please describe which image you use and how you boot Armbian or openwrt. Do you boot (first time) from SD card or from USB flash/hard disk?

I can see only black screen after boot logo
