### ISSUE TITLE
Terminal information

### ISSUE THREAD

**Issue by lynxnexy** [ophub/amlogic-s9xxx-openwrt#176]
how to display external storage info into the terminal page information, I'm here using hdd with fs ntfs..
![IMG_20211202_195729](https://user-images.githubusercontent.com/81577496/144427349-0d46c4c2-73f1-49a7-8dd0-74e672580b3a.jpg)

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-openwrt/blob/4c69ff7b2f241cfc659127b4a4ced7433efbf787/amlogic-s9xxx/common-files/patches/cpustat/30-sysinfo.sh#L176

There are various names of external devices, such as sda, sdb, mmcblk× and so on. It is not recommended that you add them here. If you change the external device in the future, an error will be reported. This is just a welcome screen, just take a look.
