### ISSUE TITLE
release name

### ISSUE THREAD

**Issue by lynxnexy** [ophub/amlogic-s9xxx-openwrt#178]
how to change the output release name..
Expl: openwrt_kylie_k5.10.86_2021.12.17.1844.img.gz

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-openwrt/blob/main/make#L386

build_image_file="${out_path}/openwrt_kylie_${build_op}_k${kernel}_$(date +"%Y.%m.%d.%H%M").img"

**Comment by lynxnexy** [comment]
Thanks 🙏
