### ISSUE TITLE
bluetooth

### ISSUE THREAD

**Issue by p0000h** [ophub/amlogic-s9xxx-openwrt#179]
how to make internal BT to work  in X96air_p2?

 -----------------------------------------------------
 Install: OpenWrt → System → Amlogic Service → Install
 Update: OpenWrt → System → Amlogic Service → Update
 Amlogic SoC: s905x3
 OpenWrt Kernel: 5.10.87-flippy-68+
 Packaged Date: 2021-12-17
 -----------------------------------------------------
 Device Model: Shenzhen Amediatech Technology Co., Ltd X96 Air
 Architecture: AArch64 : Cortex-A55 x 4
 Load Average: 0.01 0.09 0.08   Uptime:  10m 38s
 Ambient Temp: 61.1  °C         Frequency:  %s1908 Mhz
 Memory Usage: 3% of 3815MB     IP Address:  172.31.255.22 10.1.30.54
 Boot Storage: 50% of 157.5M    SYS Storage:   29% of 960.0M 
 Data Storage: 11% of 26.3G  

root@OpenWrt:~# opkg install kmod-bluetooth bluez-libs bluez-utils kmod-usb-core kmod-usb-uhci kmod-usb2 usbutils
Multiple packages (libgcc1 and libgcc1) providing same name marked HOLD or PREFER. Using latest.
Unknown package 'kmod-bluetooth'.
Multiple packages (libgcc1 and libgcc1) providing same name marked HOLD or PREFER. Using latest.
Installing bluez-libs (5.62-1) to root...
Downloading https://mirrors.cloud.tencent.com/lede/snapshots/packages/aarch64_cortex-a53/packages/bluez-libs_5.62-1_aarch64_cortex-a53.ipk
Installing bluez-utils (5.62-1) to root...
Downloading https://mirrors.cloud.tencent.com/lede/snapshots/packages/aarch64_cortex-a53/packages/bluez-utils_5.62-1_aarch64_cortex-a53.ipk
Installing bluez-libs (5.62-1) to root...
Upgrading kmod-usb-core on root from 5.4.162-1 to 5.10.87-1...
Downloading https://mirrors.cloud.tencent.com/lede/snapshots/targets/armvirt/64/packages/kmod-usb-core_5.10.87-1_aarch64_cortex-a53.ipk
Package kmod-usb-uhci (5.4.162-1) installed in root is up to date.
Package kmod-usb2 (5.4.162-1) installed in root is up to date.
Upgrading usbutils on root from 013-2 to 014-1...
Downloading https://mirrors.cloud.tencent.com/lede/snapshots/packages/aarch64_cortex-a53/packages/usbutils_014-1_aarch64_cortex-a53.ipk
Configuring usbutils.
Configuring bluez-libs.
Configuring bluez-utils.
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.87-1-1c8b2a1aac2b849f3e942408ce72c6d1) for kmod-nls-base
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.87-1-1c8b2a1aac2b849f3e942408ce72c6d1) for kmod-usb-core
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.87-1-1c8b2a1aac2b849f3e942408ce72c6d1) for kmod-crypto-hash
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.87-1-1c8b2a1aac2b849f3e942408ce72c6d1) for kmod-crypto-null
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.87-1-1c8b2a1aac2b849f3e942408ce72c6d1) for kmod-crypto-aead
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.87-1-1c8b2a1aac2b849f3e942408ce72c6d1) for kmod-crypto-manager
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.87-1-1c8b2a1aac2b849f3e942408ce72c6d1) for kmod-crypto-ecb
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.87-1-1c8b2a1aac2b849f3e942408ce72c6d1) for kmod-lib-crc16
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.87-1-1c8b2a1aac2b849f3e942408ce72c6d1) for kmod-input-core
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.87-1-1c8b2a1aac2b849f3e942408ce72c6d1) for kmod-input-evdev
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.87-1-1c8b2a1aac2b849f3e942408ce72c6d1) for kmod-hid
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.87-1-1c8b2a1aac2b849f3e942408ce72c6d1) for kmod-crypto-cmac
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.87-1-1c8b2a1aac2b849f3e942408ce72c6d1) for kmod-regmap-core
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-regmap-core found, but incompatible with the architectures configured
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.87-1-1c8b2a1aac2b849f3e942408ce72c6d1) for kmod-crypto-kpp
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-crypto-kpp found, but incompatible with the architectures configured
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.87-1-1c8b2a1aac2b849f3e942408ce72c6d1) for kmod-crypto-ecdh
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-crypto-ecdh found, but incompatible with the architectures configured
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.87-1-1c8b2a1aac2b849f3e942408ce72c6d1) for kmod-bluetooth
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-bluetooth found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package kmod-bluetooth.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for bluez-libs:
 *      kernel (= 5.10.87-1-1c8b2a1aac2b849f3e942408ce72c6d1)
 * opkg_install_cmd: Cannot install package bluez-libs.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-usb-core:
 *      kernel (= 5.10.87-1-1c8b2a1aac2b849f3e942408ce72c6d1)
 * opkg_install_cmd: Cannot install package kmod-usb-core.
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.87-1-1c8b2a1aac2b849f3e942408ce72c6d1) for kmod-usb-uhci
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.87-1-1c8b2a1aac2b849f3e942408ce72c6d1) for kmod-usb-ehci
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.87-1-1c8b2a1aac2b849f3e942408ce72c6d1) for kmod-usb2

**Comment by ophub** [comment]
The kmod module cannot be installed later, please select before compiling, and the content that needs to be added is written in the [.config](https://github.com/ophub/amlogic-s9xxx-openwrt/blob/main/router-config/lede-master/.config) file.

Confirm the Bluetooth model of your device, check whether Linux provides support in `make menuconfig`, if you have it, you can choose, if you don’t, you can’t use Bluetooth.
