### ISSUE TITLE
compile official

### ISSUE THREAD

**Issue by dotamidplayer** [ophub/amlogic-s9xxx-openwrt#180]
how to compile official 21.02.1 version? not snapshot branch

**Comment by dotamidplayer** [comment]
and when edit some config to not included some luci apps, after done compiling luci refuces to connect in browser, need download in CLI opkg install luci to fix it.

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-openwrt/blob/main/router-config/README.md

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-openwrt/actions/workflows/build-openwrt-official-21.02.yml

**Comment by dotamidplayer** [comment]
i read the article and cant find it
