### ISSUE TITLE
spam log thermal monitoring luci uhttpd

### ISSUE THREAD

**Issue by Manssizz** [ophub/amlogic-s9xxx-openwrt#182]
- Device: b860h v1
- Case: syslog full spammed with thermal monitoring No such file or directory
- Linked issue: https://github.com/ophub/amlogic-s9xxx-openwrt/issues/165
- Sample proof:
```
Thu Dec 30 12:57:01 2021 daemon.err uhttpd[2855]: awk: /sys/class/thermal/thermal_zone0/temp: No such file or directory
Thu Dec 30 12:57:08 2021 daemon.err uhttpd[2855]: awk: /sys/class/thermal/thermal_zone0/temp: No such file or directory
Thu Dec 30 12:57:13 2021 daemon.err uhttpd[2855]: awk: /sys/class/thermal/thermal_zone0/temp: No such file or directory
Thu Dec 30 12:57:18 2021 daemon.err uhttpd[2855]: awk: /sys/class/thermal/thermal_zone0/temp: No such file or directory
Thu Dec 30 12:57:23 2021 daemon.err uhttpd[2855]: awk: /sys/class/thermal/thermal_zone0/temp: No such file or directory
Thu Dec 30 12:57:29 2021 daemon.err uhttpd[2855]: awk: /sys/class/thermal/thermal_zone0/temp: No such file or directory
Thu Dec 30 12:57:34 2021 daemon.err uhttpd[2855]: awk: /sys/class/thermal/thermal_zone0/temp: No such file or directory
Thu Dec 30 12:57:40 2021 daemon.err uhttpd[2855]: awk: /sys/class/thermal/thermal_zone0/temp: No such file or directory
```
![Screenshot_20211230_130350](https://user-images.githubusercontent.com/23637327/147725985-0c8d94e4-3a93-46c2-96c7-2067a3f52f56.png)

**Comment by ophub** [comment]
In the system-ttyd terminal, or ssh into openwrt, enter the following command, and give me a screenshot.

`sed -n 130,140p /etc/profile.d/30-sysinfo.sh`

**Comment by ophub** [comment]
If your version is one month ago, you can update to the latest.

```
#Download the latest file
wget -O /etc/profile.d/30-sysinfo.sh https://raw.githubusercontent.com/ophub/amlogic-s9xxx-openwrt/main/amlogic-s9xxx/common-files/patches/cpustat/30-sysinfo.sh

#Grant permissions (can be ignored)
chmod +x /etc/profile.d/30-sysinfo.sh

reboot
```

**Comment by Manssizz** [comment]
use latest version of 30-sysinfo.sh based you repos
![image](https://user-images.githubusercontent.com/23637327/147783281-f4ba8af3-1237-43e8-a020-4ee9da549ee0.png)

**Comment by ophub** [comment]
```
elif [ -f "/sys/class/thermal/thermal_zone0/temp" ]; then
	cpu_temp="$(awk '{ printf("%.1f °C", $0 / 1000) }' /sys/class/thermal/thermal_zone0/temp)"
```
30-sysinfo.sh: delete line 133-134

**Comment by Manssizz** [comment]
still shown btw
![image](https://user-images.githubusercontent.com/23637327/147808261-30c1c420-e362-474c-aeee-852ede7e965c.png)

seems this issue linked with uhttpd scripts
![image](https://user-images.githubusercontent.com/23637327/147808306-9bf668bc-1636-491f-9585-b14f0dd573e8.png)
