### ISSUE TITLE
Compilation failed

### ISSUE THREAD

**Issue by riyuejz** [ophub/amlogic-s9xxx-openwrt#183]
hi can you help me to add luci-app-openclash into build openwrt-21.02, i tried by adding line

#diy-part2.sh
`svn co https://github.com/vernesong/OpenClash/trunk/luci-app-openclash package/openwrt-openclash
pushd package/openwrt-openclash/tools/po2lmo && make && sudo make install 2>/dev/null && popd`

#config
`CONFIG_PACKAGE_luci-app-openclash=y`

but compiling results always fails

**Comment by ophub** [comment]
Your approach is correct. What error was reported? Send a screenshot.

**Comment by riyuejz** [comment]
The logs are too big to read, it's hard to know where the error is, but after adding this package, the compilation failed
![Screenshot_2022-01-01-07-14-59-777_com android chrome](https://user-images.githubusercontent.com/50128745/147841544-91d5c9fb-d55b-42a1-9922-1e8eb4799b56.jpg)

**Comment by ophub** [comment]
You can look forward to find out if there are any errors.

Yours is a problem that you may encounter when compiling openwrt-21.02, and github will get stuck and report an error in the long log.

No need to change anything, do it again.

**Comment by ophub** [comment]
I see your repo has been successful
