### ISSUE TITLE
restore defualt u-boot.bin into eMMC

### ISSUE THREAD

**Issue by 0neday** [ophub/amlogic-s9xxx-openwrt#188]
I have check your [make script](https://github.com/ophub/amlogic-s9xxx-openwrt/blob/main/make#L477) carefully
```
    elif [[ "${ANDROID_UBOOT}" != "" && -f "${root}${ANDROID_UBOOT}" ]]; then
        dd if=${root}${ANDROID_UBOOT} of=${loop} bs=1 count=444 conv=fsync 2>/dev/null
        dd if=${root}${ANDROID_UBOOT} of=${loop} bs=512 skip=1 seek=1 conv=fsync 2>/dev/null
        #echo -e "${build_op}_v${kernel} write Android bootloader: ${ANDROID_UBOOT}"
```
can I use 
```
dd if=/lib/u-boot/u-boot-2015-phicomm-n1.bin of=/dev/mmcblk2  bs=1 count=444 conv=fsync
dd if=/lib/u-boot/u-boot-2015-phicomm-n1.bin of=/dev/mmcblk2  bs=512 skip=1 seek=1 conv=fsync
```
to update u-boot? so that I can boot from usb after reboot without losing current system.

> and ...

what different `u-boot-n1.bin`、 `u-boot.sd` 、`u-boot.usb` in BOOTC partition?

**Comment by ophub** [comment]
you can do this

.bin is made for kernels above 5.10 kernel, not needed for 5.4.y kernel
