### ISSUE TITLE
How to add multi-language support

### ISSUE THREAD

**Issue by codesnas** [ophub/amlogic-s9xxx-openwrt#19]
I want to use the Chinese management interface, how to compile and set it

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-openwrt/blob/main/router_config/.config

In line 75, it is the language pack supporting Chinese
`CONFIG_PACKAGE_luci-i18n-base-zh-cn=y`

Please refer to the official description of openwrt.org for the correspondence between more language packs:

https://openwrt.org/packages/pkgdata/luci-i18n-base-lang

**Comment by codesnas** [comment]
thanks
