### ISSUE TITLE
Compile error when adding third party packages

### ISSUE THREAD

**Issue by ozipoetra** [ophub/amlogic-s9xxx-openwrt#199]
Hi ophub, i have a problem when compiling the official build. I'm adding openclash, but when compiling it's give me an error. But this problem didn't occur when using lede build and the openclash successful pre-installed. So, what is the problem with the official or I'm missing something?

> diy-part2.sh

`svn co https://github.com/vernesong/OpenClash/trunk/luci-app-openclash package/luci-app-openclash`

log: https://github.com/ozipoetra/amlogic-s9xxx-openwrt/commit/abe81a3d35cd9638db37034c5a37f523a045b83d/checks/4951041987/logs

**Comment by ophub** [comment]
The official code repository lacks dependencies. Fill in the complete dependencies according to his instructions. Add from a third party (hint: there is a collection in the repository of a similar plug-in, you can import the complete one at a time, but don't ask me which one, you guess it yourself)
