### ISSUE TITLE
Error after installing luci-proto-qmi

### ISSUE THREAD

**Issue by latiefkhan** [ophub/amlogic-s9xxx-openwrt#2]
Iam using Hk1 box openwrt kernel version is 5.9.16
And i got same error in kernel 5.4.86, after installing luci-proto-qmi,
When i accessing network interface i got error,
Here's the error message.

/usr/lib/lua/luci/dispatcher.lua:469: Failed to execute cbi dispatcher target for entry '/admin/network/iface_add'.
The called action terminated with an exception:
/usr/lib/lua/luci/model/network/proto_qmi.lua:53: attempt to call method 'register_error_code' (a nil value)
stack traceback:
	[C]: in function 'assert'
	/usr/lib/lua/luci/dispatcher.lua:469: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:121: in function </usr/lib/lua/luci/dispatcher.lua:120>

**Comment by ophub** [comment]
Do you use a 4G network card for wan Internet access? Since your USB network card is not included when the firmware is compiled, it cannot be recognized by default. You can add support for your USB network card after fork. Enter the USB network card in the router_config/.config file (SSH connection to Actions is recommended)

make menuconfig：
Base system  ---> udev 
Kernel modules  ---> USB Support  ---> kmod-usb-acm kmod-usb-net kmod-usb-net-qmi-wwan kmod-usb-ohci kmod-usb-serial kmod-usb-serial-option L
uCI  ---> Protocols  ---> luci-proto-3g luci-proto-qmi 
Network  ---> uqmi 
Utilities  ---> usb-modeswitch usbutils

make kernel_menuconfig：
device drivers->usb support->support for host-side usb SELECT USB Modem (CDC ACM) support

USB Serial Converter support：
USB driver for GSM and CDMA modems

**Comment by ophub** [comment]
http://h-wrt.com/en/mini-how-to/qmi_ow

**Comment by latiefkhan** [comment]
Iam using Quallcomm usb modem 4g LTE device,
Okay i will try to make menuconfig

**Comment by latiefkhan** [comment]
it's still doesn't work sir. :(
Iam so borred. How to resolve this :(

**Comment by latiefkhan** [comment]
And i doesn't use ubuntu desktop.
Iam using windows 10,
 so please make the firmware pacakage included what i need sir.

**Comment by ophub** [comment]
1.fork to your repository.

2.On the Action page. Select Build OpenWrt in the list on the left, and Click the Run workflow button on the right. Set SSH connection to Actions: **true** to use tmate to connect to the GitHub Actions virtual server environment. 

You can directly perform the make menuconfig operation to generate the compilation configuration, or any customized operation. After triggering the workflow, wait for the SSH connection to Actions step to be executed on the Actions page, and then the following three lines of messages will be displayed: 1. To connect to this session copy-n-paste the following into a terminal or browser, 2.ssh Y26QenMRd@nyc1.tmate.io, 3.https://tmate.io/t/Y26QenMRd. Then copy the SSH connection command and paste it into the terminal for execution, or copy the link to open it in the browser and use the web terminal. enter the command: cd openwrt && make menuconfig for personalized configuration (The web terminal may encounter a black screen, just press Ctrl+C). After completion, press the shortcut key Ctrl+D or execute the exit command to exit, and the subsequent compilation work will proceed automatically.

**Comment by ophub** [comment]
Fork the latest repository source code
I added a personalized selection of network equipment to the configuration file /router_config/.config. You can check the specific model of your equipment, select the suitable one, and compile it.

https://github.com/ophub/amlogic-s9xxx-openwrt/blob/main/router_config/.config
in 207 line # WWAN
in 217 line # Network Devices

Add the plugin source you imported in /router_config/diy-part2.sh
Add your plug-in name luci-proto-qmi=y in luci-app of /router_config/.config

Just compile

**Comment by ophub** [comment]
How To use LTE modem in QMI mode for WAN connection

https://openwrt.org/docs/guide-user/network/wan/wwan/ltedongle

**Comment by latiefkhan** [comment]
> 
> 
> How To use LTE modem in QMI mode for WAN connection
> 
> https://openwrt.org/docs/guide-user/network/wan/wwan/ltedongle

that's tutorial is make same error too sir

**Comment by ophub** [comment]
This tutorial fully introduces how to use it. It should be possible to choose the correct driver for the device.

https://github.com/ophub/amlogic-s9xxx-openwrt/blob/main/router_config/.config
in 207 line # WWAN
in 217 line # Network Devices

**Comment by latiefkhan** [comment]
> 
> 
> This tutorial fully introduces how to use it. It should be possible to choose the correct driver for the device.
> 
> https://github.com/ophub/amlogic-s9xxx-openwrt/blob/main/router_config/.config
> in 207 line # WWAN
> in 217 line # Network Devices

yes i hope this one will work, iam still compiling the file

**Comment by latiefkhan** [comment]
have you done released new version of openwrt hk1 box.?
but, why i unnable to download the file..?

**Comment by ophub** [comment]
Compiling, download in Release after 3 hours

**Comment by latiefkhan** [comment]
> Compiling, download in Release after 3 hours

including my request problem.?

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-openwrt/actions/runs/455868305

Compiling, download after 3 hours

**Comment by ophub** [comment]
> > Compiling, download in Release after 3 hours
> 
> including my request problem.?

Add LTE support according to the tutorial on the openwrt official website, you can try to install  luci-proto-qmi. Not sure if it matches the model of your device. You can modify it in the .config file

**Comment by latiefkhan** [comment]
same problem sir when installing luci-proto-qmi
![Screenshot_3](https://user-images.githubusercontent.com/76825535/103435984-71c52080-4c49-11eb-963c-affa6daa329c.png)

**Comment by ophub** [comment]
> same problem sir when installing luci-proto-qmi
> ![Screenshot_3](https://user-images.githubusercontent.com/76825535/103435984-71c52080-4c49-11eb-963c-affa6daa329c.png)

After three hours, test whether the firmware with LTE support can be used normally. Which is your device? Find the same paragraph at https://www.ebay.com/ and send it.

**Comment by latiefkhan** [comment]
https://www.ebay.com/itm/T77W676-917817-001-lt4220-X12-LTE-4G-WWAN-M-2-450Mbps-Modem-1030-hp-EliteX-G4P6/133173804804?hash=item1f01c6ff04:g:jBoAAOSwMXddgB3c

**Comment by latiefkhan** [comment]
this log of modem on my s905x running well

![Screenshot_4](https://user-images.githubusercontent.com/76825535/103436209-a76b0900-4c4b-11eb-9444-17c8d164f44a.png)

**Comment by latiefkhan** [comment]
but i have no idea, why in my HK1 box is always getting error :(

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-openwrt/releases/tag/openwrt_s9xxx_2021.01.01.1907

Compilation is complete, you can download this version to test

**Comment by latiefkhan** [comment]
has been tested, and same result sir. after installing luci-proto-qmi, and accessing- network-interface "same error
![Screenshot_7](https://user-images.githubusercontent.com/76825535/103438297-777c2f80-4c64-11eb-9146-8544254f3794.png)

**Comment by ophub** [comment]
Is your luci-proto-qmi the latest compatible openwrt R20.12.12? Does this plugin need other dependent packages?

**Comment by ophub** [comment]
https://openwrt.org/packages/pkgdata/luci-proto-qmi
release: OpenWrt-19.07.0


You can select the specified version to compile on line 64 of https://github.com/ophub/amlogic-s9xxx-openwrt/blob/main/.github/workflows/build-openwrt.yml

**Comment by latiefkhan** [comment]
> 
> 
> Is your luci-proto-qmi the latest compatible openwrt R20.12.12? Does this plugin need other dependent packages?

iam installing luci-proto-qmi
![Uploading Screenshot_8.png…]()
 using this method

**Comment by latiefkhan** [comment]
now, iam done installing luci-proto-qmi, but the new problem is, any protocol i have installed mannualy, isn't showing up.
![Screenshot_9](https://user-images.githubusercontent.com/76825535/103443331-cb9d0900-4c90-11eb-9f63-11bebe1f334b.png)
![Screenshot_10](https://user-images.githubusercontent.com/76825535/103443333-cf309000-4c90-11eb-94c1-190f9f510d9f.png)

**Comment by ophub** [comment]
What agreement? Newly installed protocols generally need to be restarted to take effect. Send the name, let me see if it needs to be selected at compile time.

**Comment by latiefkhan** [comment]
> What agreement? Newly installed protocols generally need to be restarted to take effect. Send the name, let me see if it needs to be selected at compile time.

it must be showing 'Qmi Cellular protocol., Because the luci-proto-qmi has been successfully installed.

**Comment by ophub** [comment]
> > What agreement? Newly installed protocols generally need to be restarted to take effect. Send the name, let me see if it needs to be selected at compile time.
> 
> it must be showing ''Qmi Cellular'' protocol., Because the luci-proto-qmi has been successfully installed.
> Restarted Hk1 box is not work sir. Still not showing up.

https://github.com/ophub/amlogic-s9xxx-openwrt/blob/main/router_config/.config
Added relevant Protocols to support luci-proto in line 290, try again after compilation is complete.

The compilation process:
https://github.com/ophub/amlogic-s9xxx-openwrt/actions/runs/456972031

**Comment by latiefkhan** [comment]
this update is verry perfect my LTE CAT12 modem Running well sir, verry amazing. thank you so much for helping me sir.

**Comment by latiefkhan** [comment]
issues closed!!
