### ISSUE TITLE
Enable dvb support

### ISSUE THREAD

**Issue by j3dd4h** [ophub/amlogic-s9xxx-openwrt#203]
How we can enable DVB support for availink?  
https://github.com/availink/dvb-frontends-availink

**Comment by ophub** [comment]
https://github.com/unifreq/linux-5.10.y/tree/main/drivers/media

https://github.com/availink/dvb-frontends-availink/pull/2

Put into the corresponding directory of the supported kernel, add Add Kconfig/Kbuild to compile
