### ISSUE TITLE
Help needed for compile

### ISSUE THREAD

**Issue by xtendpayaa** [ophub/amlogic-s9xxx-openwrt#204]
Hello again ophub!
Not really question about your fw but almost :) Because I realized the x86 hardware more powerful than this little boxes and maybe better choice and there is x86_64 fw from openwrt officially.
But I need that options what your fw have, not all but at least the wifi access default (like in yours fw because normally is disabled) and built-in driver for tp-link UE300 (kmod-usb-net-rtl8152) and wifi dongle TP-LINK archer T2UH (chipset: MediaTek MT7610U)
So how can I build this like fw from official x86? Thank you!

**Comment by ophub** [comment]
Sorry, I don't know what to do.
I found the official documentation overview, you can go to the official website to get the most complete solution: https://openwrt.org/docs/start
