### ISSUE TITLE
Unbrick Ugoos AM6 after installing

### ISSUE THREAD

**Issue by DangerD1024** [ophub/amlogic-s9xxx-openwrt#213]
I accidentially clicked on install to nand, now box is not booting up and i unable to reflash it back using USB burning tool...
Is there any way to reflash it back to android?

**Comment by DangerD1024** [comment]
everything is fine, maskrom button helped =)

**Comment by ophub** [comment]
There are several ways to restore the system

How to recover if the install fails and cannot be started:
https://github.com/ophub/amlogic-s9xxx-openwrt/tree/main/router-config#108-how-to-recover-if-the-install-fails-and-cannot-be-started

Backup/restore the original EMMC system:
https://github.com/ophub/amlogic-s9xxx-openwrt#backuprestore-the-original-emmc-system

Which firmware are you using in Ugoos AM6, what dtb and u-boot are you using?
You can view it with the following command
`cat /etc/flippy-openwrt-release`

**Comment by maverle95-glitch** [comment]
Are both Ugoos AM6 and Ugoos AM6 Plus devices supported?
