### ISSUE TITLE
t95z

### ISSUE THREAD

**Issue by 392377870** [ophub/amlogic-s9xxx-openwrt#218]
t95z MAX刷入卡开机界画面，什么原因也不清楚，s912主控，刷armbian能整常启动
![IMG_20220304_194618](https://user-images.githubusercontent.com/23136114/156758253-64ecbcc8-105d-41d1-b25e-2c41dcba8956.jpg)

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/common-files/patches/boot/s912-t95z-plus/extlinux/extlinux.conf

**Comment by 392377870** [comment]
![IMG_20220304_222800](https://user-images.githubusercontent.com/23136114/156781507-7b530520-5d68-4f84-9f8d-f355ae55c80f.jpg)
还是卡住
