### ISSUE TITLE
please fix this

### ISSUE THREAD

**Issue by lynxnexy** [ophub/amlogic-s9xxx-openwrt#219]
![Screenshot_2022-03-04_21-07-06](https://user-images.githubusercontent.com/81577496/156779023-72fccf7f-a105-4ec8-b08a-c234b99e0315.png)

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-openwrt/commit/d0e3e2f4bc6b4ade83cd47c02df92486d2a43b89

Thanks for the feedback, it has been fixed
