### ISSUE TITLE
3ginfo modem

### ISSUE THREAD

**Issue by riyuejz** [ophub/amlogic-s9xxx-openwrt#22]
Hi, can you add this package to the firmware .. I tried to install manually * ipk but it didn't work .. 🙏 
https://github.com/4IceG/luci-app-3ginfo

**Comment by ophub** [comment]
https://github.com/4IceG/luci-app-3ginfo/releases/tag/1.3.1

you can download and use opkg install

**Comment by riyuejz** [comment]
Ok

**Comment by riyuejz** [comment]
![Uploading Screenshot_2021-03-02-07-40-49-767_com.termux.jpg…]()
