### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by vpei** [ophub/amlogic-s9xxx-openwrt#227]
本地编译，每次都需要重新下载文件，能不能检测存在的文件就不下载了？

**Comment by vpei** [comment]
国内这个访问速度特别慢，用代理也不稳定。

**Comment by ophub** [comment]
好主要，安排

**Comment by lynxnexy** [comment]
can you fix this problem
![Screenshot_2022-03-11_08-51-44](https://user-images.githubusercontent.com/81577496/157834285-d728a896-5232-4d6e-8458-a5e4e303776f.png)

**Comment by ophub** [comment]
This is a bug in the upstream OpenWrt source code
https://github.com/coolsnowwolf/lede

**Comment by ophub** [comment]
已经添加了检出版本检查更新
