### ISSUE TITLE
T95z plus can not initialize PHY ethernet

### ISSUE THREAD

**Issue by Richard-Chueng** [ophub/amlogic-s9xxx-openwrt#231]
Hi,
1) No problem to boot the usb with latest firmware (openwrt_s912_k5.15.30_2022.03.20.2154.img.gz), but after install to emmc, it shows success, but can not initialize the ethernet after reboot.
2) I also try to reinstall the android firmware before install openwrt, but the problem is the same
![IMG_20220321_104601](https://user-images.githubusercontent.com/101122412/159200194-964e80b1-020a-4695-b1e0-1878edfd92ba.jpg)
.

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-openwrt/commit/b099d1a8a4f313b799ebb8eadeafcd569b0c67a2
I have removed support for T95 devices, the current firmware is not suitable for T95 use

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/releases

Find the firmware named `Armbian_22.05.0_Aml_s912-t95z_focal_5.15.30_xxx.img.gz` here, and see if Armbian can be used normally on T95. If so, OpenWrt can be modified with the above method.

**Comment by Richard-Chueng** [comment]
Hi,

I did try to install armbian firmware named Armbian_22.05.0_Aml_s912-t95z_focal_5.15.30_xxx.img.gz as you suggest above,
1) when booting with USB, it fails to raise the network interfaces;
![IMG_20220321_163609](https://user-images.githubusercontent.com/101122412/159229669-12aa3211-bc29-4257-b3a8-b714e7acf5ac.jpg)

**Comment by Richard-Chueng** [comment]
2) after some minutes, it can boot from usb, and also can not boot from emmc after successful installation.
![IMG_20220321_164804](https://user-images.githubusercontent.com/101122412/159229820-6dfdd780-8024-4932-a062-cbf01389a735.jpg)

**Comment by ophub** [comment]
You plug in the network cable, without the network cable, of course there is no network

**Comment by ophub** [comment]
Thank you for your feedback. It seems that this dtb is not applicable. I deleted T95 from the supported list and added it later when I have his compiled source code.

**Comment by Richard-Chueng** [comment]
Thanks for your reply, but i have writed image openwrt_s912-t95z_k5.15.25_2022.02.26.2120.img.gz to usb disk, and boot from usb without any problem for almost a month.
PS: only booting from usb will work, always fails booting from EMMC.

**Comment by ophub** [comment]
The `meson-gxm-t95z-plus.dtb` of this firmware has no compiled source code. It is a fixed file shared by netizens. It may not be used in different versions of the kernel such as 5.4/5.10. After writing emmc, the network card cannot be driven. I removed it first and added it later when I found the dts.

**Comment by puccio823** [comment]
hi last night i did some tests and finally it booted with **meson-gxbb-p200.dtb** file
![IMG20221117233738](https://user-images.githubusercontent.com/118255617/202704836-ac83a7d7-4a76-424c-992b-62e7a562c804.jpg)
but now I have this problem
![IMG20221118004308](https://user-images.githubusercontent.com/118255617/202705149-0ccab816-d27c-4963-afa9-b6af66260704.jpg)
