### ISSUE TITLE
下载的固件不支持ipv6

### ISSUE THREAD

**Issue by sharljimhtsin** [ophub/amlogic-s9xxx-openwrt#238]
刷了之后，配置dhcpv6，luci web不显示wan6，查看了luci的代码，发现有判断ip6tables 存在的逻辑，系统默认没有自带。

之后 curl -6 测试了也不通。是编译的时候没启用ipv6吗？

**Comment by sharljimhtsin** [comment]
还有个小问题就是 lsmod 没有任何输出，也很怪

**Comment by ophub** [comment]
实测支持IPV6的网站很少，开启会导致很多异常现象，所以删除了。你如果需要可以自己添加相关选项。
