### ISSUE TITLE
s905x mxq pro plus 无法进入系统安装

### ISSUE THREAD

**Issue by lppsuixn** [ophub/amlogic-s9xxx-openwrt#240]
我有一台 mxq pro plus的盒子，s905x 的cpu，2g+16g配置。刷了s905x的包无法进入安装界面，直接到盒子系统。
但是刷emuelec系统替换dtb后，以及 https://pulpstone.pw/openwrt-18-06-2/ 这里的s905x openwrt都可以正常安装。
所有想了解下有debug的方法吗？该如何定位问题，谢谢~

**Comment by ophub** [comment]
MXQ Pro是s905，不是s905x，这个盒子不支持写入emmc，写入必砖

**Comment by lppsuixn** [comment]
这个机器有很多版本。我的是这个
https://www.geekbuying.com/item/MXQ-PRO--Android-7-1-1-Amlogic-S905X-4K-TV-BOX-2GB-16GB-385604-385604.html

**Comment by ophub** [comment]
如果确定是s905x，设备刷过emuelec系统的话必须先刷会原安卓TV系统，才可以从USB启动。

**Comment by lppsuixn** [comment]
emuelec 和 pulpstone openwrt 都是在u盘启动的。emmc内电视系统没有动过。
我也测试了F大的n1的系统，然后改成p212的dtb，也是启动不了。
有其他需要改的吗？比如u-boot之类的需要调吗？
谢谢。

**Comment by ophub** [comment]
5.4内核的固件不需要u-boot，只有5.10以后的才需要。所以只要/boot/uEnv.txt里的dtb的文件名称正确即可。你可以测试下其他dtb，你以前在emuelec 和 pulpstone openwrt里使用的是哪个dtb，看下他的名称。
https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/build-armbian/common-files/patches/amlogic-dtb
在这里找下可以使用的，更改/boot/uEnv.txt里的dtb的名称测试。

**Comment by lppsuixn** [comment]
好的，我再测试下。感谢

**Comment by lppsuixn** [comment]
<img width="1262" alt="屏幕快照 2022-04-08 下午7 37 37" src="https://user-images.githubusercontent.com/12748339/162428399-bec061ac-2a82-4249-ad2a-a66bce438746.png">
目前看到emuelec 和 pulpstone 里命名一致，都是gxl_p212_xxx.dtb 大小基本一致
奇怪的是 pulpstone里没有指定dtb地址
<img width="1425" alt="屏幕快照 2022-04-08 下午7 40 39" src="https://user-images.githubusercontent.com/12748339/162428791-d3db43f5-fb4a-45b1-8760-d760afcb9121.png">

目录截图
<img width="923" alt="屏幕快照 2022-04-08 下午7 40 54" src="https://user-images.githubusercontent.com/12748339/162428806-174ede0c-b7a1-4e31-92d5-367083b4f73a.png">

**Comment by ophub** [comment]
uEnv.ini用文本打开
