### ISSUE TITLE
大神，我把打包脚本弄到本地ubuntu出现以下错误，有影响吗？

### ISSUE THREAD

**Issue by 281677160** [ophub/amlogic-s9xxx-openwrt#248]
![QQ截图20220425174409](https://user-images.githubusercontent.com/66651997/165064471-0a2081eb-082b-4220-a0ab-76f1d87f9608.png)

**Comment by ophub** [comment]
这太影响了，打包完了完全不能用。
你的本地文件不安整。踩高跷

**Comment by 281677160** [comment]
呃，好久没搞了，以前你没改版的时候就是这样没问题的，最近你的脚本好像改的挺多的，哈哈




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ophub/amlogic-s9xxx-openwrt"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月25日(星期一) 晚上6:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ophub/amlogic-s9xxx-openwrt] 大神，我把打包脚本弄到本地ubuntu出现以下错误，有影响吗？ (Issue #248)





 
这太影响了，打包完了完全不能用。
 你的本地文件不安整。踩高跷

**Comment by 281677160** [comment]
没改版的时候本地打包没问题

**Comment by ophub** [comment]
很多文件在另一个armbian库里，要从那个仓库下载

**Comment by 281677160** [comment]
就是把这两个，覆盖到这个仓库的同名文件
![QQ截图20220425182914](https://user-images.githubusercontent.com/66651997/165071984-d629e8f0-263a-4c7d-b6d4-857cd46fd0d9.png)
吗

**Comment by 281677160** [comment]
感谢大佬，我把你https://github.com/ophub/amlogic-s9xxx-armbian这个仓库的build-armbian里面的所有文件丢一个文件夹，然后把[compile-kernel]文件下载下来也丢进去，最后把https://github.com/ophub/amlogic-s9xxx-openwrt这个仓库的compile-kernel文件覆盖过去，打包好像没问题了，就是不知道对
![QQ截图20220425185837](https://user-images.githubusercontent.com/66651997/165076716-a2a478d3-da1f-4d44-ab8d-ebeea959c5e1.png)
不对

**Comment by ophub** [comment]
你图上的下载说明可以正常从github下载文件了。所以不用复制了，打包脚本会自动处理好。
没报错就可以用了
