### ISSUE TITLE
error 403

### ISSUE THREAD

**Issue by elsangithub** [ophub/amlogic-s9xxx-openwrt#251]
Run ncipollo/release-action@v1
Error: Error 403: Resource not accessible by integration

**Comment by ophub** [comment]
https://github.com/ncipollo/release-action

It can be accessed normally, you can try again

**Comment by elsangithub** [comment]
still the same

Run ncipollo/release-action@v1
Error: Error 403: Resource not accessible by integration

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-openwrt/actions/runs/2286380871

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-openwrt/tree/main/router-config#2-set-the-privacy-variable-github_token

**Comment by elsangithub** [comment]
I've done it several times in the same way but it's the same.. 1 month ago everything was very smooth.  but now the file can't be release.  I also tried it with a different account but it's the same.
