### ISSUE TITLE
Error: Error 403: Resource not accessible by integration

### ISSUE THREAD

**Issue by nikoharo** [ophub/amlogic-s9xxx-openwrt#252]
我尝试编译很多次了，好像是没赋予fork写入权
![1](https://user-images.githubusercontent.com/96216203/167336707-7222d104-5539-4670-a625-f4175f595ab6.png)
![2](https://user-images.githubusercontent.com/96216203/167336709-7a74c02c-80fb-4256-8aad-5d01203bbb5a.png)
![3](https://user-images.githubusercontent.com/96216203/167342851-cb2a9dbd-8f7d-4dba-a073-73ed643524d9.png)
![4](https://user-images.githubusercontent.com/96216203/167342858-a740f304-3f63-4a12-b9d3-35a401c41224.png)
![5](https://user-images.githubusercontent.com/96216203/167342859-ee9a710a-d6ea-4f41-bbf2-5027b4943252.png)

**Comment by elsangithub** [comment]
I also found the same thing

**Comment by ophub** [comment]
以前没发现有权限问题，你知道怎么赋权？

**Comment by ophub** [comment]
I read the instructions, token is not required, this parameter has been removed, I tested it and it can be used. You sync the source code and try again

**Comment by nikoharo** [comment]
> 以前没发现有权限问题，你知道怎么赋权？ https://github.com/ophub/amlogic-s9xxx-openwrt/blob/main/router-config/README.cn.md#2-%E8%AE%BE%E7%BD%AE
%E9%9A%90%E7%A7%81%E5%8F%98%E9%87%8F-github_token
> 
> 你给自己的仓库有赋予token权限了没

![6](https://user-images.githubusercontent.com/96216203/167371392-fd1cee08-67c7-41a9-aa68-0c296bf843d0.png)
![7](https://user-images.githubusercontent.com/96216203/167371559-ff1a9c26-4f8c-4e35-b9b7-a1490a77fcdb.png)

后面参考了这篇文章修改参数也还是不行

**Comment by ophub** [comment]
同步刚才的修改，我删除token了，测试可用

**Comment by nikoharo** [comment]
> 同步刚才的修改，我删除了token了，测试可用 https://github.com/ophub/amlogic-s9xxx-openwrt/actions/runs/2292952862

ok,我试试

**Comment by kousyougi** [comment]
刚发现最近新fork的repositories预设没有写入Release的权限。很久以前fork预设开放写入权限。
到下面设定一下就不会跳出错误了。

![Github_Permissions](https://user-images.githubusercontent.com/43228565/167576504-8cfbd813-7e77-405b-a93d-80e12a1675bb.png)

**Comment by ophub** [comment]
https://github.com/alex-page/github-project-automation-plus/issues/39
我在这个帖子里找到了解决方案，说要创建的密钥命名是：GH_TOKEN，我测试了有效。
这个问题从昨天发现，我测试了一晚上，各种Actions权限修改也没解决，就在你发帖前我刚刚测试成功。你试试我的这种做法。
![Snip20220510_3](https://user-images.githubusercontent.com/68696949/167583100-9d9a13eb-d767-4810-9717-aa1dd02ff8d7.png)

**Comment by elsangithub** [comment]
OK.. i try

**Comment by elsangithub** [comment]
success, thank you everyone
