### ISSUE TITLE
在Github Actions里保存不了文件。

### ISSUE THREAD

**Issue by nikoharo** [ophub/amlogic-s9xxx-openwrt#253]
我试过了另外一个openwrt在线编译，同样也是无法在GitHub Releases保存，但可以在Github Actions保存，于是我修改了在.github/workflows/build-openwrt-official-21.02.yml文件，最后是成功了，但没有输出编译好的文件，
  我最后参考了https://github.com/P3TERX/Actions-OpenWrt这个项目，我成功编译并上传到了Github Actions上，于是我参考了他的build-openwrt.yml文件并选取了Upload firmware directory这部分代码修改了build-openwrt-official-21.02.yml文件，到了最后也还是没有输出文件
![1](https://user-images.githubusercontent.com/96216203/167632131-f3cef404-1f82-425b-9835-fb2812a7e82e.png)
![2](https://user-images.githubusercontent.com/96216203/167632136-e37bcedf-93a3-4e7d-9429-a1114b95d0f3.png)
![3](https://user-images.githubusercontent.com/96216203/167632141-fe09caae-4eff-4493-a1c5-f55a9f5910f8.png)
![4](https://user-images.githubusercontent.com/96216203/167632142-e5de40d6-65a8-4706-9637-675c56b4412c.png)
![5](https://user-images.githubusercontent.com/96216203/167632147-10c6cd9c-5241-49a7-a8a0-1e24bd173553.png)
![6](https://user-images.githubusercontent.com/96216203/167632480-3226e574-bca0-4513-8af3-775cda62a672.png)

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-openwrt/blob/main/router-config/README.cn.md#2-设置隐私变量-github_token

按照2-3设置下即可。
