### ISSUE TITLE
github库中找不到文件

### ISSUE THREAD

**Issue by EVEFans** [ophub/amlogic-s9xxx-openwrt#255]
在本地打包openwrt时，从github库中找不到文件
![image](https://user-images.githubusercontent.com/86581414/169630581-22e02f83-5aeb-4fc0-bf8d-c2835c2f8194.png)

**Comment by EVEFans** [comment]
> 在本地打包openwrt时，从github库中找不到文件 ![image](https://user-images.githubusercontent.com/86581414/169630581-22e02f83-5aeb-4fc0-bf8d-c2835c2f8194.png)

多次执行后OK

**Comment by ophub** [comment]
你执行的make命令是什么？你查询的2个内核都是老版本的已经删除的内核，不要指定`-a`就使用最新版，或者`-a true`自动使用最新
`sudo ./make -d -a true`
