### ISSUE TITLE
Unable to build the latest kernel files

### ISSUE THREAD

**Issue by dinhchinh82** [ophub/amlogic-s9xxx-openwrt#258]
I've just forked the latest kernel and built via Github action but got the error 
<img width="1109" alt="image" src="https://user-images.githubusercontent.com/22479095/169729042-0abc71e1-91be-405b-969f-913ceb90e7c2.png">

https://github.com/dinhchinh82/amlogic-s9xxx-openwrt/runs/6544603098?check_suite_focus=true

@ophub could you give me the suggestion to fix?

Thank you.

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-openwrt/tree/main/router-config#2-set-the-privacy-variable-github_token


2. Set the privacy variable GitHub_TOKEN
3. Fork repository and set GH_TOKEN

github.com has modified the default `fork` settings, you need to refer to the instructions and assign these permissions to `Actions` before you can use them

**Comment by dinhchinh82** [comment]
> github.com has modified the default `fork` settings, you need to refer to the instructions and assign these permissions to `Actions` before you can use them

Yes. I just found this reason. Thank you for your help.
