### ISSUE TITLE
X96 mini 1GB/8GB

### ISSUE THREAD

**Issue by Hayo-Tee** [ophub/amlogic-s9xxx-openwrt#259]
I have X96 mini. I wan to to use Openwrt. Can I use additional OpenWRT official packages or I need to build it myself? And can I use docker containers? I can i connect Huawei E8372 and set up Wi-Fi AP?

**Comment by ophub** [comment]
The X96 mini does not support wireless. Firmware must be made by yourself. You can use docker, please refer to the relevant information for specific usage
