### ISSUE TITLE
A95X Wireless Support

### ISSUE THREAD

**Issue by kodokskoprol** [ophub/amlogic-s9xxx-openwrt#260]
I have device branded as A95X, it has the same form factor and specification as Nexbox A1
How to enable wireless function?

the wireless module is Fn-Link 8223A-SR C07001 1727

Nexbox A1
**https://www.gearbest.com/tv-box-mini-pc/pp_424843.html**

A95X
**https://tokopedia.link/zQVlmUfgqqb**
![IMG_20220529_153502](https://user-images.githubusercontent.com/39587782/170859803-17dfff62-9bd0-4fa2-82a5-c0ef2a97405c.jpg)
![IMG_20220529_153715](https://user-images.githubusercontent.com/39587782/170859807-f5fda040-3d6c-4065-94c8-b19c8a7a4206.jpg)

**Comment by ophub** [comment]
I consulted flippy, this is the `qca9377` chip, it is recommended to try the `ath10k driver.` I newly added this driver today, you download today's firmware and try

**Comment by kodokskoprol** [comment]
tried all s912 lastest firmware, wireless still not showing

![bro](https://user-images.githubusercontent.com/39587782/170873537-b56d5c12-fd48-4ae8-be68-9370749347a4.PNG)

**Comment by ophub** [comment]
[meson-gxm-a95x.dtb.zip](https://github.com/ophub/amlogic-s9xxx-openwrt/files/8795710/meson-gxm-a95x.dtb.zip)

Download and decompress the meson-gxm-a95x.dtb file and upload it to the /boot/dtb/amlogic directory. Modify the name of the dtb file in `/boot/uEnv.txt` to `meson-gxm-a95x.dtb`, restart after the modification, try whether the wireless can be used, and report the result.

**Comment by kodokskoprol** [comment]
lastest firmware & a95x dtb unfortunately still not working
![ophub](https://user-images.githubusercontent.com/39587782/170942367-dca701b9-2e12-4cf7-96e1-e2bb8e56778f.PNG)

**Comment by ophub** [comment]
![image](https://user-images.githubusercontent.com/68696949/170944185-f4123e59-9ae6-4605-9430-ddaa7a26a5af.png)

![image](https://user-images.githubusercontent.com/68696949/170944247-faff6430-92af-4d25-a7c6-5d13ee0d8ec6.png)

![image](https://user-images.githubusercontent.com/68696949/170944289-1f8e52b4-d22a-4228-90da-01b9afc6a5e2.png)

GPIOX_17 corresponds to a pin on the cpu and needs to be measured with a multimeter, or you can find the official design schematic of this motherboard

[meson-gxm-a95x.dts.zip](https://github.com/ophub/amlogic-s9xxx-openwrt/files/8796574/meson-gxm-a95x.dts.zip)

This is the source file of the dtb added for your device.


```
&uart_A {
		status = "okay";
		pinctrl-0 = <&uart_a_pins>, <&uart_a_cts_rts_pins>;
		pinctrl-names = "default";
		uart-has-rtscts;

		bluetooth {
				compatible = "qcom,qca9377-bt";
				shutdown-gpios = <&gpio GPIOX_17 GPIO_ACTIVE_HIGH>;
				max-speed = <2000000>;
				clocks = <&wifi32k>;
				clock-names = "lpo";
		};
};
```

The value of `GPIOX_17` needs to determine what your pin is.

**Comment by ophub** [comment]
Is the wired network available? Is the network port of this device Gigabit or 100M?

**Comment by kodokskoprol** [comment]
the wired ethernet is gigabit and working

**Comment by kodokskoprol** [comment]
i have multitester, but i didn't know how to measure the GPIO

**Comment by ophub** [comment]
Need to remove the cpu, it is more troublesome, stop measuring, use the wired network

**Comment by kodokskoprol** [comment]
Flippy kernel does not have `u-boot.ext`.

Ophub kernel using `u-boot.ext`. file that work with this kernel is
`u-boot-p201.bin`
`u-boot-p212.bin`
`u-boot-s905.bin`
i have to manually rename those file into `u-boot.ext` , because `u-boot.ext` that came with firmware didn't work

but both kernel showing same result in the terminal
![ophub k](https://user-images.githubusercontent.com/39587782/171330501-3418b517-1e5f-4fbf-9e0d-d7e4959c8c74.PNG)
![flippy](https://user-images.githubusercontent.com/39587782/171330545-8f846c3f-3da1-4572-adcd-a3e4682388f2.PNG)

**Comment by ophub** [comment]
`u-boot-p212.bin`
This can be used normally under the 5.10 and 5.15 kernels? Then make sure it is this.

**Comment by ophub** [comment]
https://github.com/unifreq/linux-5.10.y/blob/efde4bfba2724ae4c2e2afdbb53813f45f4c8829/arch/arm64/boot/dts/amlogic/meson-gxl-s905d-sml5442tw.dts#L74

I found one in the dtb directory that uses the same chip as your qca9377, and its pin is also GPIOX_17. This value is also the setting in the file I sent you before.

Where can I find the correct value for this.

**Comment by ophub** [comment]
[meson-gxm-a95x-a.dtb.zip](https://github.com/ophub/amlogic-s9xxx-openwrt/files/8812129/meson-gxm-a95x-a.dtb.zip)
[meson-gxm-a95x-b.dtb.zip](https://github.com/ophub/amlogic-s9xxx-openwrt/files/8812130/meson-gxm-a95x-b.dtb.zip)

Can you try these 2 dtbs to use wireless again?
Upload to the `/boot/dtb/amlogic` directory
Then `vi /boot/uEnv.txt` modify the dtb name inside

**Comment by kodokskoprol** [comment]
tested the dtb unfortunately not working

**Comment by danboid** [comment]
Those dtbs don't boot at all on my X96 Air Q1000 and my X96 Max+ 64 GB.

**Comment by danboid** [comment]
The latest Manjaro linux-aml kernel package is at 5.13. Wifi works with 5.13 but it has HDMI issues. I would recommend any X96 users using Manjaro use my 5.12 kernel packages instead because they have working HDMI

https://github.com/danboid/meson-sm1-sei610-qca9377-bt/releases/tag/kernel

**Comment by danboid** [comment]
@ophub 

I'm sorry, I gave you the old manjaro ARM amlogic kernel repo address earlier. The current one is:

https://gitlab.manjaro.org/manjaro-arm/packages/core/linux-odroid

I have tested Manjaros 5.17 odroid kernel on my X96 Max+ 64 GB and my X96 Air with their meson-g12a-x96-max.dtb and the both onboard wifi and ethernet works.

**Comment by ophub** [comment]
@danboid 
What is the name of your device? soc? NIC chip?

**Comment by ophub** [comment]
In the address you sent, no modification was found for meson-g12a-x96-max.dtb or related include files. Do you know which patch he used?

**Comment by danboid** [comment]
s905x3.

What about the kernel network config options? Are they identical? I'll try and have a look later but I'm busy most of the day today.

**Comment by danboid** [comment]
@ophub 

If you send me your address I'll send you my spare X96 Air Q1000. I'd like to see s9xxx Armbian have working wifi and bluetooth for these boxes.

**Comment by ophub** [comment]
This is the default setting for the mainline kernel：

https://github.com/unifreq/linux-5.15.y/blob/main/arch/arm64/boot/dts/amlogic/meson-g12a-x96-max.dts

Know which value to change, create a new dtb like this. Just modify those few lines：

https://github.com/unifreq/linux-5.15.y/blob/main/arch/arm64/boot/dts/amlogic/meson-g12a-x96-max-rmii.dts

I can't find it in the URL you posted today. You can look for it. Or decompile the dtb you can use, and compare it with the mainline to see what has been adjusted.
