### ISSUE TITLE
[Enchantment] build selector

### ISSUE THREAD

**Issue by rapdodge** [ophub/amlogic-s9xxx-openwrt#265]
Dear ophub, can you make build selector when we want to build openwrt?

I mean, we can choose SNAPSHOT or latest stable by openwrt. Because when i want to installed another packages after running it, it says kernel is not compatible

![image](https://user-images.githubusercontent.com/33513626/173258975-1a47bfe8-984e-46eb-b0be-f7b8ccba6f6b.png)

My router
![image](https://user-images.githubusercontent.com/33513626/173259413-9913a397-800b-4bb4-99c4-f4f0a6798f95.png)

STB OpenWrt
![image](https://user-images.githubusercontent.com/33513626/173259452-6a45bba9-280b-49e3-aff6-8d8f543e96bb.png)

Thanks

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-openwrt/tree/main/router-config

Different branches of different source codes have different configuration files. Here are the configuration files of the two official versions. Other branches can be created and compiled in this way.

**Comment by rapdodge** [comment]
if i'm not forget last night i try to change to openwrt-21.02
and its still SNAPSHOT

and i destroyed the repo and reforking again...

**Comment by ophub** [comment]
https://github.com/0118Add/amlogic-s9xxx-openwrt/tree/main/router-config

I checked the fork list, there is also the previous configuration of openwrt-21.02 in this repository, you can make a copy. When compiling natively every time a fresh compile. Or use github's actions to compile and avoid caching.

**Comment by rapdodge** [comment]
Will take a look into it

**Comment by rapdodge** [comment]
Update... Its still SNAPSHOT, and, other packages that i want to install keep says not compatible...
So, i think i should rebuilding it every i want to get some packages 😅

![image](https://user-images.githubusercontent.com/33513626/173288729-b7caa946-a79f-4b69-a68d-b4d9ba387b80.png)

Thanks for your hardwork!

**Comment by rapdodge** [comment]
Btw @ophub, can you tell me how to generate router-config/.config file?

Is there any tools or something like that to generate that file?

**Comment by ophub** [comment]
https://github.com/openwrt/openwrt#quickstart

Run `make menuconfig` to select your preferred configuration for the toolchain, target system & firmware packages. `save` and generate `.config`
