### ISSUE TITLE
Pirania

### ISSUE THREAD

**Issue by adisubagja** [ophub/amlogic-s9xxx-openwrt#27]
Can add this to openwrt sir?

https://github.com/libremesh/pirania

https://github.com/libremesh/lime-packages/tree/master/packages/pirania-app
https://github.com/libremesh/lime-packages/tree/master/packages/pirania

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-openwrt/blob/main/router_config/diy-part2.sh

fork repository.
On lines 27 and 28, delete the # at the beginning of the line, like this:

```
git clone https://github.com/libremesh/lime-packages.git package/lime-packages
sed -i "/DEFAULT_PACKAGES/ s/$/ pirania-app pirania ip6tables-mod-nat ipset/" target/linux/armvirt/Makefile
```
Build your personalized plug-in. More usage methods can be found in this document:
https://github.com/ophub/amlogic-s9xxx-openwrt/blob/main/router_config/Documentation.md

**Comment by adisubagja** [comment]
Like this ? https://github.com/adisubagja/amlogic-s9xxx-openwrt/blob/main/router_config/diy-part2.sh#L27

iam using b860h this no problem for target armvirt?

**Comment by ophub** [comment]
yes

**Comment by adisubagja** [comment]
Thanks i'll try

**Comment by adisubagja** [comment]
Im done build with this, but now how to check pirania is installed bro?

**Comment by ophub** [comment]
E.g:

cat /etc/config/pirania

Check whether the file of this software exists, and find the relevant location according to the official instructions.

https://github.com/libremesh/lime-packages/tree/master/packages/pirania

```
view files:
    /etc/config/pirania is the UCI config
    /etc/pirania/db.csv (default path) contains the database of vouchers

    /etc/init.d/pirania-uhttpd starts a uhttpd on port 59080 that replies any request with a redirect towards a preset URL

    /usr/lib/lua/voucher/ contains lua libraries used by /usr/bin/voucher
    /usr/bin/voucher is a CLI to manage the db (has functions add_voucher, add_many_vouchers, auth_voucher, get_valid_macs, list_vouchers, remove_voucher and url)
    /usr/bin/captive-portal sets up iptables rules to capture traffic

    /usr/libexec/rpcd/pirania ubus pirania API (this is used by the web frontend)
    /usr/share/rpcd/acl.d/pirania.json ACL for the ubus pirania API
```

**Comment by ophub** [comment]
In addition to the entire repository integration, you can also choose the required package integration:
```
svn co https://github.com/libremesh/lime-packages/trunk/packages/{shared-state-pirania,pirania-app,pirania} package/lime-packages/packages
sed -i "/DEFAULT_PACKAGES/ s/$/ pirania-app pirania ip6tables-mod-nat ipset shared-state-pirania uhttpd-mod-lua/" target/linux/armvirt/Makefile
```

My two lines of code are how openwrt adds third-party plug-in sources and compiles them.

I use `SSH connection to Actions` to check that these two packages have been selected, so the addition method is effective.

![](https://user-images.githubusercontent.com/68696949/111093472-fef2f280-8573-11eb-8e79-8ba16b55e951.png)

I did not find their integrated compilation instructions on this plugin website, you can ask them how to compile/install/use them.

**Comment by adisubagja** [comment]
Yes im installing my fw build but not showing this file :(
I don't know what else to do
If I find any more ideas I will tell again

Thank you for the help
