### ISSUE TITLE
Can't install openwrt in EMMC

### ISSUE THREAD

**Issue by Roxy09099** [ophub/amlogic-s9xxx-openwrt#271]
My devices: my device: X92, 3GB ram, 16gb rom, 1Gbps lan.
No emmc can be found to install the openwrt system
lan port got full 1000mbps everything is quite ok for me but i cant install it to EMMC memory whether kernel 5.4.y or 5.15.y

I need your help. if you have Telegram can you help me via chat? that would be more convenient on github. Think of this as a paid support service. i will pay for that.
My Telegram: https://t.me/kogoro6996
![image](https://user-images.githubusercontent.com/10328246/177003387-70e656aa-3bd4-4668-9b1e-f8968ebbcff6.png)

**Comment by ophub** [comment]
`lsblk`
see what your emmc is
What is the `soc` of your box, install it according to the configuration you use to boot into the usb.
First use the `5.15 kernel firmware` test.

This is free software, there are no paid services. You can check the relevant operating instructions.

**Comment by Roxy09099** [comment]
yes i used 5.15.15 firmware. my box is using soc s912

**Comment by Roxy09099** [comment]
https://github.com/ophub/amlogic-s9xxx-openwrt/issues/196
I have a reference from this similar device use case. i also flashed stock android 6 firmware before using usb with openwrt installer

**Comment by Roxy09099** [comment]
lsblk
![PXL_20220702_143611243](https://user-images.githubusercontent.com/10328246/177005151-7a2a809d-5fcb-4a4d-ad9b-7867c615a652.jpg)

**Comment by Roxy09099** [comment]
> `lsblk` see what your `emmc name` is What is the `soc` of your box, install it according to the configuration you use to boot into the usb. First use the `5.15 kernel firmware` test.
> 
> This is free software, there are no paid services. You can check the relevant operating instructions.
yes i used 5.15.15 firmware. my box is using soc s912
emmc name: mmcblk2

**Comment by Roxy09099** [comment]
> `lsblk` see what your `emmc name` is What is the `soc` of your box, install it according to the configuration you use to boot into the usb. First use the `5.15 kernel firmware` test.
> 
> This is free software, there are no paid services. You can check the relevant operating instructions.


yes i used 5.15.15 firmware. my box is using soc s912
Emmc name: mmcblk2

**Comment by ophub** [comment]
![Snip20220703_1](https://user-images.githubusercontent.com/68696949/177024009-1a4b101f-4c4e-4d2a-ae36-6b2ef4d938ba.png)

The general emmc has the `mmcblk?boot0` partition, which is used to judge the name of the emmc in the script

https://github.com/ophub/luci-app-amlogic/blob/6113be1b39a63863531df3b478cd0049f8a00058/luci-app-amlogic/root/usr/sbin/openwrt-install-amlogic#L69

https://github.com/ophub/luci-app-amlogic/blob/6113be1b39a63863531df3b478cd0049f8a00058/luci-app-amlogic/root/usr/sbin/openwrt-update-amlogic#L45

**Comment by Roxy09099** [comment]
> ![Snip20220703_1](https://user-images.githubusercontent.com/68696949/177024009-1a4b101f-4c4e-4d2a-ae36-6b2ef4d938ba.png)
> 
> The general emmc has the `mmcblk?boot0` partition, which is used to judge the name of the emmc in the script
> 
> https://github.com/ophub/luci-app-amlogic/blob/6113be1b39a63863531df3b478cd0049f8a00058/luci-app-amlogic/root/usr/sbin/openwrt-install-amlogic#L69
> 
> ```
> # local: /usr/sbin/openwrt-install-amlogic
> # line 69, change into:
> install_emmc="$(lsblk -l -o NAME | grep -oE '(mmcblk[0-9])' | sed "s/boot0//g")"
> ```
> 
> https://github.com/ophub/luci-app-amlogic/blob/6113be1b39a63863531df3b478cd0049f8a00058/luci-app-amlogic/root/usr/sbin/openwrt-update-amlogic#L45
> 
> ```
> # loacal: /uar/sbin/openwrt-update-amlogic
> # line 45, change into:
> if lsblk -l -o NAME | grep "${EMMC_NAME}" >/dev/null; then
> ```
> 
> If you know the rescue plan of the device and have the corresponding Android TV system firmware, for example, if you try to write emmc, you can delete `?boot0` and test it


I don't know how to compile it myself.is there any other way than to compile a new ipk? or can you help me compile?

**Comment by ophub** [comment]
No need to compile, you change the line in these two files, it says

**Comment by Roxy09099** [comment]
> No need to compile, you change the line in these two files, it says
> 
> Download to the local modification, and then overwrite with the same path. Or use vi command to modify online
> 
> ssh: `vi /usr/sbin/openwrt-install-amlogic`


Ok i will try.
let me ask more, here is the code on the wifi chip of the x92 tv box that i have: AP6255 T111102D 1707. can add wifi driver for it?.
![PXL_20220703_044715956~3](https://user-images.githubusercontent.com/10328246/177025161-28d8e87b-bf33-4ae8-b068-bf75818a829e.jpg)

**Comment by Roxy09099** [comment]
> vi /usr/sbin/openwrt-install-amlogic



> No need to compile, you change the line in these two files, it says
> 
> Download to the local modification, and then overwrite with the same path. Or use vi command to modify online
> 
> ssh: `vi /usr/sbin/openwrt-install-amlogic`

deleted ?boot but it says I'm in emmc mode

![image](https://user-images.githubusercontent.com/10328246/177025910-810b3fb6-dde5-496e-b7c0-af8e9451c8a7.png)

![image](https://user-images.githubusercontent.com/10328246/177025943-262d66e9-01ee-4cca-a4b3-3640771923bc.png)

**Comment by ophub** [comment]
```
df / | tail -n1
lsblk -l
```

**Comment by Roxy09099** [comment]
> ```
> # view dtb
> cat /etc/flippy-openwrt-release
> 
> 
> # for wifi deiver:
> dmesg | grep -i sdio
> ls /lib/firmware/brcm/brcmfmac43455-sdio*
> cat /lib/firmware/brcm/brcmfmac43455-sdio.txt
> 
> 
> # foe install to emmc
> df / | tail -n1
> lsblk -l
> ```
> 
> ![Snip20220703_2](https://user-images.githubusercontent.com/68696949/177036377-312e9c5b-e719-4898-b45f-ff817a43e62f.png)



> ```
> # view dtb
> cat /etc/flippy-openwrt-release
> 
> 
> # for wifi deiver:
> dmesg | grep -i sdio
> ls /lib/firmware/brcm/brcmfmac43455-sdio*
> cat /lib/firmware/brcm/brcmfmac43455-sdio.txt
> 
> 
> # foe install to emmc
> df / | tail -n1
> lsblk -l
> ```
> 
> ![Snip20220703_2](https://user-images.githubusercontent.com/68696949/177036377-312e9c5b-e719-4898-b45f-ff817a43e62f.png)

thank you i will try. I need to add 2 lines of code:
df / | tail -n1
lsblk -l
enter before exit 1 (marked with a red # by you) or replace the line exit 1?

**Comment by ophub** [comment]
The red # is for you to add # in this position. to continue with the installation.

The others are for you to execute it, take screenshots of the execution results one by one, and I will look at your system information

**Comment by Roxy09099** [comment]
> ```
> # view dtb
> cat /etc/flippy-openwrt-release
> 
> 
> # for wifi deiver:
> dmesg | grep -i sdio
> ls /lib/firmware/brcm/brcmfmac43455-sdio*
> cat /lib/firmware/brcm/brcmfmac43455-sdio.txt
> 
> 
> # foe install to emmc
> df / | tail -n1
> lsblk -l
> ```
> 
> ![Snip20220703_2](https://user-images.githubusercontent.com/68696949/177036377-312e9c5b-e719-4898-b45f-ff817a43e62f.png)

* view dtb
![image](https://user-images.githubusercontent.com/10328246/177052046-0d30fdb3-171c-4a84-b217-f9986a62b5e6.png)

*for wifi driver:
dmesg | grep -i sdio
ls /lib/firmware/brcm/brcmfmac43455-sdio*
![image](https://user-images.githubusercontent.com/10328246/177052071-ade05f6c-5312-47a6-b9de-88bb0f3eb3cb.png)

cat /lib/firmware/brcm/brcmfmac43455-sdio.txt
![image](https://user-images.githubusercontent.com/10328246/177052108-43982d6b-31ac-4bb2-907c-6f4f988c9a92.png)
![image](https://user-images.githubusercontent.com/10328246/177052127-3999bd9d-eca6-4470-898d-4778e44d19aa.png)

**Comment by ophub** [comment]
![image](https://user-images.githubusercontent.com/68696949/177062563-d4e782bb-019a-43d2-90e9-4ea7d4dd69da.png)

![image](https://user-images.githubusercontent.com/68696949/177062575-5c2e3af0-2927-4070-b92a-657bcbe31aca.png)

What's the difference between you

**Comment by Roxy09099** [comment]
> ![image](https://user-images.githubusercontent.com/68696949/177062563-d4e782bb-019a-43d2-90e9-4ea7d4dd69da.png)
> 
> ![image](https://user-images.githubusercontent.com/68696949/177062575-5c2e3af0-2927-4070-b92a-657bcbe31aca.png)
> 
> [#271 (comment)](https://github.com/ophub/amlogic-s9xxx-openwrt/issues/271#issuecomment-1173066971)
> 
> What's the difference between you

before adding the following 2 lines: df / |  tail -n1
 lsblk -l it says I'm in emmc mode, but after adding those 2 lines it shows a Zram line like the picture.  you can review the screenshot
Before:
![177025910-810b3fb6-dde5-496e-b7c0-af8e9451c8a7](https://user-images.githubusercontent.com/10328246/177063631-94d61604-6080-40ce-a94a-b5c2998266c6.png)

After:
![177056171-1ce52628-bebb-42ca-b53f-c3b6b6ef0499](https://user-images.githubusercontent.com/10328246/177063652-f5d95d93-f858-433f-bf86-3a67452d2164.png)

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-openwrt/issues/271#issuecomment-1173066971

**Comment by ophub** [comment]
The dtb you filled in tx9 is usb tested and can be used? What dtb are you using now?

**Comment by Roxy09099** [comment]
> The dtb you filled in tx9 is usb tested and can be used? What dtb are you using now?
> 
> `cat /boot/uEnv.txt`

i am using tx9 pro dtb file because it has wifi driver

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-openwrt/blob/6aa4a18553dc153ce0ac8516d401e79761298e53/amlogic-s9xxx/common-files/rootfs/etc/model_database.txt#L20

There are options for tx9 in the drop-down menu, you can directly select

**Comment by Roxy09099** [comment]
> https://github.com/ophub/amlogic-s9xxx-openwrt/blob/6aa4a18553dc153ce0ac8516d401e79761298e53/amlogic-s9xxx/common-files/rootfs/etc/model_database.txt#L20
> 
> There are options for tx9 in the drop-down menu, you can directly select

still not
![image](https://user-images.githubusercontent.com/10328246/177066617-f134c44d-44dc-4b05-9ca1-c013e7a90657.png)

**Comment by ophub** [comment]
The red # is for you to add # in this position. to continue with the installation.

![image](https://user-images.githubusercontent.com/68696949/177067832-bc62a39a-47a6-4187-9402-05fc1a3f63ac.png)

**Comment by Roxy09099** [comment]
> The red # is for you to add # in this position. to continue with the installation.
> 
> ![image](https://user-images.githubusercontent.com/68696949/177067832-bc62a39a-47a6-4187-9402-05fc1a3f63ac.png)

**Comment by Roxy09099** [comment]
> > The red # is for you to add # in this position. to continue with the installation.
> > ![image](https://user-images.githubusercontent.com/68696949/177067832-bc62a39a-47a6-4187-9402-05fc1a3f63ac.png)

I'm sorry I misunderstood you earlier.  i fixed it to # exit 1 and it seems to be working but am stuck at copy boot...

**Comment by ophub** [comment]
screenshot

**Comment by Roxy09099** [comment]
> screenshot

![image](https://user-images.githubusercontent.com/10328246/177068342-cff1a0b3-17d7-47ec-b57b-c60b3e5272f5.png)

**Comment by ophub** [comment]
Unplug the power, restart and try again

**Comment by Roxy09099** [comment]
> Unplug the power, restart and try again

still fdisk partition fails
![image](https://user-images.githubusercontent.com/10328246/177070590-972a5820-1320-45a1-ae79-54666c23bdaf.png)
![image](https://user-images.githubusercontent.com/10328246/177070618-cc56e2f8-2a42-4357-bab3-9c21db027ede.png)

**Comment by ophub** [comment]
The label name of the disk format is incorrect, and it seems that the script needs to be modified in several places.
You can restore the system of the box to Android system.
Do not write emmc, the same is used in USB/TF card.

**Comment by Roxy09099** [comment]
> The label name of the disk format is incorrect, and it seems that the script needs to be modified in several places. You can restore the system of the box to Android system. Do not write emmc, the same is used in USB/TF card.
> 
> https://github.com/ophub/amlogic-s9xxx-openwrt/tree/main/router-config#108-how-to-restore-the-original-android-tv-system

meson-gxm-q200.dtb and meson-gxm-q200-mod.dtb
What is the difference of these 2 dtb files?  after i changed the dtb file in uEnv.txt to meson-gxm-q200.dtb it was able to write openwrt to emmc.  but after unplugging usb and plugging in power again it doesn't start openwrt but starts android frimware.  how to fix?

**Comment by ophub** [comment]
Writing is independent of which dtb is selected.
Your device does not support writing to emmc with the current script. Use it on external devices such as USB/SD/TF.

**Comment by Roxy09099** [comment]
> Writing is independent of which dtb is selected. Your device does not support writing to emmc with the current script. Use it on external devices such as USB/SD/TF.
i need your help, I lost my wireless in openwrt. Kernel log:
[   20.179236] brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac43455-sdio for chip BCM4345/6
[   20.204411] brcmfmac mmc0:0001:1: Direct firmware load for brcm/brcmfmac43455-sdio.tanix,tx9-pro.txt failed with error -2
[   20.373717] brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac43455-sdio for chip BCM4345/6
[   20.436896] brcmfmac: brcmf_c_preinit_dcmds: Firmware: BCM4345/6 wl0: Aug 25 2015 18:58:57 version 7.45.69 (r581703) FWID 01-24037f6e

**Comment by ophub** [comment]
Is the firmware you are using now, and the one you used before, a download file?

**Comment by Roxy09099** [comment]
> Is the firmware you are using now, and the one you used before, a download file?

Yup

**Comment by ophub** [comment]
The last 2 lines of the log you posted above show that you have successfully driven.

**Comment by Roxy09099** [comment]
> The last 2 lines of the log you posted above show that you have successfully driven.
> 
> [ 20.373717] brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac43455-sdio for chip BCM4345/6 [ 20.436896] brcmfmac: brcmf_c_preinit_dcmds: Firmware: BCM4345/6 wl0: Aug 25 2015 18:58:57 version 7.45.69 (r581703) FWID 01-24037f6e

but my wireless card is gone.  wifi is not broken when using android it can still work normally.  I don't understand why it lost wireless so suddenly

**Comment by ophub** [comment]
`cat /etc/flippy-openwrt-release`
screenshot

**Comment by Roxy09099** [comment]
> `cat /etc/flippy-openwrt-release`
> 
> `cat /lib/firmware/brcm/brcmfmac43455-sdio.txt`
> 
> screenshot
> 
> Screenshot of the welcome interface information of `ssh` (the one with the `banner` logo)

@ophub wireless appeared again in the interface after i flashed fw android 7.0.  there is a problem with my x92 device that makes me want to install openwrt in EMMC, every time I start the device while it is off, I have to press the reset button, otherwise even if the usb is plugged in and i used to start openwrt with  usb before but if the next time I turn it on I don't combine the reset button (in the AV jack) it will boot into android instead of openwrt in usb (tried with fw stock Android 6.0 and 7.0)

**Comment by ophub** [comment]
The script does not support your device and writing cannot be used.
