### ISSUE TITLE
sqm qos

### ISSUE THREAD

**Issue by carlocensi813** [ophub/amlogic-s9xxx-openwrt#272]
Hello. Someone can tell me if there is a way to install SQM QOS on 5.15 kernel and how?

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/compile-kernel

**Comment by carlocensi813** [comment]
> https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/compile-kernel

Is there a way to add it to the release version? I'm pretty much a noob

**Comment by ophub** [comment]
Others don't need it, you compile it according to your own personalized needs

**Comment by carlocensi813** [comment]
I mean to add it myself once it's already compiled

**Comment by ophub** [comment]
You check the relevant documents, which option in the kernel is the function you need, modify the .config template and compile it to get your own kernel, and then use `armbian-update <your_kernel>` to install.

https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/compile-kernel

https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/compile-kernel/tools/config
