### ISSUE TITLE
bug.. reboot device

### ISSUE THREAD

**Issue by riyuejz** [ophub/amlogic-s9xxx-openwrt#28]
reboot the device works .. but the device won't turn back on .. I'm using the hg680p device .. with the latest openwrt firmware from here .. in the previous version with kernel 5.9.16 everything went well .. but after updating in kernel version 5.10.23 some features don't work ..

**Comment by ophub** [comment]
The 5.10 kernel mainline u-boot is still in the testing period. Currently only supports experience on TF card. It is recommended that you use other kernels other than 5.10.
