### ISSUE TITLE
02.02 Invalid firmware check. [[1;91m Error [0m] The /boot files is missing.

### ISSUE THREAD

**Issue by jinkun2014** [ophub/amlogic-s9xxx-openwrt#287]
![image](https://user-images.githubusercontent.com/11567175/185761056-7e10fcb4-7c16-4fd0-a66b-a790dfef1f70.png)

![image](https://user-images.githubusercontent.com/11567175/185761081-4c85b0b6-0afc-4854-980d-553cf1aee4e8.png)

手动升级内核失败

**Comment by ophub** [comment]
你的文件不完整，重新上传，或者在线下载更新

不要重启，/boot缺了文件，重启就挂了

**Comment by jinkun2014** [comment]
1、在线更新一直下载失败
![image](https://user-images.githubusercontent.com/11567175/185772817-9d9973cc-973e-4fa7-a8fc-6e45f5c12b26.png)

2、手动上传完整固件，每次上传一半就崩了，可能压缩包太大了

基本上无解了？

/boot缺了哪些文件？重新上传什么文件

**Comment by ophub** [comment]
可以通过ftp上传，也可以`在线下载更新`
