### ISSUE TITLE
X96 mini - Python2

### ISSUE THREAD

**Issue by deyloTT** [ophub/amlogic-s9xxx-openwrt#288]
Hey, so i have a python script that i usually run with "python2 script.py" because python3 throws errors. I just got openwrt running on a x96 mini android box and for some reason i cant get python2 installed (i got python3 to install however). Can i be enlightened as to how i can get python2 running? Thanks

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-openwrt/blob/9d9d27f78e416d2245d04cd9506958d86d438eef/router-config/openwrt-master/.config#L3143

![Snip20220824_1](https://user-images.githubusercontent.com/68696949/186386451-30238c05-f4da-4705-802f-1fa0baa5c412.png)


From the official source code, support for python2 has been removed

**Comment by deyloTT** [comment]
Oh boy :( And there isn’t anway to 'sideload' it through community package or something like that?

**Comment by ophub** [comment]
This is the official configuration file of github.com/openwrt, only supports python3

**Comment by deyloTT** [comment]
Ive found a repository which has the packages that gets added successfully but i get error:
Packages for python-light found, but incompatible with the architectures configured

**Comment by ophub** [comment]
What you are looking for is x86_64, the box is `aarch64`

**Comment by deyloTT** [comment]
https://downloads.openwrt.org/releases/packages-18.06/aarch64_generic/packages/

thanks. would this architecture work? Im seeing the packages there also.

**Comment by ophub** [comment]
ok

**Comment by deyloTT** [comment]
> What you are looking for is x86_64, the box is `aarch64`

on my opkg package list configuration, i see that im receiving packages in "/armvirt/64/packages"
is this correct or did i use an incorrect release? Im using s905l x96 mini

**Comment by ophub** [comment]
The software package of aarch64 can be used in amlogic s9xxx devices, regardless of soc

**Comment by deyloTT** [comment]
Ok thanks...one more thing off-tolic: is it possible to install openvpn on my device? Im able to install openvpn-rsa but not the actual openvpn server.

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-openwrt/blob/9d9d27f78e416d2245d04cd9506958d86d438eef/router-config/lede-master/.config#L537-L538

It is included in the `lede` version, but not in the official version. You need to install version 21.03 yourself.

https://github.com/ophub/amlogic-s9xxx-openwrt/releases/tag/OpenWrt_Aml_lede_08.21.2259

**Comment by deyloTT** [comment]
Aahhh i see. Haha. Thanks. Ill have to flash over the box with the lede version then. Thanks for the help

**Comment by deyloTT** [comment]
I just installed the lede version and its in chinese. Anyway to switch to english? Or do i have to download another version? I downloaded the one in the link you sent above.
