### ISSUE TITLE
wetek model 4kiptvh01 wont boot black screen

### ISSUE THREAD

**Issue by murad0522** [ophub/amlogic-s9xxx-openwrt#292]
hello  i have wetek device   
it have 905x + 2GB ram + 8 rom + 100MB ethernet + ap6255 

I tried most of dtb files inside but no boot, 

how I can extract the file , or know the right one , 

the device running android 9 custom made for iptv company here , 

thank you

**Comment by ophub** [comment]
try: https://github.com/ophub/amlogic-s9xxx-openwrt/releases/download/OpenWrt_Aml_lede_09.06.0653/openwrt_s905x_k5.15.62_2022.09.06.img.gz

**Comment by murad0522** [comment]
same thing, no boot. do I need to specify the dtb file?

**Comment by ophub** [comment]
Do you have a product link? Motherboard high-definition picture, network card chip picture

No code output at all? Did you enable USB boot mode?

**Comment by murad0522** [comment]
i dont knwo to enable  USB boot mode I use sd card only 

motherboard high-definition picture, network card chip picture , I can take picture

**Comment by ophub** [comment]
that is not supported

**Comment by murad0522** [comment]
no product link from wetek ,

those links for the motherboard 


https://ibb.co/kgK0smX
https://ibb.co/kBdDxb8
https://ibb.co/cc4QXjx
https://ibb.co/s58g73F
https://ibb.co/64t5Gr5

**Comment by ophub** [comment]
![IMG-20220908-114815](https://user-images.githubusercontent.com/68696949/189085758-ac7dc105-3c43-4a61-9a1e-60ec22a3c6ca.jpg)

![IMG-20220908-115010](https://user-images.githubusercontent.com/68696949/189085783-6a8c6419-b128-4330-9ee8-170fcff43312.jpg)

**Comment by ophub** [comment]
Looking at the photo, it is possible to boot with the default firmware of the s905x. Did you turn on USB debugger mode?

**Comment by murad0522** [comment]
yes i did.. but when i connect usb cable nothing happen  no new device

**Comment by ophub** [comment]
If your device has a reset button, after you try to power on, press and hold for 5 seconds to see if it can enter the flash mode

**Comment by murad0522** [comment]
after long time of trying i figure out how to boot from usb... it's turned out sd boot not working only usb disk. and i should wait for 10 sec and screen will flash two times then it  start... but when i tried to install the openwrt to internal storage its wont boot eeven if i choose same dtb file it's booted from usb.. it's end with bootloop

**Comment by ophub** [comment]
which version of the kernel are you using

**Comment by murad0522** [comment]
i tried this img openwrt_s905x_k5.10.138_2022.08.26.img
also have a problem with the network  as there is no internet most of the time, I put lan to static IP and config DNS in lan and disable LAN  DHCP because I have another DHCP server running when I connect through wifi the phone is connected and all goes well expect no internet  most of the time and if there is internet it's limited I mean there is website wont open like speedtest

**Comment by ophub** [comment]
try 5.15

**Comment by murad0522** [comment]
update, i installed it to internal storage by using this kernel 5.15, but the network problem still exists I hope someone helps me how to  solve it, I tried to use dynamic IP  but still same problem, I need to switch from lan to wan, but I don't know how to do it and if I delete lan interface wan would work

**Comment by ophub** [comment]
Installed. How to use Internet query: openwrt use
