### ISSUE TITLE
5.15.62 webui 升级到5.19.7，然后无法进入webui管理界面了

### ISSUE THREAD

**Issue by AmibaWorld** [ophub/amlogic-s9xxx-openwrt#295]
昨天手贱剑的，直接升级到5.19.7，然后杯具了，提示一下错误信息：
Unable to launch the requested CGI program:
  /www/cgi-bin/luci: Exec format error

**Comment by ophub** [comment]
这个错误和内核无关。你重启一下试试。

你也可以用ssh软件登陆，手动上传内核到/mnt/mmcblk2p4目录下，用命令更新回原来的内核：openwrt-kernel

**Comment by AmibaWorld** [comment]
我看了下 /www 的luci 等一些文件为0字节
![image](https://user-images.githubusercontent.com/34524850/189473390-7eee3c24-fada-4f20-b914-3d6f9e162965.png)
![image](https://user-images.githubusercontent.com/34524850/189473412-f375af8f-fd68-4b50-93e3-ca5dd0c98cd9.png)

**Comment by ophub** [comment]
更新内核只会改两个地方的文件，/boot和/lib/modules/。其他地方都不会动。

**Comment by Vagex** [comment]
今天全新刷机5.19.8 固件，发现 上述那几个文件大小均为 0 字节，我不知道怎么回事，之前版本貌似没有出现这种情况

**Comment by ophub** [comment]
我重新编译一下
