### ISSUE TITLE
大大请问我FORK了你的仓库后，什么都没改，为啥在线编译会失败，但你的不会？

### ISSUE THREAD

**Issue by zhuboqi** [ophub/amlogic-s9xxx-openwrt#302]
https://github.com/zhuboqi/amlogic-s9xxx-openwrt/actions/runs/3148330160

日志在此

**Comment by ophub** [comment]
我今天也失败了，看日志是jq下载失败。等上游修吧

**Comment by ophub** [comment]
我改了下config，移除jq了，这个不需要源码编译，打包脚本里带了。
