### ISSUE TITLE
please include btrfs-progs on your dependency, it makes building openwrt fail without it

### ISSUE THREAD

**Issue by remlei** [ophub/amlogic-s9xxx-openwrt#305]
as title said the build fails on step 6 with error

```
mount: /home/openwrt-s9xx/amlogic-s9xxx-openwrt/tmp/5.15.71/s905w/rootfs: wrong fs type, bad option, bad superblock on /dev/loop9p2, missing codepage or helper program, or other error.
[ ERROR ] mount /dev/loop9p2 failed!
```

im scratching my head with that error even if I followed the instructions to the tee building my own image and I remembered as I tried the prebuilt openwrt image here that it uses btrfs so I ended up trying installing btrfs-progs and that fixed the issue.

I checked the https://is.gd/depend_ubuntu2204_openwrt of that link if it includes on the list, and what you know, its not present.

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/commit/7f77482209ca066e8aacb481d707ad9fe908aa6e

already added
