### ISSUE TITLE
T95Z PLUS - Controlling the LED display dtb

### ISSUE THREAD

**Issue by creamisty** [ophub/amlogic-s9xxx-openwrt#306]
hello. can you add openvfd in meson-gxm-t95z-plus.dtb for next build?
I have tried using the configuration from https://github.com/arthur-liberman/vfd-configurations/blob/master/t95z-1-vfd.conf, and it works fine for me. thanks

![photo_6181433060185190502_y](https://user-images.githubusercontent.com/9110857/193453282-e1e84157-0a79-4469-b5f5-fd8cb92b2f1c.jpg)

**Comment by ophub** [comment]
You can already use it, it means that it has been added in dtb.

**Comment by creamisty** [comment]
for wired network and wireless network works fine on my 95z plus.
wireless network using bcrm-AP6255, nand sandisk, ram 3/32. 

![photo_6296420978355450478_y](https://user-images.githubusercontent.com/9110857/193473462-2597f78f-cad3-4142-8c72-3aef07d811e7.jpg)
![photo_6296420978355450479_y](https://user-images.githubusercontent.com/9110857/193473466-b3b7f6f7-33b3-4e27-8e9f-2d2fc3914a5a.jpg)
![photo_6296420978355450481_y](https://user-images.githubusercontent.com/9110857/193473468-aec91192-3dd0-4855-877b-f7a7448343ea.jpg)
![photo_6296420978355450477_y](https://user-images.githubusercontent.com/9110857/193473505-eef3eabf-d695-472e-9672-8ad9c6bf8618.jpg)

LED work using your meson-gxm-t95z-plus-2.dtb and config from t95z-1-vfd.conf.

========================

![Screenshot from 2022-10-03 02-32-29](https://user-images.githubusercontent.com/9110857/193473687-def27296-48db-4f2f-b07c-ca1df2719d29.png)


tried modified value from your share, make LED is off on me.

**Comment by ophub** [comment]
According to your feedback, gigabit wired, wireless, led can work fine. I will submit this dtb file to the upstream kernel repository. I'll add the led's configuration file to the list of configuration files.

**Comment by ophub** [comment]
According to user feedback, t95z must be started using `/boot/extlinux/extlinux.conf`, which file are you using? Did you rename extlinux.conf.bak to extlinux.conf to start?

I see you are using `uEnv.txt` when testing dtb?

**Comment by creamisty** [comment]
> According to your feedback, gigabit wired, wireless, led can work fine. I will submit this dtb file to the upstream kernel repository. I'll add the led's configuration file to the list of configuration files.

OK. thanks.



> According to user feedback, t95z must be started using `/boot/extlinux/extlinux.conf`, which file are you using? Did you rename extlinux.conf.bak to extlinux.conf to start?
> 
> I see you are using `uEnv.txt` when testing dtb?

yes, im used file extlinux.conf.bak. oh oke. I forgot to rename the file to extlinux.conf. I will try it

**Comment by creamisty** [comment]
the result : 

1. config from: https://github.com/arthur-liberman/vfd-configurations/blob/master/t95z-1-vfd.conf 

LED = ON
```
vfd_gpio_clk='0,71,0'
vfd_gpio_dat='0,72,0'
vfd_gpio_stb='0,70,0'

vfd_chars='0,1,2,3,4'
vfd_dot_bits='0,1,2,3,4,5,6'

vfd_display_type='0x01,0x00,0x00,0x00'
```
![photo_6183940200099590353_y](https://user-images.githubusercontent.com/9110857/193523244-bdd7d18c-eecb-4210-a31f-5427ee82519a.jpg)


2.  config from your modified value : 

LED = OFF
```
vfd_gpio_clk='0,70,0'
vfd_gpio_dat='0,71,0'
vfd_gpio_stb='0,69,0'

vfd_chars='0,1,2,3,4'
vfd_dot_bits='0,1,2,3,4,5,6'

vfd_display_type='0x01,0x00,0x00,0x00'
```
3. config from : https://github.com/arthur-liberman/vfd-configurations/blob/master/t95z-2-vfd.conf

LED = OFF
```
vfd_gpio_clk='0,68,0'
vfd_gpio_dat='0,67,0'
vfd_gpio_stb='0,69,0'

vfd_chars='4,3,2,1,0'
vfd_dot_bits='0,1,2,3,4,5,6'

vfd_display_type='0x01,0x00,0x00,0x00'
```

4. modified value from config NO. 3 : 

LED = ON , sometimes symbol wifi or lan or etc is on or off
```
vfd_gpio_clk='0,71,0'
vfd_gpio_dat='0,72,0'
vfd_gpio_stb='0,70,0'

vfd_chars='4,3,2,1,0'
vfd_dot_bits='0,1,2,3,4,5,6'

vfd_display_type='0x01,0x00,0x00,0x00'
```
My time = HH:MM = 14:49
![photo_6183940200099590368_y](https://user-images.githubusercontent.com/9110857/193527497-d9e545f7-3df4-4289-adbc-ff5a2573444f.jpg)

My time = HH:MM = 14:50
![photo_6183940200099590367_y](https://user-images.githubusercontent.com/9110857/193527768-24bb3862-440a-4e48-be56-cd980ab54e64.jpg)

**Comment by creamisty** [comment]
Is there a difference when I use android stock firmware from 7.1.2 and android 9?

**Comment by ophub** [comment]
```
vfd_gpio_clk='0,67,0'
vfd_gpio_dat='0,66,0'
vfd_gpio_stb='0,68,0'

vfd_chars='4,3,2,1,0'

vfd_dot_bits='0,1,2,3,4,5,6'

vfd_display_type='0x01,0x00,0x00,0x00'

functions='wifi eth usb alarm play pause'
```

test this result

**Comment by creamisty** [comment]
> ```
> vfd_gpio_clk='0,67,0'
> vfd_gpio_dat='0,66,0'
> vfd_gpio_stb='0,68,0'
> 
> vfd_chars='4,3,2,1,0'
> 
> vfd_dot_bits='0,1,2,3,4,5,6'
> 
> vfd_display_type='0x01,0x00,0x00,0x00'
> 
> functions='wifi eth usb alarm play pause'
> ```
> 
> test this result

LED = OFF

**Comment by ophub** [comment]
```
vfd_gpio_clk='0,71,0'
vfd_gpio_dat='0,72,0'
vfd_gpio_stb='0,70,0'

vfd_chars='0,1,2,3,4'

vfd_dot_bits='0,1,2,3,4,5,6'

vfd_display_type='0x01,0x00,0x00,0x00'

functions='wifi eth usb alarm play pause'
```
try again

**Comment by creamisty** [comment]
> ```
> vfd_gpio_clk='0,71,0'
> vfd_gpio_dat='0,72,0'
> vfd_gpio_stb='0,70,0'
> 
> vfd_chars='0,1,2,3,4'
> 
> vfd_dot_bits='0,1,2,3,4,5,6'
> 
> vfd_display_type='0x01,0x00,0x00,0x00'
> 
> functions='wifi eth usb alarm play pause'
> ```
> 
> try again

![photo_6183940200099590387_y](https://user-images.githubusercontent.com/9110857/193535782-423c78cf-a1b0-4133-bce1-d2a930e3afa6.jpg)

works great!!!!

**Comment by ophub** [comment]
ok, congratulations
