### ISSUE TITLE
hello，could you please help me

### ISSUE THREAD

**Issue by univerioiln233** [ophub/amlogic-s9xxx-openwrt#307]
just like below
https://github.com/unifreq/openwrt_packit/issues/133#issue-1398716594

**Comment by ophub** [comment]
init 6 = `reboot`

**Comment by ophub** [comment]
Then you use the `reboot` command, the results of these two commands are reboots

**Comment by ophub** [comment]
kmod需要随固件编译，插件和软件包可以后期安装，keenel可以随时更换。
