### ISSUE TITLE
支持玩客云

### ISSUE THREAD

**Issue by jwkinko** [ophub/amlogic-s9xxx-openwrt#309]
大佬能否添加玩客云的支持

**Comment by ophub** [comment]
这个上游已经支持了，不用再支持了，你直接使用即可。

https://github.com/coolsnowwolf/lede

**Comment by jwkinko** [comment]
这个能写入emmc吗？

**Comment by jwkinko** [comment]
> 这个上游已经支持了，不用再支持了，你直接使用即可。
> 
> 
> 
> https://github.com/coolsnowwolf/lede

这个不能写入emmc吧

**Comment by ophub** [comment]
我不了解这个设备怎么刷机，你到他仓库问问

**Comment by jwkinko** [comment]
> 我不了解这个设备怎么刷机，你到他仓库问问

好的大佬
