### ISSUE TITLE
怎么添加ssrp插件？

### ISSUE THREAD

**Issue by 3136083906** [ophub/amlogic-s9xxx-openwrt#311]
n1刷完openwrt后怎么添加ssrp插件？

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-openwrt/blob/main/router-config/README.cn.md#举例1添加第三方软件包

这有加插件的方法，但是我不知道你说的是什么。

**Comment by 3136083906** [comment]
> [https://github.com/ophub/amlogic-s9xxx-openwrt/blob/main/router-config/README.cn.md#举例1添加第三方软件包](https://github.com/ophub/amlogic-s9xxx-openwrt/blob/main/router-config/README.cn.md#%E4%B8%BE%E4%BE%8B1%E6%B7%BB%E5%8A%A0%E7%AC%AC%E4%B8%89%E6%96%B9%E8%BD%AF%E4%BB%B6%E5%8C%85)
> 
> 这有加插件的方法，但是我不知道你说的是什么。

我说的是刷完固件后怎么添加，我是小白不会编译，我记得以前你的固件是有ssrp的啊

**Comment by ophub** [comment]
我一直没有，我只带了官方的默认固件。因为我不会编译，失败了不会调试，所以除了晶晨宝盒外没有第三方的插件。

找到ipk上传安装，方法：
`opkg install --force-reinstall <pkgs>`
