### ISSUE TITLE
求助s905l3a W10访问samba服务器0x80070035

### ISSUE THREAD

**Issue by link-like-9536** [ophub/amlogic-s9xxx-openwrt#314]
openwrt_lede_s905l3a_k5.10.148_2022.10.18.img固件

**Comment by alegoho** [comment]
大概是你系统问题，新版WIN10不允许HTTP连接，你在注册表改一下东西就能访问了

**Comment by ophub** [comment]
https://blog.csdn.net/qq_38390133/article/details/108843084

解决0x80070035找不到网络路径
局域网中，能ping通共享服务器ip地址却无法进行本地资源访问，得到0x80070035的结果
这可能是SMB协议未打开，造成客户机和服务器无法建立连接，即便是网络相通的情况下
环境：window10

解决方法1：
1、以管理员运行cmd
2、输入sc.exe config lanmanworkstation depend= bowser/mrxsmb10/nsi，回车
3、sc.exe config mrxsmb20 start= disabled，回车
4、进行这些更改后，必须重启计算机

解决方法2：
1、打开控制面板-程序-点击启用或关闭windows功能
2、勾选SMB 1.0/CIFS 文件共享支持下的所有勾选项
3、重启电脑

方法1和方法2效果是一样的，只是一个是命令执行，一个是手动操作
