### ISSUE TITLE
求助  S905L3A 可以安装Aria2么，使用什么芯片类型？

### ISSUE THREAD

**Issue by link-like-9536** [ophub/amlogic-s9xxx-openwrt#319]

**Comment by ophub** [comment]
不理解你的问题，看不懂你问的什么。

**Comment by Peterzhangnoise** [comment]
或者你也可以试试云编译，个性化定制。
https://github.com/ophub/amlogic-s9xxx-openwrt/blob/main/router-config/README.cn.md

**Comment by link-like-9536** [comment]
谢谢，我的问题是，前端时间尝试使用opk 安装Aria2，失败。使用.ipk文件安装又失败。尝试编译，也装不上这个插件。我怀疑是是不是S905L3A架构本身就不支持。编译时是什么确定编译后在这个架构上可以运行的？

**Comment by ophub** [comment]
https://github.com/coolsnowwolf/luci/blob/master/applications/luci-app-aria2/Makefile

都支持
