### ISSUE TITLE
添加EAIS 750的支持

### ISSUE THREAD

**Issue by asdawn** [ophub/amlogic-s9xxx-openwrt#320]
EAIS 750E, A311D，双网卡
https://www.yuque.com/william-apmjq/vob7gl/yz25g9

是否只要替换dtb就能使用a311d的通用版？谢谢

**Comment by ophub** [comment]
你试一下

**Comment by whmzsu** [comment]
楼主，这么久了，试了没？

**Comment by Mokou-Mokou** [comment]
能使用了吗
