### ISSUE TITLE
Wifi of E900V22C not detected(?)?(may duplicate)

### ISSUE THREAD

**Issue by zhangjing-GitHub-Code** [ophub/amlogic-s9xxx-openwrt#324]
创维E900V22C(s905l3a-b)，u盘，没装emmc
用 wifi detect没输出，配置页面也找不到
可能重复
所以怎么弄？自己编译加参数还是找哪个版本
看板子上有个unisoc uwe5621ds的(?)
是Wifi吗？

**Comment by ophub** [comment]
这个无线芯片没驱动，暂时用不了无线
