### ISSUE TITLE
能否增加iStore插件中心

### ISSUE THREAD

**Issue by Edwardyx** [ophub/amlogic-s9xxx-openwrt#329]
[Github/iStore](https://github.com/linkease/istore) 
大佬辛苦。发现自带的插件比较少，想装些千奇百怪的诸如****wall等可以科学上网的。自己太笨，不会代码，虽然大佬有说明文档，但是自己编译定制个性化固件对我来说还是太难了。所以想问问大佬能不能把iStore插件中心给加入进来。
谢谢大佬。

**Comment by ophub** [comment]
这个插件需要固件开发者自主集成 iStore，并解决 iStore 里面的各种插件的依赖。
我没有源可以提供后期的在线依赖下载，调试插件的依赖不如直接在编译时集成插件来的更容易。这个插件没有已经为aarch64调试好的ipk吗？或者看看谁为aarch64调试好软件中心了，直接使用他的集成。
