### ISSUE TITLE
tf卡无法启动

### ISSUE THREAD

**Issue by Peterzhangnoise** [ophub/amlogic-s9xxx-openwrt#330]
大佬，我直接从淘宝上买了个e900v22c,s905l3a。之前那个e900v22d不用了
现在遇到以下问题

                           网口
                                              USB1
                                              USB2
                                              tf卡

使用slc+is903主控的u盘，usb1 usb2都能启动
使用tf卡，就启动不了黑屏
使用tf卡任意读卡器，usb2能启动usb1开机黑屏+重启

这是什么原因？

**Comment by ophub** [comment]
一般USB都是没问题的，但是TF/SD在一些设备上会无法启动，可能是供电或干扰导致的。
