### ISSUE TITLE
Node.js 12 actions are deprecated

### ISSUE THREAD

**Issue by leakssh** [ophub/amlogic-s9xxx-openwrt#331]
![Screenshot_2022-11-05-11-28-43-686_com android chrome](https://user-images.githubusercontent.com/87708571/200100804-58e4ab13-634c-45b2-93a5-3d1ee0b14d75.jpg)

**Comment by ophub** [comment]
OK, thanks for the reminder. The third-party service used by this actions has not been updated for two years. I will look for an upgraded version.

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-openwrt/commit/681741157aad8fe1e32b7092b7641b465d0f67a0

The original source code repository has not been updated for 2 years. I replaced the repository and eliminated the node warning.
