### ISSUE TITLE
E900V22C（L3A+B）刷入固件无法连接网络

### ISSUE THREAD

**Issue by hehe-xiao** [ophub/amlogic-s9xxx-openwrt#334]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: [e.g. S905l3a]
 - Model [e.g. E900V22C]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 5.15.100]
 - Release: [e.g. lede]

**Describe the bug | 问题描述**
我的芯片是L3A+B 输入固件后无法连接网络，ERRO提示
ech0: validation of rmii with support 0000000,0000000,00006280 and advertisement 0000000,0000000,00006280 failed: -22
eth0: no phy at addr -1
eth0: stmmac_open: Cannot attach to PHY (-19)
![image](https://user-images.githubusercontent.com/55172531/201526253-b29cb8ae-ad36-42cd-bee6-81f2e84ce151.png)

**Comment by ophub** [comment]
试试5.10的固件，多个u-boot
