### ISSUE TITLE
s905 sunvell q-box emmc

### ISSUE THREAD

**Issue by suezz** [ophub/amlogic-s9xxx-openwrt#338]
Hi!, sorry my noob question..., does it possible the installation on emmc with the dtb I'm using in libreelec?
gxbb_p200_2G_1Gbit.dtb

tried using s905_k5.15.78_2022.11.16.img with  meson-gxbb-beelink-mini-mx.dtb  but no success
or no way for s905?

I ask before have to restore from brick another time....:)

**Comment by ophub** [comment]
meson-gxbb-p200.dtb
meson-gxbb-p201.dtb

**Comment by suezz** [comment]
thanks for reply but
brick
brick

is there a way to build the dbt from the one that is ok for libreelec?
or other to try? I make a new usb cable and became fast in restore android...:))

**Comment by ophub** [comment]
The armbian system in the USB can only be started on the basis of the Android system.

If the libreelec system is installed in the current box, first backup your libreelec system, and then restore to the original Android system. so that you can test armbian

**Comment by suezz** [comment]
Specific that I'm trying with OpenWRT, I see that booting from USB works whether Android or LibreELEC is installed in the box. I can't do the installation on emmc... I realized that it is quite complicated and it is already a lot that works from USB without modifications. The 'problem' is that if you have also connected a tethering smartphone the box does not boot from USB... Thanks all the same! :)

**Comment by ophub** [comment]
Currently s905 TV Boxes can only be used in TF/SD/USB, other types of TV Boxes also support writing to EMMC.
