### ISSUE TITLE
Ugoos AM6B Plus (2021)

### ISSUE THREAD

**Issue by cleberjorge** [ophub/amlogic-s9xxx-openwrt#339]
Hello guys
TV Box Ugoos AM6B Plus (2021) WiFi is not recognized using openwrt_official_s922x_k5.15.79_2022.11.20.img and DTB meson-g12b-ugoos-am6b-plus.dtb
Thanks

**Comment by ophub** [comment]
no wifi6 driver

**Comment by cleberjorge** [comment]
I use EmuELEC in the Box and the Wifi works perfectly, I tried to use the EmuELEC DTB and Openwrt but it didn't work.
Perhaps this information will be useful to you.
Thanks for the feedback

**Comment by cleberjorge** [comment]
I use EmuELEC in the Box and the Wifi works perfectly, I tried to use the EmuELEC DTB and Openwrt but it didn't work.
Perhaps this information will be useful to you.
Thanks for the feedback

**Comment by cleberjorge** [comment]
> no wifi6 driver

I use EmuELEC in the Box and the Wifi works perfectly, I tried to use the EmuELEC DTB in Openwrt but it didn't work.
Perhaps this information will be useful to you.
Thanks for the feedback

**Comment by ophub** [comment]
The Android system has drivers, but there are no drivers in the mainline kernel.
