### ISSUE TITLE
大神好

### ISSUE THREAD

**Issue by 281677160** [ophub/amlogic-s9xxx-openwrt#340]
![QQ截图20221121235257](https://user-images.githubusercontent.com/66651997/203099655-70ec81b1-5ace-4cf8-a8fd-c69b3415c562.png)
这个命令应该是错了，应该是gzip，打包的固件不会压缩了

**Comment by ophub** [comment]
安装依赖pigz

**Comment by 281677160** [comment]
好的，感谢大神




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ophub/amlogic-s9xxx-openwrt"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月22日(星期二) 上午8:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ophub/amlogic-s9xxx-openwrt] 大神好 (Issue #340)





 
安装依赖pigz

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/compile-kernel/tools/script/ubuntu2204-make-openwrt-depends

这个文件里的都是必要的依赖，本地不安装，在编译时会有很多错误。

**Comment by 281677160** [comment]
非常感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ophub/amlogic-s9xxx-openwrt"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月22日(星期二) 上午9:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ophub/amlogic-s9xxx-openwrt] 大神好 (Issue #340)





 
https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/compile-kernel/tools/script/ubuntu2204-make-openwrt-depends
 
这个文件里的都是必要的依赖，本地不安装，在编译时会有很多错误。
