### ISSUE TITLE
能支持一下赚钱宝pro吗，ws1508飞碟那款

### ISSUE THREAD

**Issue by Jeremy-JM** [ophub/amlogic-s9xxx-openwrt#342]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: [e.g. S805]
 - Model [e.g. 赚钱宝pro，ws1508]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 5.15.100]
 - Release: [e.g. lede]

**Describe the bug | 问题描述**
Describe the problem in detail and attach screenshots if necessary.

能支持一下赚钱宝pro吗？ws1508飞碟那款

晶晨 s805 的芯片
ram: 512mb
rom: 4g
百兆网卡

**Comment by ophub** [comment]
s805使用的32位内核和现在的不通用。

**Comment by Jeremy-JM** [comment]
> s805使用的32位内核和现在的不通用。

好的，谢谢啦
