### ISSUE TITLE
I can't fix firmware openwrt for my tv box, tanix tx6

### ISSUE THREAD

**Issue by Doejon11** [ophub/amlogic-s9xxx-openwrt#343]
I couldn't find the firmware for the tanix tx6 Soc h6 tv box, so I tried the firmware openwrt_h6_vplus_R22.11.11_k5.15.80-flippy-79+o.img.gz
and
openwrt_h6_vplus_R22.11.11_k6.0.10-flippy-79+.img.gz
but it didn't boot.  The HDMI port has no picture and the LAN port is also not recognized on the computer, nothing happens.  can you help me build the firmware for tanix tx6 Soc h6?  Thank you!

**Comment by ophub** [comment]
not support
