### ISSUE TITLE
x96-air no terminal or no display, tried x96 air gbit and simple dtbs

### ISSUE THREAD

**Issue by P9ison** [ophub/amlogic-s9xxx-openwrt#344]
- SOC: S905x3
 - Model: X96-Air

Tried booting with both dtbs, one of gbit and one simple. I am not getting any visual display at all, but can confirm that it does boot because i tried plugging in the ethernet cable and my adapter showed me gateway of 192.168.1.1 but i cannot login or ssh into 192.168.1.1 (No route to host). Normally i can use my Android box with hdmi easily.

**Comment by ophub** [comment]
If you already have a 192.168.1.1 device in your network, connect the x96 to the computer, otherwise the ip will re-emerge.

openwrt does not require hdmi

**Comment by P9ison** [comment]
#

> If you already have a 192.168.1.1 device in your network, connect the x96 to the computer, otherwise the ip will re-emerge.
> 
> openwrt does not require hdmi

It doesn't work i cannot access luci or ssh just can see the gateway. And no display.

**Comment by ophub** [comment]
/boot/uEnv.txt

X96-Air-1Gb: meson-sm1-x96-air-gbit.dtb
X96-Air-100Mb: meson-sm1-x96-air.dtb
X96-Air-Q1000: meson-sm1-x96-max-plus-q2.dtb

**Comment by P9ison** [comment]
> /boot/uEnv.txt
> 
> X96-Air-1Gb: meson-sm1-x96-air-gbit.dtb X96-Air-100Mb: meson-sm1-x96-air.dtb X96-Air-Q1000: meson-sm1-x96-max-plus-q2.dtb

Do i have to change the Uboot for any of these files?
And should I try getting a display output with AV Cable?
One thing i forgot to mention was, I was not getting any display at all after the x96 air splash logo it went no signal. So no black screen or anything.

**Comment by ophub** [comment]
try 5.15.y.
don’t need u-boot, only dtb right.

**Comment by P9ison** [comment]
> try 5.15.y. don’t need u-boot, only dtb right.

Ok i tried it now i get stuck at device eth0 entered promiscuous mode.

**Comment by P9ison** [comment]
![Uploading 167027006222428890683393700653.jpg…]()

**Comment by P9ison** [comment]
![☆_6 Dec 01_08 Horus_v2 5_OP8-8T](https://user-images.githubusercontent.com/95067625/205733277-90966529-97ad-4379-b9af-932fece90bb6.jpg)

Ok now it says this for some reason

**Comment by ophub** [comment]
This is the normal startup, press Enter on the keyboard, and you can see the welcome interface. Now the browser can access 192.168.1.1 to manage

**Comment by P9ison** [comment]
> This is the normal startup, press Enter on the keyboard, and you can see the welcome interface. Now the browser can access 192.168.1.1 to manage

Alright thanks.
How do I reset to defaults?

**Comment by P9ison** [comment]
> ttyd or ssh: `firstboot`

Hey i cannot upload anything.
Like i have tried SCP, FTP but it stays at 0% and creates a 0kb file of whatever i am trying to upload.

**Comment by ophub** [comment]
can use scp or web upload
