### ISSUE TITLE
官方源码固件安装不了openclash

### ISSUE THREAD

**Issue by 3136083906** [ophub/amlogic-s9xxx-openwrt#346]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: [e.g. S912]
 - Model [e.g. 章鱼星球]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 5.15.81]
 - Release: [e.g. 官方]

**Describe the bug | 问题描述**
Describe the problem in detail and attach screenshots if necessary.
详细描述问题，并在必要时附上屏幕截图。

如题安装不了openclash，提示好像是缺少依赖，lede固件没问题，软件仓库都是同样的

**Comment by ophub** [comment]
第三方插件，在编译时集成，后期安装比较麻烦。
