### ISSUE TITLE
Cannot enable wifi on X96 air kernel 5.15.80 & 81.

### ISSUE THREAD

**Issue by P9ison** [ophub/amlogic-s9xxx-openwrt#347]
- SOC: S905X3
 - Model X96 Air 
  
Wifi does not enable on kernel 5.15.81 and 80
It works perfectly on 5.10.156
When i tap enable on 15.81 & 15.80 
Box reboots.

**Comment by ophub** [comment]
This driver comes from a third party, and it is not very compatible with the mainline kernel. Some versions will not work. You should use 5.10.

**Comment by hillz2** [comment]
I have X96 Air too and wifi doesn't work, where can I find the download link for kernel 5.10.156 @P9ison @ophub ?

**Comment by ophub** [comment]
armbian-update -k 5.10.161

**Comment by hillz2** [comment]
@ophub my OpenWrt doesn't have armbian-update installed

**Comment by ophub** [comment]
Login in to openwrt → system menu → Amlogic Service → Select the 5.10 kernel in the settings  →  Download updates online
