### ISSUE TITLE
广东移动魔百盒cm201-1ys

### ISSUE THREAD

**Issue by LEGION128** [ophub/amlogic-s9xxx-openwrt#349]
我是魔百盒cm201-1ys 广东移动的盒子  请问这款盒子可以刷openwrt吗？  如果可以我需要下那个固件 
![image](https://user-images.githubusercontent.com/60326273/206472411-434bc0bd-f118-41f9-b2e7-ff2ac4786e77.png)

**Comment by ophub** [comment]
/boot目录的uEnv.txt改dtb名称为meson-gxl-s905x-p212.dtb
把u-boot-s905x-s912.bin复制为u-boot.ext

**Comment by LEGION128** [comment]
你好 是要下载这个固件吗？
![image](https://user-images.githubusercontent.com/60326273/206855706-2a8ff327-0975-4744-a080-62c97515b708.png)

**Comment by ophub** [comment]
对

**Comment by LEGION128** [comment]
![image](https://user-images.githubusercontent.com/60326273/206856730-49924814-ca69-4253-a451-6bd4dc75d27b.png)

**Comment by ophub** [comment]
复制一份，原来的保留

**Comment by LEGION128** [comment]
不是很懂

**Comment by LEGION128** [comment]
好像懂了 吧固件刷到u盘 虚插到盒子的usb孔上 通电开机马上吧u盘插进 屏幕显示花瓶就是代表成功了是吧

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-openwrt/blob/main/router-config/README.cn.md

10.10

**Comment by LEGION128** [comment]
您好 根据你的提示 我在盒子上开启了usb调试 win上下载且配置了adb  但是我填入ip显示这个
![image](https://user-images.githubusercontent.com/60326273/206859820-d7422ef2-8adf-4d79-bd72-5570747f262c.png)

**Comment by ophub** [comment]
你这没adb连接进去，继续尝试

**Comment by Cxy-2008** [comment]
你好，我是跟你同款盒子，也是套装124的，请问你解决了吗？
