### ISSUE TITLE
Tanix Tx5 Max (S905x2)

### ISSUE THREAD

**Issue by mreser99** [ophub/amlogic-s9xxx-openwrt#351]
I wanna use openwrt official in this device. Is that possible?

Specs:
SoC: Amlogic S905X2 Quad Core
RAM and Storage: 4 GB DDR4 / 32 GB eMMC
![IMG_4951](https://user-images.githubusercontent.com/77234662/206680508-13685ed1-c2ae-4ba2-91b6-677528b1da8c.jpeg)

**Comment by ophub** [comment]
try s905x2-km3

**Comment by mreser99** [comment]
Thank you it's booted but i couldn't connect web-ui at all. Am i doing something wrong?
When i check ip address it seems exist.

**Comment by ophub** [comment]
Do you have a monitor and keyboard? Connected, after the startup code stops, press Enter to see the welcome interface, right?

**Comment by ophub** [comment]
cat /boot/uEnv.txt

**Comment by mreser99** [comment]
No i'm using `openwrt_official_s905x2_k5.10.158_2022.12.09.img` `km3` one had ethernet issue. 
This is the screenshot and yes i'm using with default options.

![image](https://user-images.githubusercontent.com/77234662/206731153-756225ff-e9db-4d4e-a3e4-eed7ee2af9e7.png)

**Comment by ophub** [comment]
Install option 301 - X96-Max-4GB

**Comment by mreser99** [comment]
These are for just install or these gonna make my wifi works also?
It doesn't make my device brick don't it? 
I'll do this like this, right?
![image](https://user-images.githubusercontent.com/77234662/206733066-7dc0402c-382a-41de-be95-513fc210f2cd.png)

And thank for your help 😊

**Comment by ophub** [comment]
right

**Comment by mreser99** [comment]
Sorry dear developer it's my fault. 
Here it is;
`Network: Wifi ac 2×2 (RTL8222BS) – Bluetooth 4.1 – Ethernet Gigabit`

**Comment by ophub** [comment]
https://github.com/unifreq/linux-5.15.y/tree/main/drivers/net/wireless/realtek

no drivers.

**Comment by mreser99** [comment]
I see dear developer. I'll buy something with compatible. Thank you for all :)
