### ISSUE TITLE
Cant install wireguard

### ISSUE THREAD

**Issue by tuantrung96** [ophub/amlogic-s9xxx-openwrt#352]
I have install Openwrt on my Odroid n2 and running smoot  without any problam but there is  no way to install wireguard as it said not compatible .As it is different so there are many  usb drive cant install too.  Can someone guild how to install wireguard as it run faster than Openvpn thank.

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-openwrt/blob/06c65244b4d43416c29885020e70b780cf47d5d7/router-config/lede-master/config#L594
