### ISSUE TITLE
LEDE in English

### ISSUE THREAD

**Issue by mreser99** [ophub/amlogic-s9xxx-openwrt#354]
Is there any way to use LEDE project with English Language?

**Comment by ophub** [comment]
Add English translation files to the LEDE-plugin

**Comment by mreser99** [comment]
How can i do that, into .img or somewhere else? And how can i find the translation files as you mentioned?

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-openwrt/tree/main/router-config

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-openwrt/tree/main/router-config#411-let-the-firmware-support-the-native-language

If the plug-in you use has an English translation, just enable it. Generally, plug-ins come with English language packs.

**Comment by mreser99** [comment]
Plug-ins are yes but whole menu of LEDE is chinese. I'll try

**Comment by mreser99** [comment]
I've made 2 different builds since yesterday but no luck, still chinese. I've removed chinese and put the english main language but it's not resolved. 
Did i something wrong?

**Comment by ophub** [comment]
screenshot
