### ISSUE TITLE
Terminal information for Can't locate strict.pm in @INC

### ISSUE THREAD

**Issue by gforce1206** [ophub/amlogic-s9xxx-openwrt#359]
![捕获](https://user-images.githubusercontent.com/72802453/209920076-9b1fcbfa-31d4-4674-8092-5925d77c3679.PNG)
compile with Lede，sudo ./make -s 2048 -b s905l2 -k 5.10.161

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-openwrt/tree/main/router-config#1011-required-options-for-openwrt

```
Languages -> Perl
             -> perl-http-date
             -> perlbase-file
             -> perlbase-getopt
             -> perlbase-time
             -> perlbase-unicode
             -> perlbase-utf8
```

**Comment by gforce1206** [comment]
thanks，I try try

**Comment by gforce1206** [comment]
> You lack `perl`. According to the documentation, select all the required dependencies you lack.
> 
> https://github.com/ophub/amlogic-s9xxx-openwrt/tree/main/router-config#1011-required-options-for-openwrt
> 
> ```
> Languages -> Perl
>              -> perl-http-date
>              -> perlbase-file
>              -> perlbase-getopt
>              -> perlbase-time
>              -> perlbase-unicode
>              -> perlbase-utf8
> ```
> 
> ![Snip20221229_2](https://user-images.githubusercontent.com/68696949/209920755-a93774d6-4423-4925-a54b-9a6dd36fad53.png)

thanks，I try try
