### ISSUE TITLE
Corrupted archive

### ISSUE THREAD

**Issue by BlackGlassSkin** [ophub/amlogic-s9xxx-openwrt#362]
Hi.
I tried to install one of the 2 openwrt systems on the sd card,
- [X] OpenWrt_Aml_official_01.04.1056

-  openwrt_official_s905x3_k5.15.86_2023.01.04
-  openwrt_official_s905x3_k6.1.3_2023.01.04

In both cases, the same error occurs when writing to the SD card

`"Something went wrong.If it is compressedimage,pleasecheck that the archive is not corrupted."`

`"User did not grant permission."`

**Comment by Manssizz** [comment]
try burn again with etcher.

**Comment by BlackGlassSkin** [comment]
@Manssizz ,cheers mate

I was able to install using "LibreELEC USB-SD Creator"
