### ISSUE TITLE
Kernel 6 not work on stb ram 1gb?

### ISSUE THREAD

**Issue by zaiyin** [ophub/amlogic-s9xxx-openwrt#364]
I tried openwrt a905x with kernel 6 on stb ram 1gb but won't boot, I tried on stb hg680p and b860h devices
Does kernel 6 not support 1gb ram devices?

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-openwrt/blob/48f46e7d87f30b66bcf744d5d349a36ef81c4a69/amlogic-s9xxx/common-files/rootfs/etc/model_database.txt#L6

**Comment by zaiyin** [comment]
hg680p device has two versions of 2gb ram and 1gb ram.
2gb ram kernel 6 running normally but 1gb ram not booting

**Comment by ophub** [comment]
Test the firmware of the 5.15 kernel
