### ISSUE TITLE
大神，打包步骤好像有点问题

### ISSUE THREAD

**Issue by 281677160** [ophub/amlogic-s9xxx-openwrt#365]
在您仓库的 https://github.com/ophub/amlogic-s9xxx-openwrt/actions/runs/3866857706/jobs/6591253656 
Build OpenWrt firmware 步骤截的图片，您自己在这个步骤展开看看就知道了，我自己打包也是同样有这样的错误，不知道正常不

![QQ截图20230109163340](https://user-images.githubusercontent.com/66651997/211267836-c6cd5c74-06c7-4bea-bd0e-52d102d04f6f.png)

![QQ截图20230109163406](https://user-images.githubusercontent.com/66651997/211267856-b6cced5a-3fd9-40df-93a8-8a5770e97f5d.png)

**Comment by ophub** [comment]
我重新打包下lede固件，1个小时后可以使用。
其他两个版本的没问题。
