### ISSUE TITLE
玩客云pro Amlogic S912版本适配openwrt，help

### ISSUE THREAD

**Issue by jinjd** [ophub/amlogic-s9xxx-openwrt#367]
Hi,
Could you help me  to solve the problem of Wankeyun pro
(Amlogic S912 +2G+8G) adaptive, please?

Thanks!! :)

**Comment by ophub** [comment]
这个产品这里不支持，你可以在lede里直接编译

**Comment by jinjd** [comment]
> 这个产品这里不支持，你可以在lede里直接编译

好的，Amlogic S912版本和章鱼星球一样，但是使用其镜像刷机失败，后续能支持吗？

**Comment by ophub** [comment]
这个盒子是32位的，仓库里下载的都是64位的，不能通用。
这个盒子在 lede 源码里支持了，你可以直接使用源码编译。

**Comment by ophub** [comment]
这个盒子是32位的，仓库里下载的都是64位的，不能通用。
这个盒子在 lede 源码里支持了，你可以直接使用源码编译。

**Comment by jinjd** [comment]
> lede 源码

好的感谢
