### ISSUE TITLE
Openwrt H96MAX RK3318

### ISSUE THREAD

**Issue by yoelwib11** [ophub/amlogic-s9xxx-openwrt#378]
I see that there is a dtb for the a95x rk3318 on new kernel, but i don't see any firmware for that box. I am using h96max box with rk3318. So how do i use openwrt using this box?

Thank you so much.

**Comment by ophub** [comment]
need u-boot

**Comment by yoelwib11** [comment]
Yes i have. But which firmware should i use?

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/0d6a02d871cf46f8f7b023c59f43eecde76d9ca8/build-armbian/armbian-files/common-files/etc/model_database.conf#L165

u-boot.itb
idbloader.img
rk3318-xxx.dtb

**Comment by yoelwib11** [comment]
Yes i have both. So, what should i do? Please tell me how.

**Comment by ophub** [comment]
Upload these files, I will make one by hand, and you can test whether it can be used.

**Comment by yoelwib11** [comment]
[H96 Max RK3318.zip](https://github.com/ophub/amlogic-s9xxx-openwrt/files/10673290/H96.Max.RK3318.zip)

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-openwrt/releases/tag/OpenWrt_Aml_lede_02.06.2323

download: `openwrt_rk3318_h96max.img.gz`

**Comment by yoelwib11** [comment]
Btw the firmware on my box is still an Android TV.

**Comment by ophub** [comment]
I made it using the 6.1.10 kernel. I use your 2 u-boots, and the dtb file uses the one with h96max. As long as these three files are correct, it should be able to start normally in theory.

See the link above for how to boot from USB.

**Comment by yoelwib11** [comment]
I just downloaded it from https://cloud.mail.ru/public/KGXQ/a5GcEg8t9/Rockchip/LINUX/Armbian_rk3318.rar. 
And then i burn trust.img and uboot.img.

Yes but why your firmware can't be changed the dtb file? I mean unlike amlogic firmware which boot partition is editable in Windows.

**Comment by ophub** [comment]
amlogic is in fat32 format, so it can.
This rockchip uses the ext4 format, which does not support opening.

You can mount the modification under ubuntu/armbian and other systems
```
sudo losetup -P -f --show openwrt.img
sudo mount /dev/loopxxxp1 xxxx
sudo mount /dev/loopxxxp2 yyyy
```

**Comment by yoelwib11** [comment]
[rk3318-h96max-box.zip](https://github.com/ophub/amlogic-s9xxx-openwrt/files/10683158/rk3318-h96max-box.zip)

Can you edit the dtb with this one please? Maybe it is because dtb. Now i am boot Armbian with this dtb and kernel 6.1.9-rockchip64 on emmc.

**Comment by yoelwib11** [comment]
I just change dtb by myself but stuck in here. Just reboot and reboot. Can you help me please?
![IMG_20230208_200122](https://user-images.githubusercontent.com/61351018/217537628-f100ca33-f3e8-43e4-b672-eddaa75b8963.jpg)

**Comment by ophub** [comment]
Armbian_5.99_Rk3328-tv_Debian_buster_default_4.4.154_desktop_20191121.img

kernel: `4.4.154-rk3328-tv`

```
LABEL Armbian
  LINUX /Image
  INITRD /uInitrd
  FDT /dtb/rockchip/rk3328-mx10-fast.dtb
#  FDT /dtb/rockchip/rk3328-a5x.dtb
#  FDT /dtb/rockchip/rk3328-box-trn9.dtb
  APPEND root=LABEL=ROOTFS rootflags=data=writeback rw console=uart8250,mmio32,0xff130000 console=tty0 no_console_suspend consoleblank=0 fsck.fix=yes fsck.repair=yes net.ifnames=0 
```

What is the purpose of the `rk3328` Armbian you provided? What does this have to do with your H96MAX(rk3318)?

**Comment by yoelwib11** [comment]
Finally. Thank you so much. I just change base firmware armbian on emmc and flash your openwrt firmware on sdcard, change dtb with wifi on. But it can't show on monitor. Just blank. I don't know why. 
![16758810743088203555681149615797](https://user-images.githubusercontent.com/61351018/217620413-0f8ff73b-4f41-4873-af13-2de707a9d030.jpg)

**Comment by ophub** [comment]
Openwrt is configured and managed daily through browser access or ssh access without a monitor.
No HDMI output is not supported for DTB files.

**Comment by osnipezzini** [comment]
> Finally. Thank you so much. I just change base firmware armbian on emmc and flash your openwrt firmware on sdcard, change dtb with wifi on. But it can't show on monitor. Just blank. I don't know why. ![16758810743088203555681149615797](https://user-images.githubusercontent.com/61351018/217620413-0f8ff73b-4f41-4873-af13-2de707a9d030.jpg)

Can you post how do you can make this work ?

**Comment by aagym888** [comment]
> https://github.com/ophub/amlogic-s9xxx-openwrt/releases/tag/OpenWrt_Aml_lede_02.06.2323
> 
> download: `openwrt_rk3318_h96max.img.gz`
> 
> Set the box to boot from USB/TF/SD： https://github.com/ophub/amlogic-s9xxx-openwrt/tree/main/router-config#1010-set-the-box-to-boot-from-usbtfsd
> 
> Test whether it can start normally Default ip: `192.168.1.1` Username: `root` Password: `password`
> 
> It is best to connect the device to the `monitor`, and you can see the result by observing the startup code. After the code stops running, press `Enter` on the keyboard to see the `colored banner`

can u send the download link again?
