### ISSUE TITLE
kernel failed to boot when installed on emmc

### ISSUE THREAD

**Issue by Tonho888** [ophub/amlogic-s9xxx-openwrt#379]
i have amlogic s905x (b860h version 1),latest ophub 6.1.9 and 6.1.10 kernel can boot normally on amlogic b860h version 1, but fails to install openwrt on emmc, can only run on sdcard, how to fix this, sir

**Comment by ophub** [comment]
log of failed installation

**Comment by ophub** [comment]
Why do you say the installation failed, what do you see?

**Comment by ophub** [comment]
Then use the 5.15 kernel. No logs don't know why.
