### ISSUE TITLE
关于lede源码的固件编译的问题

### ISSUE THREAD

**Issue by zhuxindong** [ophub/amlogic-s9xxx-openwrt#381]
我想本地编译一个s905l3a的img包，想自行编译进去一些插件，请问是不是只需要用lede的源码编译出 *.rootfs.tar.gz放到指定目录下，再调用本项目中的编译脚本就行了？另外我想咨询一下，编译的过程中是否支持使用make menuconfig

**Comment by ophub** [comment]
有 *.rootfs.tar.gz就可以打包了，除了这一个文件以外其他所需的文件都由make脚本自动下载完成。

make menuconfig是在生成 *.rootfs.tar.gz前，定制它的.config的命令：

**Comment by zhuxindong** [comment]
我如果直接编译lede的库的话，在make menuconfig菜单，编译目标的target应该选什么？arm64的就可以吗？

**Comment by ophub** [comment]
仓库首页最底下有说明
