### ISSUE TITLE
E900V22C 网卡驱动报错

### ISSUE THREAD

**Issue by mir355** [ophub/amlogic-s9xxx-openwrt#383]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: [e.g. S095x3]
 - Model： E900V22C

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 5.15.100]
 - Release: [e.g. lede]

**Describe the bug | 问题描述**
Describe the problem in detail and attach screenshots if necessary.
我在盒子上使用5.1内核的固件，网卡有报错，无法正确加载。更换6.1内核的固件则可以正确加载使用。
![Uploading IMG_20230209_190619.jpg…]()

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-openwrt/blob/c33b8f3aef1fd7166de8f52af122374b80b253a9/amlogic-s9xxx/common-files/rootfs/etc/model_database.conf#L76

5.15的手动加一个u-boot就可以了
