### ISSUE TITLE
wireless dont turn on karnel 5.10.167

### ISSUE THREAD

**Issue by um03** [ophub/amlogic-s9xxx-openwrt#386]
I have a problem with the stable kernel on version 5.10.167 which can't turn on the internal wifi on the s905x device, is there a solution to this problem?

**Comment by mir355** [comment]
I had the same problem and I had a problem that the wired network can’t work in kernel 5.1 too. I try to add driver to recomplie with the kernel 6.1. It has a lot of error. so I give up.

**Comment by esaaprillia** [comment]
it looks like the wifi can be activated I saw this on youtube

https://youtube.com/shorts/3AJs_fB2q7Y?feature=share
