### ISSUE TITLE
Build OpenWrt with ImageBuilder

### ISSUE THREAD

**Issue by Burhan7610** [ophub/amlogic-s9xxx-openwrt#389]
appear a log like this during build on github actions at workflow
Can you help me for fix it, please!

![Capture](https://user-images.githubusercontent.com/125169413/219234473-902c8d8d-ec7a-4b1c-aba5-b47f157292e4.PNG)

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-openwrt/commit/8bd81d9ee0c7acaadee826f8feab18bc72d5d591

https://github.com/ophub/amlogic-s9xxx-openwrt/actions/runs/4190811742/jobs/7264594872

Repaired
