### ISSUE TITLE
Error opkg update

### ISSUE THREAD

**Issue by adisubagja** [ophub/amlogic-s9xxx-openwrt#39]
root@OpenWrt:~# opkg update
Collected errors:
 * opkg_conf_load: Could not lock /var/lock/opkg.lock: Resource temporarily unavailable.
![Screenshot_20210326-143007309](https://user-images.githubusercontent.com/15952175/112597611-e8844b00-8e3f-11eb-9e20-eb8161d2232c.jpg)

So Im Using OpenVPN Connection and getting this
I think this terminal not support openvpn connection and how to fix?

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-openwrt/blob/main/router_config/.config#L417

`luci-app-openvpn`  has been integrated in the firmware, but I don’t know how to use the `openvpn`  plug-in. You can search for how to configure it. I tested `opkg` locally and it can be used normally.

**Comment by adisubagja** [comment]
Im using custom openvpn config using terminal
Like file ovpn & login.txt
at line auth-user-pass put login.txt

like example :
auth-user-pass login.txt

then put username & password in login.txt file

this my method to run openvpn
just type `openvpn file.ovpn &`

i dont know using self config in luci-app-openvpn :( if u have contact like telegram,whatsapp,etc i'll chat to solve this

**Comment by ophub** [comment]
Someone asked how to use this `luci-app-openvpn` plugin before. But I will not use this plugin.

We use BBM in Indonesia, but my mom doesn't let me play mobile phones.

**Comment by adisubagja** [comment]
where u from bro? and you have pc bro?
i think telegram desktop available on pc

**Comment by ophub** [comment]
Telegram cannot be used in Indonesia, we use BBM.
