### ISSUE TITLE
[ rk3328 ] config is missing!

### ISSUE THREAD

**Issue by dimanton1221** [ophub/amlogic-s9xxx-openwrt#391]
![image](https://user-images.githubusercontent.com/116934032/220507556-e47e2738-cdaf-45b3-bdf2-7cf0ee97b704.png)

i can't build openwrt for rk3328

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-openwrt/blob/main/make-openwrt/openwrt-files/common-files/etc/model_database.conf

When making the OpenWrt firmware, find [ the first ] configuration information with the [ same `BOARD` name ] and [ `BUILD` as yes ]
