### ISSUE TITLE
Bug wifi on b860h

### ISSUE THREAD

**Issue by Burhan7610** [ophub/amlogic-s9xxx-openwrt#392]
**Device Information | 设备信息**
 - SOC: s905x
 - Model ZTE B860H

**Armbian Version | 系统版本**
 - Kernel Version: 5.15.94 flippy
 - Release: build with image builder github actions

**Describe the bug | 问题描述**
stb restarts when the enable wireless wifi button is pressed, and wifi remains disabled when stb is on

**Comment by ophub** [comment]
What is the wireless chip, take a picture of the number on the chip and send it

**Comment by erfanrinanda** [comment]
chip s905x

**Comment by erfanrinanda** [comment]
chip rtl8188f
