### ISSUE TITLE
hk1 box刷入emmc后无法使用千兆

### ISSUE THREAD

**Issue by fengyuanluo** [ophub/amlogic-s9xxx-openwrt#394]
如题，使用81+固件刷入emmc，且刷入bl，导致既无法驱动千兆又无法从U盘启动，请问该怎么办？

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/documents/README.cn.md

12.3.2

**Comment by fengyuanluo** [comment]
可是我已经设置了静态ip且在同一网段下无法连接，甚至网线直连也不能使用ip打开luci，这是否可能与我写入emmc时的报错有关？
报错的内容大概是
tar 无法将什么什么指定给uid6xxxx

**Comment by ophub** [comment]
看10.8.2

**Comment by fengyuanluo** [comment]
额，我还是想用

**Comment by fengyuanluo** [comment]
openwrt的啊

**Comment by fengyuanluo** [comment]
刷机的话好像hk1 捅av口时ubt识别不了

**Comment by ophub** [comment]
你先短接刷回安卓，然后再刷op，不要使用线。

你现在写入了主线，所以必须先刷回安卓覆盖回原bootloader

**Comment by fengyuanluo** [comment]
行吧，不过短接可能有点麻烦，我试试

**Comment by fengyuanluo** [comment]
不过之前没写入主线bl也驱动不了网口，所以我才试着写入了主线bl

**Comment by ophub** [comment]
可能你的hk1是个新变种的？以前刷过op吗？

**Comment by fengyuanluo** [comment]
半年前刷过，也没成功，就放弃玩coreelec去了，但coreelec系统限制太大且可玩性低了点

**Comment by fengyuanluo** [comment]
刷那个armbian也没法驱动千兆，且写入emmc后和现在情况差不多

**Comment by fengyuanluo** [comment]
目前测试只有原系统和coreelec驱动成功了

**Comment by ophub** [comment]
那就说明没适配了你的这个新变种的盒子，hk1和x96max都有很多变种。

**Comment by fengyuanluo** [comment]
已经是一年多前买的了，看来应该刷不了op了？

**Comment by ophub** [comment]
用不了
