### ISSUE TITLE
Firmware for Hk1-mini Rk3229?

### ISSUE THREAD

**Issue by Biangkerok32** [ophub/amlogic-s9xxx-openwrt#400]
I have HK1-MINI with rk3229

Which  firmware version must I use 🤔

**Device Information **
 - SOC: [?]
 - Model [ HK1 Mini]
 - Chipshet [RK3229]
 - Processor [Armv7]

All of rochipset will work 🤔

Thanks 🙏

**Comment by ophub** [comment]
not support

**Comment by Biangkerok32** [comment]
> not support

Any idea sir,

**Comment by ophub** [comment]
The existing ones support armv8, not v7
