### ISSUE TITLE
N1刷openwrt_lede_amlogic_s905d_k5.15.100_2023.03.14.img.gz后udpxy不能正常工作

### ISSUE THREAD

**Issue by baowuji** [ophub/amlogic-s9xxx-openwrt#403]
**Device Information | 设备信息**
 - SOC: [e.g. s905d]
 - Model [e.g. N1]

刷的固件
openwrt_lede_amlogic_s905d_k5.15.100_2023.03.14.img.gz

**Describe the bug | 问题描述**
自己安装udpxy后不能正常工作。可以显示运行，但是不能播放组播

**Comment by ophub** [comment]
不能播放的表述等于没说，提示的什么？要收费？要同意协议？要看广告？要女士优先？你提问不说具体情况，大家猜可能是你没开机？还是摄像机忘了开镜头盖了呢？

到lede仓库请教一下怎么用。准确截图或者提供错误日志给他。
