### ISSUE TITLE
no amlogic service 

### ISSUE THREAD

**Issue by murad0522** [ophub/amlogic-s9xxx-openwrt#404]
I compile from a custom OpenWRT build that I repack with this script, lately no almogic service, 
I have 2 devices 905x and 905x3 and all the same, I use this command to compile 

sudo ./make  -b s905x -s 1024

before It was fine, now I don't know why 

another problem 
when I try to update with the offline mode the new img its says no boot partition, but it boots if I burn it to USB 

 - SOC  S095x3 
 - Model HK1

 - Kernel Version: 5.15.100

**Comment by ophub** [comment]
https://github.com/ophub/luci-app-amlogic

# Add luci-app-amlogic
svn co https://github.com/ophub/luci-app-amlogic/trunk/luci-app-amlogic package/luci-app-amlogic

# This plugin can be compiled separately
make package/luci-app-amlogic/compile V=99

# Or integrate this plugin when fully compiling OpenWrt
make menuconfig
# choose LuCI ---> 3. Applications  ---> <*> luci-app-amlogic ----> save
make V=99
