### ISSUE TITLE
移动M301A，s905l2，CW代工，降频到26Mhz写入成功

### ISSUE THREAD

**Issue by champion0117** [ophub/amlogic-s9xxx-openwrt#405]
目前运行正常，给大家一个参考

**Comment by ophub** [comment]
用的哪个dtb和u-boot文件？
拍点盒子的外观照片，底部照片能看到这个盒子的型号标签。

**Comment by ophub** [comment]
好的，谢谢分享。
你测试的选择对应列表里序号`113`的配置，我记录一下。
你有这个盒子的安卓系统没？发个下载链接我转存一份。

**Comment by champion0117** [comment]
链接：https://pan.baidu.com/s/11IBauP9dkFIgFUKwDiCPMw 
提取码：bzs5 
--来自百度网盘超级会员V8的分享
我在写入的时候刷的是在你这下载的MGV2000的固件

**Comment by ramondsq** [comment]
M301A，s905l2，九联代工（应该是），成功U盘启动

U盘启动方法：U盘写入 `openwrt_official_amlogic_s905l2_k5.15.119_2023.07.01.img.gz` 后，修改了 uEnv.txt 文件中的 dtb 为 `meson-gxl-s905l2-x7-5g.dtb` 。U盘插网口旁边的口。用卡针按住底部**按钮**（有一个箭头指向）通电。

目前成功进入系统，连接网线能进入后台，但是尝试写入114到emmc后无法启动

![IMG_7822](https://github.com/ophub/amlogic-s9xxx-openwrt/assets/57244337/5fa23df3-e034-42f7-95d6-81592e61c692)
![IMG_7789](https://github.com/ophub/amlogic-s9xxx-openwrt/assets/57244337/4d17df78-8b12-4621-a4b4-60ab7d6524da)
![IMG_7785](https://github.com/ophub/amlogic-s9xxx-openwrt/assets/57244337/f9ee54de-470a-4ab1-8daa-84d80a481aa8)
![D86550E626478000E44E3A36A50D0C27](https://github.com/ophub/amlogic-s9xxx-openwrt/assets/57244337/8c090daf-9081-4ba6-95d1-c8fc247eeb4e)

**Comment by ophub** [comment]
默认的能启动就使用默认的，为什么要改个别的dtb，你试过改了可行？

**Comment by ramondsq** [comment]
> 默认的能启动就使用默认的，为什么要改个别的dtb，你试过改了可行？

好吧，我看了下默认就是 `meson-gxl-s905l2-x7-5g.dtb` ，相当于是默认配置启动的，被某些教程误导了。

目前是安装提示成功，但是启动一直黑屏。
![image](https://github.com/ophub/amlogic-s9xxx-openwrt/assets/57244337/2db406ae-7a60-44ba-bbb5-b6cb70964350)

**Comment by ophub** [comment]
流览器访问试试。有的盒子没有hdmi输出显示，但可以正常启动

**Comment by ramondsq** [comment]
> 流览器访问试试。有的盒子没有hdmi输出显示，但可以正常启动

浏览器无法访问，没有分配 IP 。

U盘启动的时候是有 HDMI 输出的，然后连接键盘也是可以输入的，但是命令行不会显示输入的内容，并且输入的字符某些也会被吞。

![IMG_7823](https://github.com/ophub/amlogic-s9xxx-openwrt/assets/57244337/46e9e2eb-e92f-421b-b9c9-fda278319b11)

**Comment by ophub** [comment]
选择使用主线

**Comment by ramondsq** [comment]
> 选择使用主线

请问主线指的是使用6.1内核吗？才试了一下7月1号和9号的固件都无法U盘启动

**Comment by ophub** [comment]
哪个内核都可以安装时选择主线。

宝盒插件设置，选择使用bootloader

**Comment by ramondsq** [comment]
> 哪个内核都可以安装时选择主线。
> 
> 宝盒插件设置，选择使用bootloader

我尝试在宝盒插件设置中勾选了**自动写入 bootloader**然后安装114，依旧和之前一样无法启动进入EMMC的系统。
另外就是我依旧没有找到**选择主线**相关选项，还请麻烦能否详细说明一下。
最后就是安装之后现在**插着U盘**的情况下可以自动启动进入U盘的系统，不用按住刷机键，但是**拔掉U盘**的情况下依旧没法启动进入EMMC的系统。
![image](https://github.com/ophub/amlogic-s9xxx-openwrt/assets/57244337/b94bc994-e94a-4abc-aad4-bf9fb7ec29ea)

**Comment by ramondsq** [comment]
试了一下 Armbian ，成功写入 EMMC 并启动，用的 [Armbian_23.08.0_amlogic_s905l2_lunar_5.15.119_server_2023.07.01.img.gz](https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_lunar_save_2023.07/Armbian_23.08.0_amlogic_s905l2_lunar_5.15.119_server_2023.07.01.img.gz)

**Comment by ophub** [comment]
上面这个盒子的贡献者使用的113，你选择114有什么特殊考虑？试试先刷他分享的安卓

**Comment by ramondsq** [comment]
> 上面这个盒子的贡献者使用的113，你选择114有什么特殊考虑？试试先刷他分享的安卓

1. 选择114是因为看到对应型号 M301A 在里面。刚才又试了一下113配置，无法启动。
![image](https://github.com/ophub/amlogic-s9xxx-openwrt/assets/57244337/bf5236ee-87f0-4a97-a934-22404850f1d4)

2. 试了一下贡献者 [champion0117](https://github.com/champion0117) 提供的线刷包 [android_tv_m301a_s905l2.tar.xz](https://github.com/ophub/kernel/releases/download/tools/android_tv_m301a_s905l2.tar.xz) ，工具 USB Burning Tool V2.1.2，无法刷入。但是在 [恩山](https://www.right.com.cn/forum/forum.php?mod=viewthread&tid=4108964) 上找的 [固件](https://pan.baidu.com/s/1rQBCKrJG0Mj-MHmQDyTjMw) （提取码：uvkb）可以正确刷入并启动。
![image](https://github.com/ophub/amlogic-s9xxx-openwrt/assets/57244337/8ab37ab6-0a89-4c57-9aff-a2c5beff7cbd)

**Comment by ophub** [comment]
不能刷他分享的安卓，可能机器不同，魔百和各地运营商出的可能不同。找可用的安卓9系统刷。

**Comment by fujintcc** [comment]
我用的也是M301A OPENWRT写入 EMMC也是失败，但是U盘可以启动，Armbian 成功写入 EMMC 并启动，不知道是哪里问题

**Comment by liuyi265** [comment]
@ramondsq  我的盒子s905l2 也是插网线没反应，界面输入字符不显示    请问最后是怎么解决的

**Comment by champion0117** [comment]
好久没折腾这个盒子了，当时写这个issues时光记得我降频了，忘了我是修改了分区信息的，安卓固件当时也试过很多，大部分写入都没什么问题，还没搞定的可以尝试：
        BOOT=512
        BLANK1=68
        BLANK2=152

**Comment by liuyi265** [comment]
@champion0117  不知道在哪里降频 或者在哪里修改你发的这几个参数

**Comment by liuyi265** [comment]
有现成的dbt文件么

**Comment by txhtxh11** [comment]
怎么降频，必须降频吗

**Comment by FoureyedApple** [comment]
盒子又翻出来做打印服务器，所以研究了一下这个wifi，现在的meson-gxl-s905l2-x7-5g.dtb貌似不能启动，用meson-gxl-s905l2-ipbs9505.dtb修改了一下，emmc 50 MHz工作正常，网卡(rtl8822bs)25 MHz驱动成功。
直接写入EMMC很大概率启动不了，需要修改分区：
BOOT=512
BLANK1=68
BLANK2=152

小白一个，不知道DTB改得对不对，反正我能用，仅供参考
瞎捣鼓的，稳定性有待测试

完整的DTB附上

`[    2.349061] meson-gx-mmc d0072000.mmc: Got CD GPIO
[    2.350053] meson-gx-mmc d0074000.mmc: allocated mmc-pwrseq
[    2.518354] mmc2: new HS200 MMC card at address 0001
[    2.519227] mmcblk2: mmc2:0001 H8G4a� 7.28 GiB
[    2.524600]  mmcblk2: p1 p2 p3 p4
[    2.526363] mmcblk2boot0: mmc2:0001 H8G4a� 4.00 MiB
[    2.531624] mmcblk2boot1: mmc2:0001 H8G4a� 4.00 MiB
[    2.536335] mmcblk2rpmb: mmc2:0001 H8G4a� 4.00 MiB, chardev (236:0)
[    4.419618] meson-gx-mmc d0070000.mmc: allocated mmc-pwrseq
[    4.460364] meson-gx-mmc d0070000.mmc: card claims to support voltages below defined range
[    4.948148] mmc0: Skipping voltage switch
[    4.968352] mmc0: new high speed SDIO card at address 0001
[    5.595596] BTRFS: device label EMMC_ROOTFS1 devid 1 transid 51 /dev/mmcblk2p2 (179:2) scanned by mount (312)
[    5.604391] BTRFS info (device mmcblk2p2): first mount of filesystem bc4b02cb-4794-4fc6-86d1-256bbd28458a
[    5.612733] BTRFS info (device mmcblk2p2): using crc32c (crc32c-generic) checksum algorithm
[    5.635931] BTRFS info (device mmcblk2p2): enabling ssd optimizations
[    5.638585] BTRFS info (device mmcblk2p2): turning on async discard
[    5.644808] BTRFS info (device mmcblk2p2): enabling free space tree
[    5.651012] BTRFS info (device mmcblk2p2): use zstd compression, level 6
[   18.824569] rtw_8822bs mmc0:0001:1: Firmware version 27.2.0, H2C version 13
[   19.576070] BTRFS: device label EMMC_ROOTFS2 devid 1 transid 9 /dev/mmcblk2p3 (179:3) scanned by block (864)
[   19.589312] BTRFS info (device mmcblk2p3): first mount of filesystem b11737b3-7dec-4060-8046-4ce3edba7d59
[   19.597931] BTRFS info (device mmcblk2p3): using crc32c (crc32c-generic) checksum algorithm
[   19.615049] BTRFS info (device mmcblk2p3): enabling ssd optimizations
[   19.617625] BTRFS info (device mmcblk2p3): turning on async discard
[   19.623883] BTRFS info (device mmcblk2p3): enabling free space tree
[   19.631888] BTRFS: device label EMMC_SHARED devid 1 transid 13 /dev/mmcblk2p4 (179:4) scanned by block (864)
[   19.641110] BTRFS info (device mmcblk2p4): first mount of filesystem 92baefa1-c9dc-43a8-9217-755e9ba4db46
[   19.649354] BTRFS info (device mmcblk2p4): using crc32c (crc32c-generic) checksum algorithm
[   19.699782] BTRFS info (device mmcblk2p4): enabling ssd optimizations
[   19.702471] BTRFS info (device mmcblk2p4): turning on async discard
[   19.708697] BTRFS info (device mmcblk2p4): enabling free space tree
`

[meson-gxl-s905l2-M301A.zip](https://github.com/user-attachments/files/22556229/meson-gxl-s905l2-M301A.zip)
