### ISSUE TITLE
mgv2000_jz_iptv_hunan，U盘启动后找不到EMMC

### ISSUE THREAD

**Issue by tcanong** [ophub/amlogic-s9xxx-openwrt#406]
mgv2000_jz_iptv_hunan，U盘启动后找不到EMMC

root@armbian:~# armbian-ddbr
[ STEPS ] Welcome to use the eMMC system backup/restore service.
[ INFO ] The device name: [ Amlogic Meson GXL (S905L2) X7 5G Tv Box ]
[ ERROR ] The eMMC storage not found in this device!

root@armbian:~# df
Filesystem     1K-blocks    Used Available Use% Mounted on
udev              275384       0    275384   0% /dev
tmpfs              82296    2816     79480   4% /run
/dev/sda2        2507080 1282908   1207788  52% /
tmpfs             411472       0    411472   0% /dev/shm
tmpfs               5120       4      5116   1% /run/lock
/dev/zram2        397952      80    369072   1% /tmp
/dev/sda1         257071  103835    153236  41% /boot
/dev/zram1         49560     760     45216   2% /var/log
tmpfs              82292       0     82292   0% /run/user/0

**Device Information | 设备信息**
 - SOC: [S905L2-B]
 - Model [MGV2000_jz_iptv_hunan]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 5.15.104]
 - Release: [Armbian_23.05.0_amlogic_s905l2_bullseye_5.15.104_server_2023.03.23.img.gz]

**Comment by ophub** [comment]
这个用的不是emmc吗？nand？
