### ISSUE TITLE
8822cs无线网卡

### ISSUE THREAD

**Issue by 1520316653** [ophub/amlogic-s9xxx-openwrt#409]
大佬我想问一下，8822cs这个无线网卡，驱动不是集成到内核里的吗，为什么我刷的f大和haiibo网盘里的安装包，依然没有WiFi。
也尝试过更换.5.15.104内核但是依然没有WiFi
但是大佬的主页下载的就能驱动WiFi，不知道如何实现的。（ophub大佬的技术还是牛逼）。尝试用你的dtb文件依然不行，也尝试过本地自编译了，发现技术不到位。没有成功。
那个大佬我想你能不能也出一个比较全的版本，就像那种有istore，agron主题这种，全功能的版本，怕麻烦的话吗，可以一个月或者几个月一更新。跪谢ophub大佬。
机型是那个鲸鱼盒子，s905x3的。rtl8211f+8822cs无线网卡。

**Comment by ophub** [comment]
8822cs有的人反馈能用，有的不能用，但是我用的是f大的内核编译的。编译配置文件和打包过程都是开源的，你可以看到全部资料和过程，所以我没有黑科技，只是偶然事件，你在armbian的问题交流区可以看到很多人反馈不能用。
