### ISSUE TITLE
X96Max_Plus_A100 issue

### ISSUE THREAD

**Issue by ashkib** [ophub/amlogic-s9xxx-openwrt#418]
**Device Information
 - SOC: S095x3
 - Model [X96Max_Plus_A100] 
 - 4GB RAM and 32GB emmc 
 - WIFI AM7256
 - LAN 100M
 
Openwrt_official_amlogic_s905x3_k5.15.106_2023.04.11.img.gz

**Describe the bug 
Dear Sir, thank you for your effort and support
I have X96Max_Plus_A100 box, It doesn't work with default USB boot, No lan ip recived or luci 

If I use meson-sm1-sei610.dtb I get lan IP and wifi I can get it boot using Q1 dtb also 
If I use install to emmc I have balck screen, no Ethernet  IP Just dead device in both cases

Could you please help me to install Openwrt on emmc ?
Kind regards

Board photo 
https://photos.app.goo.gl/2yGYDmMtH42WBSK66

Network properties
https://photos.app.goo.gl/Kp7QmWa9HfnGJpEx8

**Comment by ophub** [comment]
```
armbian-install -m yes
523
```

**Comment by ashkib** [comment]
Thank you ophub for your answer
Could you please help me by explaining more details about the steps ?

**Comment by ophub** [comment]
I answered several warehouse questions at the same time, but I made a mistake. You are using the OP system, and the commands above are from Armbian.

In the menu of the openwrt system, select System > amlogic service > Plugin settings > Use `Bootloader`, and then install the OP to use the mainline u-boot

**Comment by ashkib** [comment]
thank you for your support
unfortunately still not booting from emmc after checking write boot loader
openwrt_official_amlogic_s905x3_k5.15.106_2023.04.13.img.gz

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/issues/779

This is a previous test post, openwrt and armbian system startup requirements are the same.

**Comment by ophub** [comment]
https://github.com/ophub/kernel/releases/tag/tools
a100

The network card cannot be recognized, you may need to replace the Android system first, and then flash armbian

**Comment by ashkib** [comment]
I flashed the android rom from the link 
used the dtb from the link above (Q1) to boot from usb , both lan and wifi works
activated boot loader writing and installed openwrt on emmc using (device 515 ) in the list
emmc success but with 2 GB ram only of 4GB

Thank you for your help 
You can close the issue now

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/build-armbian/documents

look at: 12.12
copy u-boot

**Comment by ashkib** [comment]
ok thank you so much ..
I will try it and update you. 

Could you please recommend the most compatible dtb file for my tv box for emmc install?
https://photos.app.goo.gl/2yGYDmMtH42WBSK66

SOC: S095x3
Model X96Max_Plus_A100
4GB RAM and 32GB emmc
WIFI AM7256
LAN 100M

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-openwrt/blob/cf85b0f4ba79acb5ea89746566a81c2e919b52eb/make-openwrt/openwrt-files/common-files/etc/model_database.conf#L153

523

**Comment by ashkib** [comment]
523 boots and works from USB but gave me black screen after emmc install 
Could you guide me to the right steps to install openwrt using 523 dtb?

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-openwrt/tree/main/make-openwrt/documents

**Comment by ashkib** [comment]
Could you please be more specific
example easy steps to follow 1,2,3...

**Comment by hillz2** [comment]
> Could you please be more specific example easy steps to follow 1,2,3...

I also have X96 Max Plus running openwrt but the LAN port doesn't work, does yours work ?
