### ISSUE TITLE
Samba setup

### ISSUE THREAD

**Issue by riyuejz** [ophub/amlogic-s9xxx-openwrt#42]
can you help me to set it up .. i'm using hdd ntfs partition .. so I can read and write how to do it..
![Screenshot_2021-03-28-19-04-52-962_com android chrome](https://user-images.githubusercontent.com/50128745/112751634-32646100-8ff9-11eb-858a-86fd9532c4e8.jpg)
![Screenshot_2021-03-28-19-04-38-236_com android chrome](https://user-images.githubusercontent.com/50128745/112751640-355f5180-8ff9-11eb-8ffb-95d0df0a2d2e.jpg)
![Screenshot_2021-03-28-19-10-19-942_com termux](https://user-images.githubusercontent.com/50128745/112751657-460fc780-8ff9-11eb-9a9b-1ae6098763fe.jpg)

**Comment by ophub** [comment]
![1](https://user-images.githubusercontent.com/68696949/112755756-baa42f80-9014-11eb-81cc-2cf6c7b42026.png)

**Comment by riyuejz** [comment]
![Screenshot_2021-03-29-02-58-16-186_com lonelycatgames Xplore](https://user-images.githubusercontent.com/50128745/112766157-ab37dd00-903a-11eb-9a5e-5e699a1cd677.jpg)
Invalid SMB status: STATUS_ACCESS_DENIED

**Comment by ophub** [comment]
https://forum.openwrt.org/t/how-i-got-samba4-working-for-me/68633
https://openwrt.org/docs/guide-user/services/nas/samba_configuration
