### ISSUE TITLE
x88king没有tf卡没有合适dtb启动文件

### ISSUE THREAD

**Issue by qili01** [ophub/amlogic-s9xxx-openwrt#422]
x88king    晶晨s922x  4+128 
测试gt king  am6   的dtb文件启动不了

**Comment by ophub** [comment]
meson-g12b-odroid-n2.dtb
meson-g12b-ugoos-am6.dtb

你试试这2个dtb

**Comment by qili01** [comment]
> meson-g12b-odroid-n2.dtb meson-g12b-ugoos-am6.dtb
> 
> 你试试这2个dtb

试过不行
