### ISSUE TITLE
mgv2000更新内核失败

### ISSUE THREAD

**Issue by JayceeNee** [ophub/amlogic-s9xxx-openwrt#426]
**Device Information | 设备信息**
 - SOC: s905l2
 - Model mgv2000

**Armbian Version | 系统版本**
 - Kernel Version: 5.15.109-ophub
 - Release: OpenWrt SNAPSHOT r22711-4fa9ec125a / LuCI Master git-23.104.28202-588c6a1

**Describe the bug | 问题描述**
在线更新内核失败，提示[%1B[1;91m Error %1B[0m] Missing [ tar ] in OpenWrt firmware, unable to update kernel，但系统已有tar

![屏幕截图 2023-05-05 190101](https://user-images.githubusercontent.com/118952014/236441460-48c08730-b046-4438-ac47-6b72f69004bc.png)
![屏幕截图 2023-05-05 190219](https://user-images.githubusercontent.com/118952014/236441478-86414841-e210-4953-84c3-4c627e146cdf.png)

**Comment by JayceeNee** [comment]
尝试完整更新全系统，提示 The device name is empty and cannot be recognized.手动上传更新情况相同
![image](https://user-images.githubusercontent.com/118952014/236443165-cb696830-6e6b-4e05-8a55-423d82dad055.png)

**Comment by ophub** [comment]
你的界面不正常，怎么重复显示2次内核版本呢？这几个按钮不要一起点，只执行一个。

现在切换到手动上传更新那个里，把看到的这些tar.gz文件都删了，重启一下，重新在线下载更新

**Comment by JayceeNee** [comment]
删除并重启后 在线更新情况依旧
![image](https://user-images.githubusercontent.com/118952014/236496174-f0675a1a-efc5-427d-906d-9e66bfe641b9.png)

**Comment by JayceeNee** [comment]
返回如图
![image](https://user-images.githubusercontent.com/118952014/236599550-c998e252-762d-4f10-9926-737c40f4294a.png)

**Comment by ophub** [comment]
正常情况下他应该这样显示，你的显示双重，不知道是不是你的luci皮肤导致的，你在系统里切换个别的皮肤看看。

![Snip20230506_5](https://user-images.githubusercontent.com/68696949/236610407-5a938b9a-3ee9-4b16-8c1e-1595369c94da.png)
