### ISSUE TITLE
Openvpn and Samba

### ISSUE THREAD

**Issue by lynxnexy** [ophub/amlogic-s9xxx-openwrt#43]
can you add back the openvpn & samba v3.x package for the next update in the lede version

**Comment by ophub** [comment]
```
CONFIG_PACKAGE_luci-app-openvpn=y
CONFIG_PACKAGE_luci-app-openvpn-server=y
CONFIG_PACKAGE_luci-app-samba4=y
```

All repository have been added for you.
`samba4` should contain `1/2/3` downwards.
