### ISSUE TITLE
关于ct2000的内核

### ISSUE THREAD

**Issue by JamesLiu0802** [ophub/amlogic-s9xxx-openwrt#431]
请问在使用lede的openwrt时，如果在U盘的是6.1内核的openwrt，现在能够刷入emmc了吗？

**Comment by JamesLiu0802** [comment]
看了armbian的issue，明白了

**Comment by ophub** [comment]
kernel_dev里面的都可用，5.10， 6.1都可以，打了补丁了。

**Comment by JamesLiu0802** [comment]
好的，谢谢大佬解答
