### ISSUE TITLE
ct2000 指定内核无效

### ISSUE THREAD

**Issue by OwO-GitHub** [ophub/amlogic-s9xxx-openwrt#434]
**Device Information | 设备信息**
 - SOC: S922X
 - Model CT2000

**OpenWrt Version | 系统版本**
 - Kernel Version: ALL
 - Release: immortalwrt

**Describe the bug | 问题描述**
Action编译的时候不管是指定flippy 还是stable，最后下载内核的时候，总是会下载dev内核。
![image](https://github.com/ophub/amlogic-s9xxx-openwrt/assets/79355200/5267532a-d92d-4e7e-a905-964890cd3f77)
![image](https://github.com/ophub/amlogic-s9xxx-openwrt/assets/79355200/d6e5ea6a-72c4-474d-9bcf-1bc4041c6ef1)

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-openwrt/blob/main/make-openwrt/openwrt-files/common-files/etc/model_database.conf

在KERNEL_TAGS里指定为 stable, 5.x.y, 6.x.y 时可以被自选 tags 替换。

指定为 rk3588, flippy, dev 时不可被替换。

**Comment by OwO-GitHub** [comment]
好的，知道了谢谢。
