### ISSUE TITLE
UNT400G1安装到EMMC后无法启动

### ISSUE THREAD

**Issue by KongGuoguang** [ophub/amlogic-s9xxx-openwrt#438]
系统版本：openwrt_lede_amlogic_s905l3-unt400g1_k6.1.28_2023.05.15

U盘启动成功后使用晶晨宝盒安装到EMMC，拔掉U盘断电重启后无法进入系统

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/issues/1277

每个设备在初次接触时，先在首页点设备的名称进入当时测试的帖子，先看看之前大家的使用方法。
