### ISSUE TITLE
5.15 flippy 内核打包出错

### ISSUE THREAD

**Issue by OwO-GitHub** [ophub/amlogic-s9xxx-openwrt#439]
打包选择 5.15 flippy内核出错，多次尝试都是这样。试过其他版本内核没事

![image](https://github.com/ophub/amlogic-s9xxx-openwrt/assets/79355200/ffe259d5-42a6-436a-8109-242c417d032e)

**Comment by ophub** [comment]
可能是mac电脑的tar压缩和linux不同导致的，我把flippy这个tags下的全部内核都在linux重新打包了一遍，已经更新了，你再试试。

**Comment by OwO-GitHub** [comment]
> 可能是mac电脑的tar压缩和linux不同导致的，我把flippy这个tags下的全部内核都在linux重新打包了一遍，已经更新了，你再试试。
> 
> [kernel_flippy](https://github.com/ophub/kernel/releases/tag/kernel_flippy)下的5.15.y和6.1.y是我转存的f大分享的内核；其中5.4.y和5.10.y是我转存的[breakings](https://github.com/breakings/OpenWrt/releases/tag/kernel_stable)制作的内核。

测试已经可以正常打包了
