### ISSUE TITLE
AdGuardHome + Luci

### ISSUE THREAD

**Issue by lynxnexy** [ophub/amlogic-s9xxx-openwrt#44]
how do I add this package to the build script ...
1. https://github.com/AdguardTeam/AdGuardHome

2. https://github.com/rufengsuixing/luci-app-adguardhome

**Comment by ophub** [comment]
Add to diy-part2.sh:
`svn co https://github.com/rufengsuixing/luci-app-adguardhome/trunk  package/lean/luci-app-ssr-plus`


Add to .config:
`CONFIG_PACKAGE_luci-app-adguardhome=y`
