### ISSUE TITLE
S905X-T95 cannot access Web Gui Luci ?

### ISSUE THREAD

**Issue by Biangkerok32** [ophub/amlogic-s9xxx-openwrt#442]
**Device Information | 设备信息**
 - SOC: [S095x-t95]

**OpenWrt Version | 系统版本**
 - Kernel Version: [last]
 - Release: [lede/immortalwrt]

**Describe the bug | 问题描述**
I'm try use last build lede and immortal with last kernel,but I'm can't access luci web GUI?
I can access ssh work it.

I try enter "ps -w" on ssh terminal,but i see "usr/sbin/uhttpd -f -h /www -r HOSTNAME -x /cgi-bin -t 60 -T 30 -k 20 -A 1 -n 3 -N 100 -R" without "0.0.0.0:80"

How to fix that 🤔

Thanks.

**Comment by ophub** [comment]
Screenshot of the complete interface of the terminal

**Comment by ophub** [comment]
```
rm -rf /tmp/luci-*
sync
reboot
```

**Comment by Biangkerok32** [comment]
It's fix now . 👍

I'm open Luci Web GUI with other browser 

I thinks error from my browser cache.

![IMG_20230612_192511_820](https://github.com/ophub/amlogic-s9xxx-openwrt/assets/48493593/1a3616e2-10ec-4b96-83c4-f49afcc9d5bd)
