### ISSUE TITLE
23.03.0-rc2

### ISSUE THREAD

**Issue by esaaprillia** [ophub/amlogic-s9xxx-openwrt#447]
@ophub 

please add armsr already released

https://downloads.openwrt.org/releases/23.05.0-rc2/targets/armsr/armv8/

**Comment by ophub** [comment]
rc1-rc5 is beta

**Comment by esaaprillia** [comment]
> rc1-rc5 is beta

yes i know that but it needs to be added urgently. replace the armvirt target with armsr and it will be a different target and I see that the armsr target must be separated from armvirt

**Comment by OwO-GitHub** [comment]
immortal fw4 装上之后 防火墙设置里不显示  fullcone nat1的选项

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-openwrt/commit/677d60db60523aadbed985cc2ad8a886f6e6c040

添加这个测试版选项了。

**Comment by esaaprillia** [comment]
@ophub 
Thanks

**Comment by esaaprillia** [comment]
@ophub 

```
[ STEPS ] Start adding custom files...
[ INFO ] [ files ] directory status: total 4
drwxr-xr-x 3 runner docker 4096 Jun 29 19:25 etc
[ STEPS ] Start building OpenWrt with Image Builder...
Profile "Default" does not exist!
Use "make info" to get a list of available profile names.
make[1]: *** [Makefile:236: _check_profile] Error 1
make: *** [Makefile:258: image] Error 2
```

**Comment by esaaprillia** [comment]
maybe change make image PROFILE="Default" to make image PROFILE=""

**Comment by esaaprillia** [comment]
there is no default profile in armsr anymore

**Comment by esaaprillia** [comment]
maybe you made a change but you didn't try it. I already told you this must be separated armvirt and armsr

**Comment by esaaprillia** [comment]
@ophub 

i saw your change and it solved the problem. i will close this

**Comment by esaaprillia** [comment]
Ping @ophub 

this must be replaced

```sed -i "s|iw |ipconfig |g" ${wireless_mac80211}```

to

```sed -i 's|iw dev "$wdev" del |#iw dev "$wdev" del |g' ${wireless_mac80211}```


I've tried it doesn't change. can you change this
