### ISSUE TITLE
大兄弟，很牛逼

### ISSUE THREAD

**Issue by BourneMars** [ophub/amlogic-s9xxx-openwrt#45]
GTKING GKINGPRO 不可能用来openwrt . 我的GTKING 刚坏 600多一个。 
买R3300-M  准备openwrt 做个单臂路由，科学上网使用。  
什么时候有时间也给做一个openwrt . 感谢。
Spec:

ro.product.model=R3300-M
ro.product.brand=BesTV

SOC:S905M-B

WIFI:RT8189ETV

EMMC:4GB

RAM:1GB

 

2 USB（1 microusb port） and 1 TF card slot.

https://forum.armbian.com/topic/16952-need-help-to-run-armbian_2010_arm-64_bionic_current_590-on-a-s905m-b-box/

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-openwrt/blob/main/amlogic-s9xxx/amlogic-dtb/meson-gxbb-p201.dtb

`Amlogic s905m STB`  can try to use this dtb file, first test and use it in `USB`.

Are you Chinese? Almost all resources of this repo are collected from Chinese websites. You should understand `flippy`, I'm just his porter.
