### ISSUE TITLE
S905x3 HK1 hardware 4GB membory, but Openwrt only shows 2GB

### ISSUE THREAD

**Issue by n1019ws** [ophub/amlogic-s9xxx-openwrt#450]
![圖片](https://github.com/ophub/amlogic-s9xxx-openwrt/assets/137037428/03417c8f-b8eb-4038-b9c0-c3f41cd4ae82)
Sorry again, how to fix this?

**Comment by ophub** [comment]
use mainline-uboot

**Comment by n1019ws** [comment]
![圖片](https://github.com/ophub/amlogic-s9xxx-openwrt/assets/137037428/88db60c3-fee8-42c7-8e5c-aa556f09d259)
Thanks again!
