### ISSUE TITLE
SmartLabs SML-5442TW

### ISSUE THREAD

**Issue by WallcroftUK** [ophub/amlogic-s9xxx-openwrt#451]
![image](https://github.com/ophub/amlogic-s9xxx-openwrt/assets/122221257/378e0b5e-39e1-4182-b2f2-a4f189744399)

is it possible to install it on this devices to emmc ?

**Comment by ophub** [comment]
Send screenshots of the results of these three commands. There is currently no installation option for your device, you can add installation options according to your test situation.
```
cat /boot/uEnv.txt
cat /etc/flippy-openwrt-release
ls -l /boot/u-boot*
```

**Comment by WallcroftUK** [comment]
![image](https://github.com/ophub/amlogic-s9xxx-openwrt/assets/122221257/abd8eb00-662e-437f-98c4-dda1ec426c9a)
![image](https://github.com/ophub/amlogic-s9xxx-openwrt/assets/122221257/8db38ab3-8953-409c-a813-1d5db427b955)
![image](https://github.com/ophub/amlogic-s9xxx-openwrt/assets/122221257/c71a7ace-4949-4a7e-a360-6e2b1b9f363b)
 here

**Comment by WallcroftUK** [comment]
i have SML-5442TW openwrt installed on sdcard i must edit uENV.txt to set my ddt

**Comment by WallcroftUK** [comment]
meson-gxl-s905d-sml5442tw.dtb

**Comment by WallcroftUK** [comment]
and if i can ask you guys about one thing 
if its possible to install k8s on device :D

**Comment by WallcroftUK** [comment]
the thing is only this version of armbian work for me i tried latest armbian older armbian and nothing and after try of this img it actually booted :D and works

**Comment by WallcroftUK** [comment]
and other thing wlan is not found no wifi even when this device have BT and Wifi

**Comment by WallcroftUK** [comment]
I booted from sdcard and only working is your image of openwrt but if I wanted same way boot armbian it stuck at something

**Comment by WallcroftUK** [comment]
Where should I search ? Sorry for that question

**Comment by WallcroftUK** [comment]
found it :D

**Comment by ophub** [comment]
Post the screenshot of the newly downloaded 6.1.36 interface after startup.
```
cat /etc/ophub-release
ls -l /boot/u-boot*
```


Installation method: armbian-install, select `104`

**Comment by 07510480632** [comment]
cat /boot/uEnv.txt
cat /etc/flippy-openwrt-release
ls -l /boot/u-boot*

**Comment by pospa1** [comment]
Hi, can someone help me with boot Armbian on SML-5442TW? Im not able to boot it from sd card... always boot into stock firmware.
