### ISSUE TITLE
Please add support for Akari AX512 S905x

### ISSUE THREAD

**Issue by hillz2** [ophub/amlogic-s9xxx-openwrt#456]
Hi, please add support for akari AX512 box (s905x) I have the original android firmware (*.img) for this box if you need it. Let me know and I'll upload it for you.

![a](https://github.com/ophub/amlogic-s9xxx-openwrt/assets/25127225/1b1f1fa1-7776-4205-9aed-f35ba73dcffb)

**Comment by ophub** [comment]
Use the existing s905x firmware to test

**Comment by hillz2** [comment]
I have, and have tried several s905x dtbs, so far no dtb works for the box. Openwrt doesn't boot up

**Comment by ophub** [comment]
try 5.15.y

**Comment by zhz89512021** [comment]
It may be an accidental error during compilation, this image is still working properly.
https://github.com/zhz89512021/amlogic-s9xxx-openwrt/releases/tag/OpenWrt_immortalwrt_save_2023.07

**Comment by hillz2** [comment]
@zhz89512021 which kernel should I download for AX512?

**Comment by zhz89512021** [comment]
![image](https://github.com/ophub/amlogic-s9xxx-openwrt/assets/87250017/0f5f8b15-9da7-4c13-8114-8d251cacbf0e)
6.1.38 on my device works will.

**Comment by zhz89512021** [comment]
> @zhz89512021 which kernel should I download for AX512?

![image](https://github.com/ophub/amlogic-s9xxx-openwrt/assets/87250017/998681c7-c4b4-4477-8f31-6dc5606671dd)
6.1.38 on my device works well

**Comment by hillz2** [comment]
@zhz89512021 does everything else work like wifi and Ethernet?

**Comment by zhz89512021** [comment]
> @zhz89512021 does everything else work like wifi and Ethernet?

it works well on my device
(my device doesn't have wifi,you can try it)

**Comment by ophub** [comment]
@zhz89512021 

Hello, please share the configuration information you're using:

`cat /etc/flippy-openwrt-release`

**Comment by hillz2** [comment]
> @zhz89512021
> 
> Hello, please share the configuration information you're using:
> 
> `cat /etc/flippy-openwrt-release`

I have tried @zhz89512021 openwrt build for Akari AX512 but it still doesn't boot up, @zhz89512021 are you sure https://github.com/zhz89512021/amlogic-s9xxx-openwrt/releases/tag/OpenWrt_immortalwrt_save_2023.07 is running well for Akari AX512 ? I'm referring to this box https://www.androidtv-guide.com/pay-tv-provider/xl-axiata-xl-home-box-dv8252/

**Comment by allentd** [comment]
> > @zhz89512021
> > Hello, please share the configuration information you're using:
> > `cat /etc/flippy-openwrt-release`
> 
> I have tried @zhz89512021 openwrt build for Akari AX512 but it still doesn't boot up, @zhz89512021 are you sure https://github.com/zhz89512021/amlogic-s9xxx-openwrt/releases/tag/OpenWrt_immortalwrt_save_2023.07 is running well for Akari AX512 ? I'm referring to this box https://www.androidtv-guide.com/pay-tv-provider/xl-axiata-xl-home-box-dv8252/

Hi, how do we boot from SD card or USB on these official Android TV?
