### ISSUE TITLE
s905x3 最近編譯的 6.1 kernel 很容易 reboot 失敗

### ISSUE THREAD

**Issue by xgmq** [ophub/amlogic-s9xxx-openwrt#466]
**Device Information | 设备信息**
 - SOC: [ S095x3 ]
 - Model [ HK1 x96max x96air ]

**OpenWrt Version | 系统版本**
 - Kernel Version: [ 6.1 ]
 - Release: [ lede ]

**Describe the bug | 问题描述**
一直都是用 lede編譯 kernel 選 6.1，在三台機器( HK1 x96max x96air )上每天定時reboot都沒問題。
六月底編譯編譯過一次 6.1.31-flippy-83+ ，也是正常的。

八月初編譯的 6.1.42 開始，一直到八月中編譯的 6.1.44，都有隨機reboot失敗的問題。flippy跟ophub的kernel都試過，只要選6.1 kernel，頻率大概是reboot 5 次 會有 1 次失敗。

所以判斷 六月底到八月初這段時間 6.1 kernel 有東西可能更動了，造成隨機的reboot失敗。

目前kernel選5.4，新編譯出來的 Kernel: 5.4.253-ophub，reboot經過上百次測試是正常的。

**Comment by ophub** [comment]
s905x3是个特例，flippy曾经为这个soc写了一个专用的reboot，你可以试试，覆盖同名文件

https://github.com/unifreq/openwrt_packit/blob/master/files/s905x3/reboot

**Comment by kousyougi** [comment]
測試有效
