### ISSUE TITLE
有支持新魔百和hm201的固件么

### ISSUE THREAD

**Issue by BailOrgana** [ophub/amlogic-s9xxx-openwrt#467]
看起来cpu是S905L的数讯代工有复位键的那款
![0821](https://github.com/ophub/amlogic-s9xxx-openwrt/assets/30749673/561ad81b-420a-40b2-92c2-e01317bab141)
![eb079231727ceb8c371cf0bc1caf538](https://github.com/ophub/amlogic-s9xxx-openwrt/assets/30749673/f050d549-bf1c-4001-a0df-06d83ae8f9e4)
![b42917311c1c090190fcf21fc5979cf](https://github.com/ophub/amlogic-s9xxx-openwrt/assets/30749673/012fd9e9-98a2-43aa-b773-3dca2d99b8d9)

**Comment by ophub** [comment]
目前没有测试反馈，你可以测试下现有的固件。

**Comment by hehh2001** [comment]
> 目前没有测试反馈，你可以测试下现有的固件。
首先感谢大佬所做的工作！借楼请教您一个问题，我有两个3399设备，一台AM40和一台华北工控的板子，我有个需求是想利用其中一个板子跑聚合路由系统openmptcp，官网上对这两个板子并没有适配，看了一下也是基于op的，打算自行编译，能给一些建议和注意事项吗？

**Comment by ophub** [comment]
忧郁不决可以问一下chatgpt
