### ISSUE TITLE
Odroid N2+ total memory detected less than physical

### ISSUE THREAD

**Issue by amirulshukry** [ophub/amlogic-s9xxx-openwrt#470]
**Device Information | 设备信息**
 - SOC: s922x
 - Model: Odroid N2+ with 4Gb RAM

 - Kernel Version: 6.1.50-ophub
 - Release: Armbian (23.08.0-trunk) aarch64 

**Describe the bug | 问题描述**
Physical RAM is 4GB but only 1.9GB available
amirul@odroid:~$ free -h
               total        used        free      shared  buff/cache   available
Mem:           1.9Gi       1.3Gi       186Mi        78Mi       546Mi       580Mi
Swap:          973Mi        47Mi       925Mi

**Comment by ophub** [comment]
enable u-boot

**Comment by amirulshukry** [comment]
How do I enable u-boot?

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/documents

12.12

**Comment by amirulshukry** [comment]
ok thanks
