### ISSUE TITLE
How do you update the firmware that's installed on the EMMC ?

### ISSUE THREAD

**Issue by hillz2** [ophub/amlogic-s9xxx-openwrt#471]
I have openwrt installed on the X96 Max Plus EMMC and I'm wondering if it's safe to just upload another *.img file to the **Manually Upload Update** page to update the firmware, can I just do this to update my openwrt fimrware on the EMMC ? I'm asking this because I'm afraid I'll brick my device if I just go ahead and try it.  If I can't do this, then how should I update the openwrt firmware installed on the EMMC?

![2023-09-03-192406_1920x984_scrot](https://github.com/ophub/amlogic-s9xxx-openwrt/assets/25127225/14b348e3-981f-431b-905b-2ca6726cc39a)

**Comment by ophub** [comment]
If you're worried, don't update.
