### ISSUE TITLE
希望能够编译支持tvi3315a的openwrt

### ISSUE THREAD

**Issue by sehczaa** [ophub/amlogic-s9xxx-openwrt#473]
大佬你的另一个仓库armbian已经编译支持tvi3315a了  希望这边openwrt能够支持tvi3315a

**Comment by ophub** [comment]
已经同步添加了，固件也编译了。

**Comment by sehczaa** [comment]
> 已经同步添加了，固件也编译了。

好快，感谢大佬的付出
