### ISSUE TITLE
Failed to update the kernel online through LuCi.

### ISSUE THREAD

**Issue by grndis** [ophub/amlogic-s9xxx-openwrt#476]
**Device Information | 设备信息**
 - SOC: S095x3
 - Model x96 max+

**OpenWrt Version | 系统版本**
 - Kernel Version: 6.1.49-ophub
 - Release: OpenWrt 23.05.0-rc3

**Describe the bug | 问题描述**

I encountered an error while attempting to update the kernel online via LuCi. The error message states: `[Error] Missing [tar] in OpenWrt firmware, unable to update kernel.`

I tried uploading manually, but I got the same error message.

Got any clues to help fix this problem?

Thank you.

<img width="990" alt="CleanShot 2023-09-18 at 16 55 43@2x" src="https://github.com/ophub/amlogic-s9xxx-openwrt/assets/75177014/52a4cf1a-1789-471b-b4fb-d331ca2a6b91">

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-openwrt/tree/main/documents


10.11

When compiling by yourself, all required options must be added.

**Comment by grndis** [comment]
very clear, thank you 🤝🏼
