### ISSUE TITLE
I broke luci How can I use the command to upgrade?

### ISSUE THREAD

**Issue by simplove** [ophub/amlogic-s9xxx-openwrt#477]
**Device Information | 设备信息**
N1盒子
**OpenWrt Version | 系统版本**
5.15.74-flippy-78+o
OpenWrt 11.14.2022 by Kiddin' / LuCI Master git-73fe47b

**Describe the bug | 问题描述**
首页无法登录提示：
Bad Gateway
The process did not produce any response

I broke luci. The GUI interface cannot be used. I can log in via SSH and have uploaded the .img file. How can I use the command to upgrade?

在安装adguardhome的时候导致无法登录，提示
Bad Gateway
The process did not produce any response
估计是opkg源的问题，更新之后，再执行opkg update成功，但是openwrt界面仍然不行。
用不了图片化界面的那个晶晨宝盒。
但是ssh可以登录，已经重新下载了一个新的系统，openwrt-09.20.2023-s905d.img
解压之后是1个1G多的img文件。请问如何通过命令的方式升级恢复？
或者是告诉我如何修复Bad Gateway

设备在外面，不方便搞，不然我直接拿U盘弄了

**Comment by ophub** [comment]
openwrt-update-amlogic
