### ISSUE TITLE
failed image builder 22.03.5

### ISSUE THREAD

**Issue by itremote** [ophub/amlogic-s9xxx-openwrt#480]
**Device Information | 设备信息**
 - SOC: S905X3
 - Model H96Max

**OpenWrt Version | 系统版本**
 - Kernel Version: latest
 - Release: official 22.03.5

**Describe the bug | 问题描述**
I have failed image builder build workflow with only h96 max option 

![Screenshot_1](https://github.com/ophub/amlogic-s9xxx-openwrt/assets/140676334/91b92056-56df-4809-9326-b947e76b5aab)

**Comment by OldCoding** [comment]
![image](https://github.com/ophub/amlogic-s9xxx-openwrt/assets/85047508/aaa0d645-25dd-4d8b-9242-07bcfeabadad)
https://github.com/itremote/amlogic-s9xxx-openwrt/blob/23ef6697631ea80e0bd01a462cede8dd2ce2ea87/.github/workflows/build-openwrt-with-imagebuilder.yml#L241
patch？

**Comment by itremote** [comment]
> https://github.com/itremote/amlogic-s9xxx-openwrt/actions/runs/6270050206/job/17027414162#step:4:1320

thx.. just remove samba4 from config.. :)
