### ISSUE TITLE
刷入V900E22D发现的问题

### ISSUE THREAD

**Issue by WinstonDeSun** [ophub/amlogic-s9xxx-openwrt#485]
刷入V900E22D发现的问题
您好！我的机器盒子是V900E22D,芯片是S905L3A-B，刷入之后，改做旁路由，openwrt系统可以上网，软件源可以更新，但是把网关该为openwrt后无法上网。
刷入后指纹错误，导致部分ipk安装时提示不兼容。

主要是刷入后做旁路由手机电脑无网络的问题，还请作者优化一下，谢谢！

**Comment by WinstonDeSun** [comment]
刷入的固件是V900E22C的S905L3A芯片固件

**Comment by ophub** [comment]
这是你设置的问题，和优化无关。上网搜索相关教程和视频看看
