### ISSUE TITLE
请问E900V22D的盒子，芯片是s905l3a-b，是否可以刷s905l3b的固件？

### ISSUE THREAD

**Issue by WinstonDeSun** [ophub/amlogic-s9xxx-openwrt#487]
请问E900V22D的盒子，芯片是s905l3a-b，是否可以刷s905l3b的固件？

s905l3b对应的是E900V22D盒子，但我的E900V22D盒子却是s905l3a-b，不知道是否可通刷，求大神解答，谢谢!

**Comment by ophub** [comment]
这是一样的，我写的时候少写了一个（－），其他的a也一样，写的时候省略了
