### ISSUE TITLE
菜单里的终端不能用

### ISSUE THREAD

**Issue by goldsoft8888** [ophub/amlogic-s9xxx-openwrt#489]
OpenWrt_official_save_2023.10
菜单里的终端不能用，TTYD

**Comment by ophub** [comment]
改了IP要重启才能使用。

**Comment by goldsoft8888** [comment]
> 修改了IP要重启才能使用。
重启无数次了，卸了重装都不行

**Comment by ophub** [comment]
截图看看什么现象

**Comment by goldsoft8888** [comment]
还有，想装WIREGUARD，提示内核版本不对。

**Comment by goldsoft8888** [comment]
![1697261281325](https://github.com/ophub/amlogic-s9xxx-openwrt/assets/11472472/9124ea80-0e51-4514-a8ac-98749da6abcb)

**Comment by ophub** [comment]
![Snip20231014_3](https://github.com/ophub/amlogic-s9xxx-openwrt/assets/68696949/66193341-8e8d-4311-a1bf-fb06f647ead7)
![Snip20231014_4](https://github.com/ophub/amlogic-s9xxx-openwrt/assets/68696949/9ad87480-2336-4288-a5be-405c37533f44)

**Comment by goldsoft8888** [comment]
![1697264187808](https://github.com/ophub/amlogic-s9xxx-openwrt/assets/11472472/7b5721cb-9ba2-4ea2-a301-ef6f77cadbf6)
我是TX3的盒子，怎么都不行，前几天的版本，终端可以用的，升级到最新版的，就不行了，
