### ISSUE TITLE
Problem with installing kmod driver

### ISSUE THREAD

**Issue by elbarfallah** [ophub/amlogic-s9xxx-openwrt#49]
Hello, I want to install kmod-ath9k-htc, but opkg said that it isn't compatible with the architectures configured. Previously in LEDE version, I can install that driver by using argument --force-depends. But from this official version, it doesn't work anymore.
Here is the log:

root@OpenWrt:~# opkg install kmod-ath9k-htc
Unknown package 'kmod-ath9k-htc'.
Collected errors:
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-ath9k-common found, but incompatible with the architectures configured
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-ath9k-htc found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package kmod-ath9k-htc.

root@OpenWrt:~# opkg install kmod-ath9k-htc --force-depends
Unknown package 'kmod-ath9k-htc'.
Collected errors:
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-ath9k-common found, but incompatible with the architectures configured
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-ath9k-htc found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package kmod-ath9k-htc.

**Comment by ophub** [comment]
`CONFIG_PACKAGE_kmod-ath9k-htc=y`

I set the default integration of this driver, you can try again after the compilation is complete

**Comment by elbarfallah** [comment]
![image](https://user-images.githubusercontent.com/60389974/114275375-93098a00-9a4c-11eb-8da6-d21bbfd8640f.png)
Thanks, Now, I can use my usb wifi for my stb.
