### ISSUE TITLE
opkg update 时总是出错，安装软件包时，提示内核不对

### ISSUE THREAD

**Issue by goldsoft8888** [ophub/amlogic-s9xxx-openwrt#492]
opkg update 时总是出错，安装软件包时，提示内核不对，更新软件很多装不上
kernel 版本不兼容
tx3 mini  的最新版本openwrt_official_amlogic_s905w_k6.1.57_2023.10.13.img  ，不断重启，5.15版的启动正常。

最好与openwrt源相同，内核版本相同，太折腾了

能让在电视盒子用上openwrt，还是非常感谢各位老大的辛苦付出！

**Comment by ophub** [comment]
软件源是相同的
内核是不同的
如果内核使用官方就启动不了了，为了能在盒子上启动，使用了f大的移花接木桂花香的手术。
一般情况下kmod不能在线安装，需要编译时添加，其他软件包应该都可以正常安装更新。

**Comment by goldsoft8888** [comment]
谢谢老大的耐心解答，我明白了。wireguard能编译进去吗？这个比OPENVPN好用。

**Comment by goldsoft8888** [comment]
已安装的软件包 kernel 版本不兼容，需要 5.15.134-1-39db1d77… 而 6.1.56-1-2b00528c… 已安装。

**Comment by shirakun** [comment]
编译的时候编译一个sdk
用到的kmod包可以尝试用sdk编译看看
