### ISSUE TITLE
如何配置 N1 以突破校园网设备数限制？

### ISSUE THREAD

**Issue by hmsjy2017** [ophub/amlogic-s9xxx-openwrt#494]
**Device Information | 设备信息**
 - SOC: s905d
 - Model: Phicomm N1

**OpenWrt Version | 系统版本**
 - Kernel Version: 6.1.59-ophub
 - Release: official 23.05

**Describe the bug | 问题描述**
学校使用 Dr.com 网页认证，无论是 WiFi 还是以太网都要认证，而且限制两台设备同时登录。连上 N1 的 WiFi 后，每台设备还是要单独认证，此时 N1 相当于交换机，无法突破校园网设备数限制。由于网关地址变成了 172.22.0.1，此时会无法访问 OpenWrt 的后台管理页面。

网上说向认证服务器发送一条 GET 请求即可通过认证，我在手机、电脑和香橙派上都测试成功了。理论上把认证脚本放在 N1 上并加一个计划任务就行，但实测还是会被劫持到校园网登录页面。

**Comment by shirakun** [comment]
这位同学,你问错地方了
