### ISSUE TITLE
最新的docker版OP，webui好像进不去

### ISSUE THREAD

**Issue by iJayscn** [ophub/amlogic-s9xxx-openwrt#499]
**Device Information | 设备信息**
 - SOC: S905D
 - Model: N1

**OpenWrt Version | 系统版本**
 - Kernel Version: Linux 6.1.38-ophub
 - Release:DOCKER

SSH 正常，ping OP容器正常，容器内ping 其他网站都正常

就是webui进不去，不知道啥问题

浏览器提示：

嗯… 
无法访问此页面192.168.1.1 
已拒绝连接。

PS：192.168.1.1 没有其他设备占用！

退回好久个月前的一个版本 就正常访问！

**Comment by iJayscn** [comment]
DIGEST
eba43034216e

这个版本也不行，是只有我有这个问题吗？ 大家都正常吗？

**Comment by iJayscn** [comment]
> 修改 /etc/config/uhttpd 文件，注释掉 2 行 listen_https

这样是能解决

后续版本会修复不？

**Comment by ophub** [comment]
切换到官方源的tar包使用吧，lede

![Snip20231201_1](https://github.com/ophub/amlogic-s9xxx-openwrt/assets/68696949/8bf554c9-d2fe-42c9-ac89-1c2146fde8bb)
![Snip20231201_2](https://github.com/ophub/amlogic-s9xxx-openwrt/assets/68696949/14d481bf-37e0-4040-8edf-fb283135833e)
![Snip20231201_3](https://github.com/ophub/amlogic-s9xxx-openwrt/assets/68696949/d8bf53dc-0ccb-41cb-9473-3b6c00af93cb)
