### ISSUE TITLE
荐片盒子ssh用不了！？

### ISSUE THREAD

**Issue by y9858** [ophub/amlogic-s9xxx-openwrt#508]
**Device Information | 设备信息**
 - SOC: [rk3566]
 - Model [荐片TV]

**OpenWrt Version | 系统版本**
 - Kernel Version: [6.1.62]
 - Release: [immortalwrt]

**Describe the bug | 问题描述**
使用immortalwrt master源码编译，用本源码打包。网页ttyd和电脑MobaXterm连ssh都提示如图：

![QQ截图20231119130559](https://github.com/ophub/amlogic-s9xxx-openwrt/assets/53130835/2ddcae02-ccff-417b-9e6b-3912f4f5bd6d)

按键盘ctrl+c/enter也没反应！。

**Comment by ophub** [comment]
你编译的底包缺必要依赖，这个欢迎界面的温度等都没显示出来：
https://github.com/ophub/amlogic-s9xxx-openwrt/blob/main/make-openwrt/openwrt-files/common-files/etc/profile.d/30-sysinfo.sh



https://github.com/ophub/amlogic-s9xxx-openwrt/blob/main/documents/README.cn.md
看10.11

**Comment by y9858** [comment]
[kmod-brcmfmac(SDIO)|kmod-brcmutil|kmod-cfg80211|kmod-mac80211|hostapd-common|wpa-cli|wpad-basic|iw|zoneinfo-europe (other) other找不到 没选 |acpid]用不上wifi 这些都没选。情况依旧。附上.config。
[1.txt](https://github.com/ophub/amlogic-s9xxx-openwrt/files/13402530/1.txt)

**Comment by y9858** [comment]
换大雕源码 ok了
