### ISSUE TITLE
rclone

### ISSUE THREAD

**Issue by lynxnexy** [ophub/amlogic-s9xxx-openwrt#51]
can you add rclone package into fw openwrt-21.02

**Comment by ophub** [comment]
No plug-in source that supports openwrt-21.02 was found.

Currently openwrt-21.02 has just been officially released. It is recommended that you use the stable branch of lede.

**Comment by lynxnexy** [comment]
ok thanks for the help

**Comment by ophub** [comment]
Found it, it has been added to openwrt-21.02
