### ISSUE TITLE
 Cannot find the partition corresponding to the root file system!

### ISSUE THREAD

**Issue by vpei** [ophub/amlogic-s9xxx-openwrt#511]
Cannot find the partition corresponding to the root file system!

上次升级后出现这种情况，系统正常使用，现在再升级就提示这个错误。

**Comment by acd407** [comment]
i have the same error with the compiled image for panther x2.

**Comment by Dimazhan** [comment]
same error where connecting to s905x2-x96max-2g booted from usb flash
perhaps not the best solution, but I decided for myself so
[sysinfo_fix.patch](https://github.com/ophub/amlogic-s9xxx-openwrt/files/13464776/sysinfo_fix.patch)
