### ISSUE TITLE
Rootfs partition does not exist in emmc

### ISSUE THREAD

**Issue by SHINRA-OPI** [ophub/amlogic-s9xxx-openwrt#518]
**Device Information | 设备信息**
 - SOC: [s905x]
 - Model [Generic Tv Box(tv98) 1gb/8gb emmc]

**OpenWrt Version | 系统版本**
 - Kernel Version: [6.1.65]
 - Release: [lede]

There are no problem if the openwrt was booted in usb, the problem will occur after the installation in emmc. In booting, there is an alert "UUID=(the long id) does not exist. Dropping to shell! " Then it stuck in "(initramfs)" . I enter blkid command and there is no rootfs partition only "EMMC SHARE, EMMC ROOTFS1, EMMC ROOTFS2 AND EMMC BOOT". I try to plugged in my usb drive and enter exit command the booting continues like normal. I will provide screenshot if you need tomorrow.

**Comment by SHINRA-OPI** [comment]
![Uploading IMG_20231218_101813_176.jpg…]()

**Comment by SHINRA-OPI** [comment]
![Uploading IMG_20231218_101958_222.jpg…]()

**Comment by ophub** [comment]
You cannot see the picture you posted. When posting an image, you need to wait for the image to finish uploading before submitting it. Without the UUID, it indicates that the write was not successful. Please try writing to the eMMC again (System Menu - Amlogic Service - Install OpenWrt).

**Comment by SHINRA-OPI** [comment]
![IMG_20231218_101813_176](https://github.com/ophub/amlogic-s9xxx-openwrt/assets/76043615/f204122e-de65-449c-8c6f-6b378df13d66)
![IMG_20231218_101958_222](https://github.com/ophub/amlogic-s9xxx-openwrt/assets/76043615/e7c369a0-d28d-4c87-9949-62086fa10def)

**Comment by ophub** [comment]
System Menu - Amlogic Service - Install OpenWrt

**Comment by SHINRA-OPI** [comment]
I try it several times it still the same error

**Comment by ophub** [comment]
try kernel 5.15.y

**Comment by SHINRA-OPI** [comment]
the 2023.12,23 version of lede with kernel 5.15.144 is now booting without a problem. Thank you
