### ISSUE TITLE
能否在actions里面增加支持ISTOREOS源码

### ISSUE THREAD

**Issue by hx801217** [ophub/amlogic-s9xxx-openwrt#519]
实在不会修改DTB，导致JP-TVBOX难以运行最新ISTOREOS,能否通过大佬的方法用您和F大的kernel引导他们的rootfs

**Comment by ophub** [comment]
不知道你说的是什么

**Comment by hx801217** [comment]
除了build  
          - openwrt-main
          - lede-master
          - immortalwrt-master 这三种外，能不能增加iStoreOS-22.03

**Comment by ophub** [comment]
仓库发一下

**Comment by hx801217** [comment]
> 仓库发一下

https://github.com/istoreos/istoreos

**Comment by ophub** [comment]
添加了，你测试下
默认ip：192.168.1.1
默认用户：root
默认密码：password

**Comment by hx801217** [comment]
感谢大佬

**Comment by hx801217** [comment]
第一时间试了JPTVBOX，不行
![QQ截图20231223223434](https://github.com/ophub/amlogic-s9xxx-openwrt/assets/34504398/97e916e1-16b1-43d9-a2ce-49049d7be695)

**Comment by bakeDong1** [comment]
大佬找到一个istoreos的action https://github.com/draco-china/istoreos-actions 不知道有没有用
