### ISSUE TITLE
kylin3399刷最新OpenWrt_istoreos_save_2023.12 最新发行版-能启动，无法识别网卡  无法获取ip

### ISSUE THREAD

**Issue by dahuazi** [ophub/amlogic-s9xxx-openwrt#520]
可以启动，但是无法获取ip，接显示器 键盘后  无法输入命令 

所刷固件为  openwrt_istoreos_rockchip_kylin3399_k6.1.69_2023.12.24.img.gz

**Comment by dahuazi** [comment]
![Uploading 微信图片_20231225160143.jpg…]()

**Comment by dahuazi** [comment]
恳请大佬帮忙看看，能不能解决一下

**Comment by ophub** [comment]
刷其他的吧，我第一次接触istoreos，不知道为什么他的network一直无法工作，我在n1上测试了也是没网络，我先下架了。

**Comment by hx801217** [comment]
翘首以盼O大再次上线。

**Comment by Vinke2** [comment]
现在呢
