### ISSUE TITLE
immortalwrt 防火墙区域没有 开启fullcone选项

### ISSUE THREAD

**Issue by Link-ee** [ophub/amlogic-s9xxx-openwrt#521]
如题，使用23.05和master  fw4 打包出来的在盒子上没有开去fullcone选项，下图是我X86使用的时候可以正常显示。
![image](https://github.com/ophub/amlogic-s9xxx-openwrt/assets/79355200/30466d1e-af0f-4afd-9dfc-dd6f842209b1)

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-openwrt/blob/ab863ef755efeca2f5fe4a5d461fff926bfecd3e/config/immortalwrt-master/config#L2386

把2386行这个改成y试试

`CONFIG_PACKAGE_kmod-ipt-fullconenat=y`

**Comment by Link-ee** [comment]
> https://github.com/ophub/amlogic-s9xxx-openwrt/blob/ab863ef755efeca2f5fe4a5d461fff926bfecd3e/config/immortalwrt-master/config#L2386
> 
> 把2386行这个改成y试试
> 
> `CONFIG_PACKAGE_kmod-ipt-fullconenat=y`

这个是ipt的吧，默认的nft的fullcone是已经选中了
https://github.com/ophub/amlogic-s9xxx-openwrt/blob/ab863ef755efeca2f5fe4a5d461fff926bfecd3e/config/immortalwrt-master/config#L2454

**Comment by AoXIUy** [comment]
老哥，无法开启Fullcone解决了吗
