### ISSUE TITLE
lede版默认的腾讯云源在海外用不了

### ISSUE THREAD

**Issue by ysuolmai** [ophub/amlogic-s9xxx-openwrt#525]
在海外盒子上无法获取armvirt目录
![image](https://github.com/ophub/amlogic-s9xxx-openwrt/assets/12818757/ae04e52f-8503-4f37-a7cd-a307c99f32c0)

国内的盒子没有问题
![image](https://github.com/ophub/amlogic-s9xxx-openwrt/assets/12818757/2ea56075-1db1-432f-9685-ff5060d121ab)

不知道有什么好的解决办法? 
另外不用Immortal版是因为immortal版在我这个鲸鱼盒子上, 5.15版启动通过eth0无法获取IP, 6.1版能启动但是写入emmc后无法启动. lede版正常但是无法更新

**Comment by ophub** [comment]
某些插件里选择回国模式
