### ISSUE TITLE
ZTE B860H

### ISSUE THREAD

**Issue by adereksisusanto** [ophub/amlogic-s9xxx-openwrt#529]
**Device Information | 设备信息**
 - SOC: Amlogic s905x
 - Model ZTE B860H

**OpenWrt Version | 系统版本**
 - Kernel Version: 5.15.145
 - Release: official an immortalwrt

**Describe the bug | 问题描述**
- [ ] for zte b860h firmware openwrt_official_amlogic_s905x-t95_k5.15.145_2024.01.07.img.gz wireless AP is activated can't login to LUCI and wireless remains undetected

- [ ] for zte b860h firmware openwrt_immortalwrt_amlogic_s905x_k5.15.145_2024.01.07.img can't login to LUCI and LAN is not connected

Please provide a detailed description of the issue and, if necessary, attach a screenshot.
详细描述问题，并在必要时附上屏幕截图。

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-openwrt/blob/1079997d5e79596c54bcf31ebd508969f813fa59/make-openwrt/openwrt-files/common-files/etc/model_database.conf#L47

Compile the firmware by selecting the correct board option `s905x-b860h`

**Comment by adereksisusanto** [comment]
terminal not access
![image](https://github.com/ophub/amlogic-s9xxx-openwrt/assets/34746706/59cb4de1-2454-473a-ad8d-d34888d38440)

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-openwrt/blob/c5c44fe5df80de8d58be773c08326275d13f414c/make-openwrt/openwrt-files/common-files/etc/profile.d/30-sysinfo.sh#L18-L23

**Comment by adereksisusanto** [comment]
how to fix  @ophub ?

**Comment by ophub** [comment]
try lede tag

https://github.com/ophub/amlogic-s9xxx-openwrt/releases/tag/OpenWrt_lede_save_2024.01

**Comment by adereksisusanto** [comment]
thanks @ophub 
![image](https://github.com/ophub/amlogic-s9xxx-openwrt/assets/34746706/602eee31-1dd1-44ab-b993-7e0399fe6551)
