### ISSUE TITLE
wont boot to emmc

### ISSUE THREAD

**Issue by Chicadaa** [ophub/amlogic-s9xxx-openwrt#53]
Hello, I already install openwrt to emmc (B860H V1) and when I tried to reboot why it won't boot to the openwrt?
sorry for my bad english

**Comment by ophub** [comment]
Dial the power source, and then try to plug in the power source. What is the version number of the kernel you installed.

**Comment by Chicadaa** [comment]
How do i check it?

**Comment by Chicadaa** [comment]
Do I need to change boot file?

**Comment by ophub** [comment]
meson-gxl-s905x-p212.dtb

**Comment by Chicadaa** [comment]
Done, What to do next?

**Comment by ophub** [comment]
Then it's all right. Unplug the U disk, unplug the power supply, plug in the power supply again, wait one minute for the system to start, and you can use it

**Comment by Chicadaa** [comment]
> Then it's all right. Unplug the U disk, unplug the power supply, plug in the power supply again, wait one minute for the system to start, and you can use it

I did, but why the system won't start

**Comment by ophub** [comment]
Start and end your installation. Send screenshots of these two parts. Let me take a look at your installation.

**Comment by Chicadaa** [comment]
![image](https://user-images.githubusercontent.com/50999514/114558064-7f506480-9c94-11eb-9760-bac53a94b89e.png)
![image](https://user-images.githubusercontent.com/50999514/114558200-a3ac4100-9c94-11eb-8399-7bcaeb57ef41.png)
[logs.txt](https://github.com/ophub/amlogic-s9xxx-openwrt/files/6303947/logs.txt)

**Comment by ophub** [comment]
When writing into EMMC through openwrt-install, select 0
enter：
meson-gxl-s905x-zte-b860h.dtb
