### ISSUE TITLE
没法使用安装完成找不到根目录，无法进入终端，ssh也进不去。

### ISSUE THREAD

**Issue by daliyunhu** [ophub/amlogic-s9xxx-openwrt#534]
**Device Information | 设备信息**
 - SOC: [e.g. S095x3]
 - Model [e.g. HK1]

**OpenWrt Version | 系统版本**
 - Kernel Version: [e.g. 5.15.100]
 - Release: [e.g. official/lede/immortalwrt]

**Describe the bug | 问题描述**
All issues will only remain open for one week to prioritize resolving them.
After that period, they will be closed but can still continue to be discussed in the thread.
所有的问题都只保留一周的开启状态供重点关注解决，超时将关闭，但仍然可以长期继续跟帖讨论。

Please provide a detailed description of the issue and, if necessary, attach a screenshot.
详细描述问题，并在必要时附上屏幕截图。

**Comment by ophub** [comment]
终端已经修复，测试最新固件

**Comment by daliyunhu** [comment]
很是感谢，问题已修复，目前使用正常。

ophub ***@***.***> 于2024年1月19日周五 17:16写道：
