### ISSUE TITLE
Error Symlink Build

### ISSUE THREAD

**Issue by Manssizz** [ophub/amlogic-s9xxx-openwrt#551]
**OpenWrt Version | 系统版本**
 - Kernel Version: 5.4 - 6.1
 - Release: official/lede/immortalwrt

**Describe the bug | 问题描述**
`ln: failed to create symbolic link '/home/runner/work/_actions/ophub/amlogic-s9xxx-openwrt/main/openwrt': No such file or directory`

![image](https://github.com/ophub/amlogic-s9xxx-openwrt/assets/23637327/354ece08-19b1-40ba-9059-21f7c3745c90)

**Comment by ophub** [comment]
uses: manssizz/amlogic-s9xxx-openwrt@cendrawasih


You are using your own actions; modify the path from "ophub" to "manssizz".

**Comment by Manssizz** [comment]
thanks. 
after updating repo name and branch. worker running without problem.
