### ISSUE TITLE
CM201-1 S905L3盒子未适配

### ISSUE THREAD

**Issue by goodnull** [ophub/amlogic-s9xxx-openwrt#553]
**Device Information | 设备信息**
 - SOC: S905L3
 - Model  CM201-1-YS

**Describe the bug | 问题描述**
测试了一些包都不能开机，从安卓adb U盘启动亮红灯，路由器后台看不到设备

这是我按教程，从安卓系统里提取的bootloader 和 dtb 文件，大佬帮忙编译下
[mybox.zip](https://github.com/ophub/amlogic-s9xxx-openwrt/files/14561163/mybox.zip)

**Comment by goodnull** [comment]
发错仓库，我是想刷armbian的

**Comment by ophub** [comment]
你找个root的安卓，最好9.0+的换个安卓再试

**Comment by goodnull** [comment]
adb是带root的，安卓是4.0

找了好多包，都刷不进去，其中两个能刷的都是4.0
