### ISSUE TITLE
RK3328有支持百兆网口的包吗？

### ISSUE THREAD

**Issue by nihaonas** [ophub/amlogic-s9xxx-openwrt#558]
请问大佬，我还有个R-box plus使用的是RK3328芯片，使用rk3328-roc-cc.dtb  可以正常引导进入，但是不能识别我的百兆网口，无法连接网络，网口灯也不闪烁，确定网口是好的，使用盒子的时候可以正常联网，我看了支持列表 rk3328都是支持的千兆网口
请问大佬有啥办法吗？

**Comment by ophub** [comment]
没有这个设备的固件
