### ISSUE TITLE
大神，求S905L3A-B固件

### ISSUE THREAD

**Issue by Twodogs2020** [ophub/amlogic-s9xxx-openwrt#559]
大神，求OpenWrt固件
型号
CPU：S905L3A-B
DDR+Flash：4+32

CM511-1 pro
网口是千兆的

在拜托大神，来个带Root底包固件，实在找不到，拜托了！！
叩首！感谢！！！

如下图
https://picgo-2023-1317500951.cos.ap-guangzhou.myqcloud.com/imgs/6ac30d490acc729811a0e4c161c518d.jpg

https://picgo-2023-1317500951.cos.ap-guangzhou.myqcloud.com/imgs/3e318af61bedeb22808d6183709cdec.jpg

https://picgo-2023-1317500951.cos.ap-guangzhou.myqcloud.com/imgs/3446cf883bd015be66dfdde326770d8.jpg

https://picgo-2023-1317500951.cos.ap-guangzhou.myqcloud.com/imgs/f4bc63e1494cced131ec95ca5a0eb51.jpg

https://picgo-2023-1317500951.cos.ap-guangzhou.myqcloud.com/imgs/7b024103848bd5ca283d66b44aa0798.jpg

**Comment by ophub** [comment]
没有固件
