### ISSUE TITLE
H3 support request

### ISSUE THREAD

**Issue by puccio823** [ophub/amlogic-s9xxx-openwrt#560]
hi ophub, I was wondering if it was possible to start openwrt in this tv box
https://linux-sunxi.org/MXQ-4K
these are images of the TV box I have
![IMG20240315093255](https://github.com/ophub/amlogic-s9xxx-openwrt/assets/118255617/81c3d4a6-4338-4cb4-a102-a4d1e5e7cf71)
![IMG20240315093914](https://github.com/ophub/amlogic-s9xxx-openwrt/assets/118255617/b7946ea7-d231-4bd1-925e-3ca7869109de)
![IMG20240315093326](https://github.com/ophub/amlogic-s9xxx-openwrt/assets/118255617/18cfab5f-5bda-4dab-81cd-12b6f991a235)
![IMG20240315093808](https://github.com/ophub/amlogic-s9xxx-openwrt/assets/118255617/685028ec-4aac-4fa6-a11d-16779f7329ed)

**Comment by ophub** [comment]
没有固件
