### ISSUE TITLE
Please Add Device Nanopi R2S

### ISSUE THREAD

**Issue by adibindrianto** [ophub/amlogic-s9xxx-openwrt#563]
please add support for nanopi r2s devices, thank you

**Comment by reukiodo** [comment]
Isn't it already supported officially? https://openwrt.org/toh/friendlyarm/nanopi_r2s

**Comment by ophub** [comment]
Added, could you please test if it works as expected?

**Comment by adibindrianto** [comment]
I will try and report any bugs found

**Comment by adibindrianto** [comment]
1. Can't access the web UI
2. The indicator light on the device does not turn on
3. Changing to another kernel still returns to kernel 6.1

**Comment by ophub** [comment]
I am using the default configuration of armbian official r2s, which should work fine. Could you please send me a download link to an armbian image file that you can use normally, so I can take a look and see what the problem is?

**Comment by adibindrianto** [comment]
I tried openwrt 23.05.3 kernel ophub stable all versions with build imager
