### ISSUE TITLE
e900v22c  2+8 用晶晨宝盒无法写入EMMC

### ISSUE THREAD

**Issue by NFH9** [ophub/amlogic-s9xxx-openwrt#571]
![1](https://github.com/ophub/amlogic-s9xxx-openwrt/assets/166964532/561406a8-74aa-4dfa-8742-dbad090b1081)
![2](https://github.com/ophub/amlogic-s9xxx-openwrt/assets/166964532/97783100-67c5-4e49-9e91-1244ab3e1a30)
如题，是不是只有改成4+64或128才能写入？如果不改，原机配置怎么写入EMMC，谢谢啦！

**Comment by ophub** [comment]
看仓库的文档，调低dtb的频率
