### ISSUE TITLE
S905L2 U盘启动成功，写入emmc后无法开机

### ISSUE THREAD

**Issue by liuyi265** [ophub/amlogic-s9xxx-openwrt#575]
**Device Information | 设备信息**
 - SOC: s905l2
 - Model 杰赛科技S65
使用
openwrt_official_amlogic_s905l2_k6.1.84_2024.04.08.img
最开始启动后无法识别网卡
参照https://github.com/ophub/amlogic-s9xxx-armbian/issues/1278
复制u-boot-s905x-s912文件，改成u-boot.emmc
u-boot-s905x-s912 改为U-boot.ext
从U盘启动后网卡正常识别，无法识别EMMC

参照https://github.com/ophub/amlogic-s9xxx-armbian/issues/1277  回复中的DBT文件下载，使用此DBT文件可以识别EMMC，使用魔盒刷入EMMC后无法开机

请大佬帮忙分析下问题

**Comment by whmzsu** [comment]
我也碰到类似的问题，u盘启动没问题，安装刷入emmc也ok，但是启动失败
