### ISSUE TITLE
创维E900V21C用哪个刷机包

### ISSUE THREAD

**Issue by samnelking** [ophub/amlogic-s9xxx-openwrt#576]
移动的盒子,芯片是S905L的,1G内存,8GB ROM.曾经用Armbian_20.10_Arm-64_buster_current_5.9.0.img成功刷过,但用这里的
Armbian_24.5.0_amlogic_s905l_jammy_6.1.84_server_2024.04.08.img刷无法启动.还望各位大能不吝指教,谢谢

**Comment by ophub** [comment]
在设备列表点链接进去，看贡献者的分享，刷对应的安卓
