### ISSUE TITLE
请教是否可行

### ISSUE THREAD

**Issue by greatzane** [ophub/amlogic-s9xxx-openwrt#584]
我有一块firefly-rk3399，可以刷入目前的snapshot openwrt，但是我想要使用stable版的openwrt，是否可以通过将6.1.y的内核与stable版的rootfs相结合做出一个stable版？如果可行opkg中kmod的兼容问题又如何解决？

**Comment by ophub** [comment]
结合可以，我就是这么制作的。
默认编译op带的kmod可以正常使用。

**Comment by greatzane** [comment]
那请问一下为啥咱们项目不用stable版而用snapshot呢？有时总有些问题不知道是不是snapshot的缘故。
