### ISSUE TITLE
Seewo SV21的dts文件问题，CPU没有跑满

### ISSUE THREAD

**Issue by itoywh** [ophub/amlogic-s9xxx-openwrt#586]
您好，用这个编译op后，发现跑分特别慢，才1w2左右，正常的3568跑分大概在2w7左右，经检查发现cpu是跑在最低频率了，dts有问题，要加上opp？恳请加上

![WX20240515-124451@2x](https://github.com/ophub/amlogic-s9xxx-openwrt/assets/46450501/eb1c76e3-6c21-4c3d-8d7c-72015ecc1b67)

**Comment by itoywh** [comment]
网上找了几个dts文件，但是我不会打包添加，给您做下参考，看是否修复了，或者您帮忙打包

lede的  https://github.com/coolsnowwolf/lede/blob/master/target/linux/rockchip/files/arch/arm64/boot/dts/rockchip/rk3568-seewo-sv21.dts

liwei的 https://github.com/liwei19920307/armbian/blob/main/patch/kernel/rk35xx-vendor-6.1/dt/rk3568-seewo-sv21.dts

factory https://github.com/blacksamuraiiii/seewo-sv21-rk3568/blob/main/rk3568-seewo-sv21_factory.dts

**Comment by ophub** [comment]
![Snip20240515_17](https://github.com/ophub/amlogic-s9xxx-openwrt/assets/68696949/f12659d6-8269-47cf-a139-b2405ed10c53)

![Snip20240515_18](https://github.com/ophub/amlogic-s9xxx-openwrt/assets/68696949/00800558-664c-4c51-9401-288c677146ca)

3个都无法编译，其中第三个不是内核源码，是个反编译文件。

**Comment by itoywh** [comment]
> ![Snip20240515_17](https://private-user-images.githubusercontent.com/68696949/330744921-f12659d6-8269-47cf-a139-b2405ed10c53.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3ODA4MDEsIm5iZiI6MTcxNTc4MDUwMSwicGF0aCI6Ii82ODY5Njk0OS8zMzA3NDQ5MjEtZjEyNjU5ZDYtODI2OS00N2NmLWExMzktYjI0MDVlZDEwYzUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE1VDEzNDE0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkZGY2MmEzZTdkZmFjYzY2NDNiMjFjNzJhYWVhMTNiNGE5M2VhYTBjOTE3NWRhNDQ0NTdjMjIwNmVmM2IwZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aN0_K8Q903FT6KU6J_vpxW7eGGYByIlK0Awa79YukI4)
> 
> ![Snip20240515_18](https://private-user-images.githubusercontent.com/68696949/330744939-00800558-664c-4c51-9401-288c677146ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3ODA4MDEsIm5iZiI6MTcxNTc4MDUwMSwicGF0aCI6Ii82ODY5Njk0OS8zMzA3NDQ5MzktMDA4MDA1NTgtNjY0Yy00YzUxLTk0MDEtMjg4YzY3NzE0NmNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE1VDEzNDE0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlYzBhZmQ5OGJiY2YxYjQ0YzQ2MzlmZTUzNzUxMTBkNDgzMmJlZGMxOTAwNjYwNzlkOWRhZjczM2QyMzM2ZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eWc2RnC7jWz_9dGN6pR1IxlR0vBvjN0-OfPDr6WelUE)
> 
> 3个都无法编译，其中第三个不是内核源码，是个反编译文件。 测试环境为主线内核源码6.1.y： https://github.com/unifreq/linux-6.1.y

好吧，那老哥，有什么办法能调试提升下CPU性能呢，还是需要找到标准的dts文件么？这个性能实在是太憋屈了。
