### ISSUE TITLE
指定5.15.158内核，提示dg3399不能使用该内核

### ISSUE THREAD

**Issue by mazige1997** [ophub/amlogic-s9xxx-openwrt#587]
**Device Information | 设备信息**
 - SOC: [rk3399]
 - Model [dg3399]

**OpenWrt Version | 系统版本**
 - Kernel Version: [5.15.158]
 - Release: [lede]

**Describe the bug | 问题描述**
指定5.15.158内核，提示dg3399不能使用该内核。附上编译日志
Copy OpenWrt rootfs file: [ openwrt/output/*rootfs.tar.gz ]
'/home/runner/work/amlogic-s9xxx-openwrt/amlogic-s9xxx-openwrt/openwrt/output/openwrt-armvirt-64-generic-rootfs.tar.gz' -> 'openwrt-armvirt/openwrt-armvirt-64-generic-rootfs.tar.gz'
About the [ openwrt-armvirt ] directory: 
total 345[84](https://github.com/mazige1997/amlogic-s9xxx-openwrt/actions/runs/9096529350/job/25002144644#step:14:86)
-rw-r--r-- 1 runner docker 35410495 May 15 10:53 openwrt-armvirt-64-generic-rootfs.tar.gz
Start to make openwrt...
[ STEPS ] Welcome to make OpenWrt!
[ INFO ] Server running on Ubuntu: [ Release: jammy / Host: x[86](https://github.com/mazige1997/amlogic-s9xxx-openwrt/actions/runs/9096529350/job/25002144644#step:14:88)_64 ] 

[ STEPS ] Start Initializing Variables...
[ INFO ] The kernel tags list: [ specific ]
[ STEPS ] Start searching for OpenWrt file...
[ INFO ] OpenWrt file: [ openwrt-armvirt-64-generic-rootfs.tar.gz ]
[ INFO ] The source_codename: [ _lede ], OpenWrt source code repository: [ github.com/coolsnowwolf/lede ]
[ STEPS ] Start downloading dependency files...
[ INFO ] firmware download completed.
[ INFO ] different-files download completed.
[ INFO ] balethirq download completed.
[ INFO ] app/sbin download completed.
[ INFO ] app/share download completed.
[ STEPS ] Start downloading the kernel files...
[ INFO ] (1.1) [ specific - 5.15.158 ] Kernel download from [ https://github.com/ophub/kernel/releases/download/kernel_stable/5.15.158.tar.gz ]
[ INFO ] All [ 6 ] kernel files are sha256sum checked to be complete.

[ INFO ] [ 1 ] lists of OpenWrt board: [ dg3399 ]
[ INFO ] Kernel Repo: [ ophub/kernel ], Kernel Usage: [ stable ] 

[ INFO ] Server space usage before starting to compile: 
Filesystem                Type  Size  Used Avail Use% Mounted on
/dev/mapper/github-runner xfs   112G  [92](https://github.com/mazige1997/amlogic-s9xxx-openwrt/actions/runs/9096529350/job/25002144644#step:14:94)5M  112G   1% /builder 

[ STEPS ] Start making OpenWrt firmware...
(1.1) [ NOTE ] The [ dg3399 ] device cannot use [ stable/5.15.158 ] kernel, skip.
[ STEPS ] Server space usage after compilation: 
Filesystem                Type  Size  Used Avail Use% Mounted on
/dev/mapper/github-runner xfs   112G  925M  112G   1% /builder

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/armbian-files/common-files/etc/model_database.conf

在model里做了限制，rk3399只在6.1.y下做过测试，其他内核没dts

**Comment by mazige1997** [comment]
哦哦
