### ISSUE TITLE
U盘启动后卡住了

### ISSUE THREAD

**Issue by zhoushun98** [ophub/amlogic-s9xxx-openwrt#588]
MGV2000 KL     S905L2

从U盘启动，然后就卡在这个页面，是盒子性能不行，要等一会，还是出错了

![image](https://github.com/ophub/amlogic-s9xxx-openwrt/assets/69625362/d247a97f-efe3-4d67-8941-30a7185da74b)

**Comment by ophub** [comment]
这就是ok了，你想看banner回车一下
