### ISSUE TITLE
CM311-1A YST 305写入EMMC黑屏

### ISSUE THREAD

**Issue by jackcctse** [ophub/amlogic-s9xxx-openwrt#590]
盒子是YST，u盘启动没有问题。写入EMMC时，选305时开机黑屏，机器红灯，应该没有启动； 但选304时则正常启动。这个算bug吗？测试了5.15， 6.1, 6.6的核心，结果一样。

另外问, 在自定image 时，device board里面有一个s905l3a-cm311， 这个跟s905l3a有什么区别吗？

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/armbian-files/common-files/etc/model_database.conf

每个board的配置看model。
有些魔百和没有hdmi输出，使用ssh管理。

**Comment by jackcctse** [comment]
我就是headless操作。选305时黑屏红灯，系统没有载入。
看了配置文件，不肯定是否因为BT-rtl8761b就黑屏，但305这个board layout确实有误导成份。
