### ISSUE TITLE
Default setting

### ISSUE THREAD

**Issue by lynxnexy** [ophub/amlogic-s9xxx-openwrt#60]
how to change the default time zone and language

**Comment by ophub** [comment]
There are default settings in Lienol's plugin library, which are as follows:
https://github.com/Lienol/openwrt/blob/19.07/package/default-settings/files/zzz-default-settings


I added a few lines to modify the code in the config file, you can remove # and modify according to your own time zone.
line 22-24:
https://github.com/ophub/amlogic-s9xxx-openwrt/blob/main/router-config/openwrt-master/diy-part2.sh
