### ISSUE TITLE
添加iStore提供的feed源就可以编译出istore首页的openwrt

### ISSUE THREAD

**Issue by phcl1998** [ophub/amlogic-s9xxx-openwrt#600]
项目地址:https://github.com/linkease/nas-packages-luci
效果:
![UDPMYHJQ9(DB{L)S~@22(WW](https://github.com/ophub/amlogic-s9xxx-openwrt/assets/125857645/f5882ab6-614d-43c6-aba2-8e0d386ae81e)
![1AP2XG%{3RL%%PQTB4PVAD8](https://github.com/ophub/amlogic-s9xxx-openwrt/assets/125857645/4144f6b9-174e-4f59-bd00-cfad064813bc)
![0(%(7D4)}( @YX O1ZQ}`TA](https://github.com/ophub/amlogic-s9xxx-openwrt/assets/125857645/35d35e9d-c723-428f-854b-697b312437c0)
![M)CYCC%A{LA1977NS2UQ(OS](https://github.com/ophub/amlogic-s9xxx-openwrt/assets/125857645/c233b9e1-3856-4dc6-975f-ef2c5a6c3551)
1.复刻ophub openwrt仓库，在diy-part1.sh脚本里添加
echo >> feeds.conf.default
echo 'src-git istore https://github.com/linkease/istore;main' >> feeds.conf.default
echo >> feeds.conf.default
echo 'src-git nas https://github.com/linkease/nas-packages.git;master' >> feeds.conf.default
echo 'src-git nas_luci https://github.com/linkease/nas-packages-luci.git;main' >> feeds.conf.default
2.在config文件里 Applications 下增加
CONFIG_PACKAGE_luci-app-ddnsto=y
CONFIG_PACKAGE_luci-app-diskman=y
CONFIG_PACKAGE_luci-app-istorex=y
CONFIG_PACKAGE_luci-app-linkease=y
CONFIG_PACKAGE_luci-app-quickstart=y
CONFIG_PACKAGE_luci-app-unishare=y
CONFIG_PACKAGE_luci-nginxer=y

**Comment by b051431** [comment]
编译刷机报软件源配置错误

**Comment by b051431** [comment]
编译刷机报软件源配置错误

**Comment by Vinke2** [comment]
用的是哪个源码官方 or lede or immortalWrt?
