### ISSUE TITLE
Build OpenWrt with ImageBuilder  rockchip 系列不能用5.10_5.15 的内核 生成固件

### ISSUE THREAD

**Issue by kemp-zz** [ophub/amlogic-s9xxx-openwrt#608]
**Device Information | 设备信息**
 - SOC: [e.g. rockchip]
 - Model [smart am40]

**OpenWrt Version | 系统版本**
 - Kernel Version: [e.g. 5.15.100]
 - Release: [ official/lede/immortalwrt]

**Describe the bug | 问题描述**
All issues will only remain open for one week to prioritize resolving them.
勾选Auto use the latest kernel  能正常生成固件 但都会自动生成6.1内核 的 没有5.1内核 的。
不勾选Auto use the latest kernel  就会出现 
https://github.com/ophub/kernel/releases/download/kernel_stable/5.15.y.tar.gz ]
curl: (22) The requested URL returned error: 404

**Comment by ophub** [comment]
rockchip系列只能使用6.1.y和6.6.y的内核，不能使用主线（stable）5.x.y
rk35xx/rk3588可以使用5.10.1y（非主线）
