### ISSUE TITLE
I found 8189fs 5.9

### ISSUE THREAD

**Issue by Kry9toN** [ophub/amlogic-s9xxx-openwrt#61]
I have module 8189fs for kernel 5.9
But i have problem
![PXL_20210423_013827](https://user-images.githubusercontent.com/44697929/115768713-e082e100-a3d4-11eb-9768-201bd265f630.jpg)

I dont have idea to fix, but i think u can give me kernel 5.9.0 or u can change localversion kernel

**Comment by ophub** [comment]
8189fs for kernel 5.9 give me.
I have the kernel of `5.9.1`, I will merge it into this driver for you, please try whether it can be used normally in openwrt.

**Comment by Kry9toN** [comment]
I will test it with pleasure

8189fs.ko
https://sourceforge.net/projects/krypton-project/files/OpenWrt/8189fs.ko

**Comment by ophub** [comment]
I put the driver you shared into the modules-5.9.1-flippy-47+.tar.gz file, you can compile and try to see if it can drive successfully.

https://github.com/ophub/amlogic-s9xxx-openwrt/tree/main/amlogic-s9xxx/amlogic-kernel/kernel/5.9.1

**Comment by Kry9toN** [comment]
I oke i try it now

**Comment by Kry9toN** [comment]
> I put the driver you shared into the modules-5.9.1-flippy-47+.tar.gz file, you can compile and try to see if it can drive successfully.
> 
> https://github.com/ophub/amlogic-s9xxx-openwrt/tree/main/amlogic-s9xxx/amlogic-kernel/kernel/5.9.1

![PXL_20210423_133252](https://user-images.githubusercontent.com/44697929/115828910-8156b800-a438-11eb-9e83-477c28f0cca8.jpg)

Same, maybe module must be compile on same kernel

**Comment by ophub** [comment]
sad.

**Comment by Kry9toN** [comment]
> sad.

Maybe u can show me where you source kernel to build?

**Comment by ophub** [comment]
I haven’t found this driver in the openwrt official network driver. It seems that I have to wait.

**Comment by Kry9toN** [comment]
> I haven’t found this driver in the openwrt official network driver. It seems that I have to wait.

I found this module driver in khadas

https://github.com/khadas/android_hardware_wifi_realtek_drivers_8189ftv

**Comment by ophub** [comment]
http://www.kernel.org/pub/linux/kernel/

**Comment by ophub** [comment]
When compiling the kernel, select the network card driver and compile it in, which is the most appropriate.

**Comment by Kry9toN** [comment]
> http://www.kernel.org/pub/linux/kernel/

Hmm where is makefile?

**Comment by Kry9toN** [comment]
> https://www.google.com/search?q=linux+kernel+compilation
> 
> https://www.cyberciti.biz/tips/compiling-linux-kernel-26.html
> 
> https://www.linux.com/topic/desktop/how-compile-linux-kernel-0/

https://web.facebook.com/notes/dd-wrt-open-wrt-indonesia-open-source/list-download-firmware-openwrt-untuk-stb/471673447483739/

maybe you can extract this kernel for me, i try it not work on you script

**Comment by ophub** [comment]
Which version of this URL do you want?

**Comment by Kry9toN** [comment]
> Which version of this URL do you want?

on the link there is a list of openwrt whose wifi is working well

**Comment by ophub** [comment]
Have you tried it? Which one of these can drive this network card? Connect this firmware to me, I will extract it into the kernel for you

**Comment by ophub** [comment]
3.14  and 5.8.18 ?
Downloading, I'll send it to you later.

**Comment by Kry9toN** [comment]
> 3.14 and 5.8.18 ?
> Downloading, I'll send it to you later.

Yes, oke thanks you, i will waiting 👍

**Comment by Kry9toN** [comment]
> Have you tried it? Which one of these can drive this network card? Connect this firmware to me, I will extract it into the kernel for you

On the list everything went well with the wifi driver

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-openwrt/tree/main/amlogic-s9xxx/amlogic-kernel/kernel/5.8.18

You try this, the other 3.14 file cannot be mounted and cannot be used.

**Comment by Kry9toN** [comment]
> https://github.com/ophub/amlogic-s9xxx-openwrt/tree/main/amlogic-s9xxx/amlogic-kernel/kernel/5.8.18
> 
> You try this, the other 3.14 file cannot be mounted and cannot be used.

Oke thanks i hope that work

**Comment by Kry9toN** [comment]
> https://github.com/ophub/amlogic-s9xxx-openwrt/tree/main/amlogic-s9xxx/amlogic-kernel/kernel/5.8.18
> 
> You try this, the other 3.14 file cannot be mounted and cannot be used.

Sad, not booted

**Comment by ophub** [comment]
Sad, keep working hard

**Comment by Kry9toN** [comment]
> Sad, keep working hard

Oke, thanks for help me
