### ISSUE TITLE
安装软件提示内核版本不匹配

### ISSUE THREAD

**Issue by RuthIPTV** [ophub/amlogic-s9xxx-openwrt#618]
**Device Information | 设备信息**
 - SOC: [amlogic_s905l3a]
 - Model [M401A]

**OpenWrt Version | 系统版本**
 - Kernel Version: [Linux ImmortalWrt 6.6.40-ophub #1 SMP Mon Jul 15 20:54:07 EDT 2024 aarch64 GNU/Linux]
 - Release: [immortalwrt]

**Describe the bug | 问题描述**
安装软件都会有这么一行报错
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 6.6.39~4ad8919e6cb358ce9faee3c576171c3d-r1) for kmod-inet-diag
 * 但是我的内核版本已经是6.6.40了，为什么还会有6.6.39的报错?

Please provide a detailed description of the issue and, if necessary, attach a screenshot.

**Comment by ophub** [comment]
自己编辑添加需要的
