### ISSUE TITLE
cant install kmod packets

### ISSUE THREAD

**Issue by PriFak** [ophub/amlogic-s9xxx-openwrt#619]
hello
i noticed that i cant install any kmod packets because the kernel version is incompatible. but it is no linux kernel version, but "kernel" packet version inside openwrt. 
so can you compile alongside with snapshot version a stable openwrt version (like 23.05.01) where this problem will be eliminated or compile the openwrt snapsot version that is compatible with the version of kernel modules (kmod)

thank you

**Comment by ophub** [comment]
Fork the repository, add the required software packages, and build a custom firmware. There is no image repository support for installing later.
