### ISSUE TITLE
boot分区没有被正常挂载

### ISSUE THREAD

**Issue by jsdfhasuh** [ophub/amlogic-s9xxx-openwrt#622]
**Device Information | 设备信息**
 - SOC: AM6B-plus
 - Model [e.g. HK1]

**OpenWrt Version | 系统版本**
 - Kernel Version: 5.15.100]
 - Release: official

**Describe the bug | 问题描述**
启动之后发现boot分区没有被正常挂载

![image](https://github.com/user-attachments/assets/ff42648b-71d9-4651-ad3a-0246dd193d64)

**Comment by jsdfhasuh** [comment]
[test.txt](https://github.com/user-attachments/files/16648128/test.txt)
openwrt official 编译选项

**Comment by ophub** [comment]
![IMG_0762](https://github.com/user-attachments/assets/03c5f434-b726-4b3a-8315-0ddcf15c001c)

![IMG_0763](https://github.com/user-attachments/assets/040fc424-0bb6-478c-b12a-85354ee10ae6)

![IMG_0764](https://github.com/user-attachments/assets/944078d0-0f30-46d1-8ed4-cca64dcf38f7)

**Comment by ophub** [comment]
![IMG_0762](https://github.com/user-attachments/assets/03c5f434-b726-4b3a-8315-0ddcf15c001c)


![IMG_0764](https://github.com/user-attachments/assets/944078d0-0f30-46d1-8ed4-cca64dcf38f7)

**Comment by jsdfhasuh** [comment]
[Uploading blkid.log…]()

**Comment by jsdfhasuh** [comment]
[blkid.log](https://github.com/user-attachments/files/16648803/blkid.log)

**Comment by jsdfhasuh** [comment]
[dmesg.log](https://github.com/user-attachments/files/16648813/dmesg.log)

**Comment by jsdfhasuh** [comment]
我镜像里面没有lsblk，我现在改一下

**Comment by jsdfhasuh** [comment]
改了也没用，好像是mount 不支持label属性
mount: mounting LABEL="BOOT" on /boot failed: No such file or directory
