### ISSUE TITLE
无法从U盘启动

### ISSUE THREAD

**Issue by taotaoyouyou** [ophub/amlogic-s9xxx-openwrt#625]
**设备信息**
 - SOC: S905D
 - Model Phicomm-N1

**系统版本**
 - Kernel Version: 6.1.106
 - Release: official

**问题描述**
EMMC中的系统是[openwrt_official_amlogic_s905d_k6.1.106_2024.08.23]，U盘制作的系统是[istoreos-22.03.6-2024043010-phicomm_n1]，尝试多次均无法从U盘启动，但是如果U盘中的系统是openwrt_official/immortalwrt_amlogic_s905d_xxxx(同是ophub编译的其他系统）就可以从U盘启动。

**尝试的办法**
1. 尝试另一个USB口-失败
2. 尝试更换U盘—失败
3. 尝试更换其他大神编译的镜像-失败
4. 尝试更换USB刻录软件—失败
5. 在作者armbian的仓库里看到一个已经关闭的问题[#565](https://github.com/ophub/amlogic-s9xxx-armbian/issues/565)，尝试修改/boot/boot.cmd,添加usb start ***字段—失败。
6. 网上也找到一些N1无法从U盘启动的案例（包括作者的），都是建议用双公头USB刷bootloader，果断下单了双公头（ 写这个issue的时仍未到货）

**成功的办法**
从上面第五个办法得出灵感，此问题应该是作者/boot分区文件导致不兼容其他系统，导致无法启动U盘的里系统，那将U盘boot分区的文件替换emmc中boot文件，原理上应该能启动，但是尝试搜索没找到成功的案例（可能是我没找仔细），具体操作：
1.启动emmc中的系统，ssh连接
2.  cd /boot
     rm -rf *  (删除emmc中boot分区中的所有文件）
3. cp /mnt/sda1/*    /boot   (将U盘boot分区中的所有文件拷贝到emmc的boot分区中，我的U盘boot分区挂载的是sda1）
4. ls /boot （查看是否复制成功）
5. 断电 1 2 3  插电  开机
6. 进入istoreos（U盘系统）

**总结**
问题应该出在作者的boot分区文件，之前有个帖子讨论boot的mainline 和 overload （没看懂），觉得应该是这个原因引起的。

**Comment by ophub** [comment]
istoreos的N1你直接使用即可，先把N1用救砖法刷回原来的安卓系统，再安装你的istoreos。
不用改boot，这2个系统的差异不只是boot，你用他的即可。
