### ISSUE TITLE
请问如何得到内核的boot压缩包的，通过linux内核可以得到吗

### ISSUE THREAD

**Issue by jsdfhasuh** [ophub/amlogic-s9xxx-openwrt#632]

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/compile-kernel

使用内核源码编译的

**Comment by jsdfhasuh** [comment]
你好，我看了你写的recomplie，发现boot和header都是直接从armbian里面获取到的，为什么不从内核里面拿呢

**Comment by ophub** [comment]
你再仔细看看。armbian只是编译环境，用的是源码。几个文件有些在x86里就可以交叉编译成，header和boot要到armbian里编。

**Comment by jsdfhasuh** [comment]
> 你再仔细看看。armbian只是编译环境，用的是源码。几个文件有些在x86里就可以交叉编译成，header和boot要到armbian里编。
> 
> 节目分上下场，上半场在x86，下半场在armbian。从x86转场时把上半场的源码也带入了armbian。
header 可以直接用linux源码安装header_install吗，为什么boot不能在x86上面生成，是因为什么原因呢

**Comment by ophub** [comment]
不能装，不能生，不同arch
