### ISSUE TITLE
请问一下u盘引导的时候是可以正常进入的，写入emmc后不开机

### ISSUE THREAD

**Issue by meetclover** [ophub/amlogic-s9xxx-openwrt#634]
设备: 魔百盒M401A（江苏版）s905l3a
我分别尝试了以下几个版本只要写入emmc后都会开不了机，请问一下开发者我该如何解决
![image](https://github.com/user-attachments/assets/939e53b2-d887-4cf6-b2f1-722f966a8fc8)

**Comment by ophub** [comment]
你从首页设备列表点这个进去看使用方法

**Comment by meetclover** [comment]
> 你从首页设备列表点这个进去看使用方法，可以试一下添加u-boot使用：`armbian-install -m yes`

我现在尝试安装的是openwrt

**Comment by meetclover** [comment]
> 你从首页设备列表点这个进去看使用方法，可以试一下添加u-boot使用：`armbian-install -m yes`

我现在尝试安装的是openwrt，下面是安装操作日志希望能帮到您
[log.txt](https://github.com/user-attachments/files/17082533/log.txt)

**Comment by ophub** [comment]
晶晨宝盒里选择使用主线bootloader

**Comment by meetclover** [comment]
![image](https://github.com/user-attachments/assets/d3ef7251-8133-482c-beb7-7688849a49c6)
感谢大佬指正，我记得原来没有这个选项的，踩坑了希望能帮到后来者
