### ISSUE TITLE
Custom kernel not working

### ISSUE THREAD

**Issue by Manssizz** [ophub/amlogic-s9xxx-openwrt#648]
**Device Information | 设备信息**
 - SOC: All
 - Model All

**OpenWrt Version | 系统版本**
 - Kernel Version: 5.15.y 6.1.y 6.6y
 - Release: All

**Describe the bug | 问题描述**
I have custom kernel with low latency tags in my [kernel repo](https://github.com/Manssizz/ophub-kernel). Compiled work but still used stable kernel. How to use custom kernel?
- i've try change some value in `remake` script (attachment)
- I was add my own kernel repo and kernel usage value (attachment)

Please provide a detailed description of the issue and, if necessary, attach a screenshot.
![image](https://github.com/user-attachments/assets/ee163983-6941-4628-9390-43eeebcbca59)
![image](https://github.com/user-attachments/assets/e51d27c4-54d3-4f4f-88e4-b97d6dc06e9d)

**Comment by ophub** [comment]
Tags use name:
kernel_stable
kernel_beta
kernel_dev

**Comment by Manssizz** [comment]
so... only support 3 tags (stable, beta,dev)?

**Comment by Manssizz** [comment]
ok. thanks. closed
