### ISSUE TITLE
请教大佬，编译前，在哪个地方可以修改固件每个分区的大小

### ISSUE THREAD

**Issue by sztuxp** [ophub/amlogic-s9xxx-openwrt#655]
请教大佬，编译前，在哪个地方可以修改每个分区的大小，现在是分给docker使用的分区有点小，其他又没有使用？谢谢！

**Comment by ophub** [comment]
amlogic的分区不可以自定义，写入不安全的区域就砖了，现在的分区大小都经过了严格计算。docker放/mnt/mmcblk2p4

**Comment by sztuxp** [comment]
S905D 挂载在 /dev/mmcblk2p2
<html>
<body>

/dev/mmcblk2p2 | /mnt/sda4/docker | 555.17 MiB / 960.00 MiB | 32.36% (310.64 MiB)
-- | -- | -- | --



</body>
</html>

**Comment by ophub** [comment]
改保存路径

**Comment by sztuxp** [comment]
> 改保存路径
请教如何改？
我现在找到一个土办法，现在盒子刷一个其他版本固件（F大的），再用U盘上的immotalwrt安装就正常了

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-openwrt/blob/main/documents/README.cn.md

看10.5
