### ISSUE TITLE
Error on pip module

### ISSUE THREAD

**Issue by latiefkhan** [ophub/amlogic-s9xxx-openwrt#7]
when i installing ssh connection client using module pip. it always getting error,
![Screenshot_27](https://user-images.githubusercontent.com/76825535/103989651-9a599700-51c2-11eb-956c-5d0cac611615.png)

**Comment by ophub** [comment]
Installation example:

opkg update                       #Update list ofavailable packages  
opkg list | grep pip              #Find the software name that contains pip
opkg install python3-pip    #Install  python3-pip

###########

Common commands for opkg:

opkg  update                               #Update list ofavailable packages  
opkg  upgrade  <pkgs>              #Upgrade packages  
opkg  install <pkgs>.                  #Install package(s)  
opkg  configure <pkgs>             #Configure unpacked package(s)  
opkg  remove <pkgs|regexp>    #Remove package(s)
opkg  list                                      #List availablepackages  
opkg  list-installed                      #List installed packages  
opkg  list-upgradable                 #List installed and upgradable packages
opkg  list | grep <pkgs>              #Find similar software names
