### ISSUE TITLE
分辨率支持问题

### ISSUE THREAD

**Issue by GongKuiJun** [ophub/amlogic-s9xxx-openwrt#70]
你好 
我希望能更加插入的输出设备适应分辨率，比如我接一个1280*800的显示器，输出分辨率自动为1280*800  而不是通过mesondisplay.cfg 设置固定分辨率

**Comment by ophub** [comment]
Hello, we are using OpenWrt firmware, and you are asking about the configuration of Android firmware. Your suggestions need to go to amlogic's official feedback.
