### ISSUE TITLE
检测硬盘大小的代码出错了，是系统少安装了什么软件吗？

### ISSUE THREAD

**Issue by vpei** [ophub/amlogic-s9xxx-openwrt#72]
(1.1) Start packaging OpenWrt [ s905d - 5.4.123 ]. ./make:行642: [[: 3.2：语法错误: 无效的算术运算符 (错误符号是 ".2")
Remaining space is 3.2G.

检测硬盘大小的代码出错了，是系统少安装了什么软件吗？

**Comment by ophub** [comment]
Remaining space is 3.2G.
Insufficient space to compile, 3G is only suitable for compiling one firmware.

**Comment by ophub** [comment]
Line 642 is modified to: `exit 0`

**Comment by ophub** [comment]
Modify line 642 to: break 2
