### ISSUE TITLE
luci app bypass combination ssr+ with passwall

### ISSUE THREAD

**Issue by ramasedang** [ophub/amlogic-s9xxx-openwrt#77]
can u add luci-app-bypass ? https://github.com/garypang13/luci-app-bypass

**Comment by ophub** [comment]
1. in diy-part2.sh add:
svn co https://github.com/garypang13/luci-app-bypass.git package/luci-app-bypass

2. in .config add
CONFIG_PACKAGE_luci-app-bypass=y

This will compile the plug-in.
