### ISSUE TITLE
2/16 version

### ISSUE THREAD

**Issue by aska-lz** [ophub/amlogic-s9xxx-openwrt#78]
hi develover, kernel 5.12.10 booting normaly in x96max+ ver.4/32 . 
but can't booting on x96max+ ver.2/16 . 
please fix it.
thank you 🙏

**Comment by ophub** [comment]
Hello, 2G version and 4G version are two different firmwares, 2G needs to use s905x2 firmware.

E.g: openwrt_s905x2_v5.12.10_2021.06.13.0352.img.gz

**Comment by aska-lz** [comment]
> Hello, 2G version and 4G version are two different firmwares, 2G needs to use `s905x2` firmware.
> 
> E.g: `openwrt_s905x2_v5.12.10_2021.06.13.0352.img.gz`
> 
> Use the openwrt-install command to install option `10. X96-Max-2G -------------- [ S905x2 / CPU: 1944Mtz / NETWORK: 100M ]`
> 
> Use the luci-app-amlogic install option:
> 
> ![Snip20210613_2](https://user-images.githubusercontent.com/68696949/121804132-79b4d200-cc77-11eb-8a05-3be69ca46c90.png)

oh, i think same come with s905x3 , thank you for your reply. i will try with  s905x2
