### ISSUE TITLE
Wetek Hub

### ISSUE THREAD

**Issue by muetzekoeln** [ophub/amlogic-s9xxx-openwrt#80]
Could you please also support (legacy device) WETEK Hub?

**Comment by ophub** [comment]
Support Amlogic S9xxx STB are S905x3, S905x2, S922x, S905x, S905d, s912.
What model is `WETEK Hub`?

**Comment by muetzekoeln** [comment]
Thanks. I tried it. Copied image to micro-SD, copied dtb file and changed uEnv.txt.
But WETEK Hub did not even try to start from micro-SD. It instantly boots from NAND.
There seems to be something very basic missing or wrong.
