### ISSUE TITLE
Crash/not booting to B860H

### ISSUE THREAD

**Issue by farhanfajrin** [ophub/amlogic-s9xxx-openwrt#81]
heello im error for stb B860 v1, i not acces to 192.168.1.1 and notif not reached why?

but if I use this firmware I can access..  https://www.youtube.com/watch?v=ZxXYuwkC2WM

**Comment by ophub** [comment]
B860H can use s905x firmware, you download the corresponding firmware to test, such as:

[openwrt_s905x_v5.4.127_2021.06.------.img.gz](https://github.com/ophub/amlogic-s9xxx-openwrt/releases)

[openwrt_s905x_v5.12.12_2021.06.------.img.gz](https://github.com/ophub/amlogic-s9xxx-openwrt/releases)
