### ISSUE TITLE
您好，您的配置文件或许有问题

### ISSUE THREAD

**Issue by 281677160** [ophub/amlogic-s9xxx-openwrt#82]
用你的.config配置文件编译固件，下载DL的时候会显示一个错误，不过可以编译成功
我发现是这个带来的错误：CONFIG_TARGET_ROOTFS_PARTSIZE=1024
bash: *1024*1024: syntax error: operand expected (error token is "*1024*1024")

![QQ截图20210620225315](https://user-images.githubusercontent.com/66651997/122678706-7e9af800-d21a-11eb-9281-1677fc62430d.png)

**Comment by ophub** [comment]
https://forum.openwrt.org/t/how-to-set-root-filesystem-partition-size-on-x86-imabebuilder/4765/2



This is to set the firmware size, which is mainly set when the X86 image file is compiled. Can be commented out.

The size of the firmware will be allocated again during `packaging` and `install`, and it can be cancelled here.

Thanks for the feedback.
