### ISSUE TITLE
ASK [Restore Android OS from OpenWrt EMMC]

### ISSUE THREAD

**Issue by radityabh** [ophub/amlogic-s9xxx-openwrt#86]
How to return Openwrt emmc to Android Os again? my device x96max+. 
Thank you

**Comment by ophub** [comment]
Use USB_Burning_Tool to flash Android system online. 

Or use armbian, boot from usb hard disk, ddbr restore Android system.

**Comment by radityabh** [comment]
> Use USB_Burning_Tool to flash Android system online.
> 
> Or use armbian, boot from usb hard disk, ddbr restore Android system.
> 
> Same as the method of restoring the system:
> 
> https://github.com/ophub/amlogic-s9xxx-openwrt/tree/main/router-config#108-how-to-recover-if-the-install-fails-and-cannot-be-started

Ok thanks
