### ISSUE TITLE
Can't boot B860H (s905x)

### ISSUE THREAD

**Issue by aarzaary** [ophub/amlogic-s9xxx-openwrt#89]
why B860H can't boot with kernel 5.10+
if using 5.4.xxx it's boot normal

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-openwrt/blob/e8fff0b1a79a5b53e821a3599618c539f7c9da92/make#L185

change into:

```
FDTFILE="meson-gxl-s905x-p201.dtb"
UBOOT_OVERLOAD="u-boot-p201.bin"

```
You try whether p201 can start.

**Comment by ophub** [comment]
If the kernel above 5.10 has mainline U-BOOT, it is the best solution. At present, there is only 5.4 available.
