### ISSUE TITLE
Fix theme argon

### ISSUE THREAD

**Issue by kbuku35** [ophub/amlogic-s9xxx-openwrt#90]
can the argon theme look better, such as:
https://github.com/jerrykuku/luci-theme-argon/releases/tag/v1.7.2
thank you

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-openwrt/blob/main/router-config/README.md#example-2-replace-the-existing-software-package

You can replace your favorite skins after fork.
