### ISSUE TITLE
大佬，gt king pro卡starting kenel，无法完成启动。

### ISSUE THREAD

**Issue by y9858** [ophub/amlogic-s9xxx-openwrt#91]
![IMG_20210628_210333_612__01](https://user-images.githubusercontent.com/53130835/123657473-66068f80-d863-11eb-94df-9313a459aafd.jpg)
5.12kernel的固件，用U盘启动的。看提示bootfromsd无定义，是一定要用sd卡吗？

**Comment by ophub** [comment]
- Select the firmware of s9222: https://github.com/ophub/amlogic-s9xxx-openwrt/releases/download/openwrt_s9xxx_lede_2021.06.29.0515/openwrt_s922x_k5.12.13_2021.06.29.0510.img.gz
- Try another usb.
- Use [Rufus](https://rufus.ie) to write image files to usb
