### ISSUE TITLE
章鱼星球网页网速测速不能满速

### ISSUE THREAD

**Issue by yu13740000** [ophub/amlogic-s9xxx-openwrt#92]
大佬，章鱼星球网页测速跑不满，同一个节点，你的固件300兆，f大的315兆，也不能满速，网页不关闭继续换维加云测速340兆，我是300兆的宽带。

**Comment by ophub** [comment]
With 300MB broadband, isn’t it full speed to run 300?

My default is `ondemand` mode, you can change to `schedutil` mode in CPU adjustment.( Services > CPU Freq )
- CPU Scaling Governor: schedutil
- Min Idle CPU Freq: 100000
- Max Turbo Boost CPU Freq: 1512000
- CPU Switching Threshold: 50
- CPU Switching Sampling rate: 10
