### ISSUE TITLE
Openwrt Official

### ISSUE THREAD

**Issue by r3yr3** [ophub/amlogic-s9xxx-openwrt#94]
Why you stop build openwrt official?

**Comment by ophub** [comment]
coolsnowwolf/lede was upgraded to 21.02 a week ago, and it is now the same as the official branch. The software package of lede is more abundant, and the speed of BUG repair is faster, so use this.

**Comment by r3yr3** [comment]
> coolsnowwolf/lede was upgraded to 21.02 a week ago, and it is now the same as the official branch. The software package of lede is more abundant, and the speed of BUG repair is faster, so use this.

Thanks for answer,...
