### ISSUE TITLE
badvpn-tun2socks

### ISSUE THREAD

**Issue by lynxnexy** [ophub/amlogic-s9xxx-openwrt#95]
please add package "badvpn-tun2socks" to system firmware

**Comment by codesnas** [comment]
Hello, I did not find the package you mentioned. What is his full name.

**Comment by ophub** [comment]
Hello, I did not find the package you mentioned. What is his full name.

**Comment by kbuku35** [comment]
maybe this means :
https://github.com/zhfish/tun2socks-Openwrt

**Comment by ophub** [comment]
https://github.com/zhfish/tun2socks-Openwrt/blob/master/badvpn/Makefile
```
PKG_NAME:=badvpn
PKG_VERSION:=1.999.117rc2
PKG_RELEASE:=1

PKG_SOURCE:=$(PKG_NAME)-$(PKG_VERSION).tar.bz2
PKG_SOURCE_URL:=http://badvpn.googlecode.com/files/
```

The author hasn't updated it for 8 years. This file can no longer be downloaded. Give up, face the future, spring blossoms.

**Comment by lynxnexy** [comment]
this is https://code.google.com/archive/p/badvpn/wikis/tun2socks.wiki

i need this package for ssh tunneling ==> dynamic socks5 ==> tun interface

**Comment by ophub** [comment]
His file can no longer be downloaded, so give up.

**Comment by helmiau** [comment]
> Find another plan.

how about this repo?
https://github.com/friyadhibiermann/openwrt_badvpn-tun2socks
