### ISSUE TITLE
Add interface on system fw

### ISSUE THREAD

**Issue by riyuejz** [ophub/amlogic-s9xxx-openwrt#96]
can you help add the hilink modem interface to the system firmware

> Interface setup details

Name `hilink`
Protocol `dhcp client`
Physical `eth1`
Firewall `wan`

**Comment by ophub** [comment]
On your device: `Network` > `Interface`, after the configuration is completed, you can get your dedicated `network` file. The path is in `/etc/config/network` of the `openwrt` system.

`Fork` the repo, copy this file to the `/amlogic-s9xxx/common-files/files/etc/config/network` path in the repo. In this way, your packaged `openwrt` firmware is already set.

**Comment by riyuejz** [comment]
For example, if I put a file in `/usr/bin/mybinnary` will the file automatically give permission to 755?

**Comment by ophub** [comment]
There are two ways to authorize. The first method is to locally `chmod +x usr/bin/mybinnary` and then `git push` to github. Another method is to add permissions when packaging, such as adding `chmod +x usr/bin/mybinnary` in `make`

**Comment by riyuejz** [comment]
ok i will try it .. thanks and good morning 😄
