### ISSUE TITLE
能否支持A311D？

### ISSUE THREAD

**Issue by yangquan3** [ophub/amlogic-s9xxx-openwrt#99]

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-openwrt/blob/main/amlogic-s9xxx/amlogic-dtb/meson-g12b-a311d-khadas-vim3.dtb

`/boot/uEnv.txt` 
FDT changed to the file name of `meson-g12b-a311d-khadas-vim3.dtb`.

Open the A311D-Box in ADB and start the USB flash drive:

adb connect device_ip_address
adb shell reboot update

Test whether you can start the openwrt system in the U disk.

**Comment by darkliang** [comment]
> https://github.com/ophub/amlogic-s9xxx-openwrt/blob/main/amlogic-s9xxx/amlogic-dtb/meson-g12b-a311d-khadas-vim3.dtb
> 
> `/boot/uEnv.txt` FDT changed to the file name of `meson-g12b-a311d-khadas-vim3.dtb`.
> 
> Open the A311D-Box in ADB and start the USB flash drive:
> 
> ```
> adb connect device_ip_address
> adb shell reboot update
> ```
> 
> Test whether you can start the openwrt system in the U disk.

Hi, I have a A311D box (Khadas vim3) also. I used the S922X image and replaced the FDT to `meson-g12b-a311d-khadas-vim3.dtb`, it works. But it doesn't support the wireless drivers, and it can't turn on the fan. So how can I build a custom-made image for it?

**Comment by ophub** [comment]
https://github.com/armbian/build/blob/master/config/boards/khadas-vim3.conf

I saw this box in the official support list of armbian. The official default compilation should be able to support it, right?
The boxes in my repository are devices that are not officially supported by default, and we tweaked a little bit to try and make armbian work on these boxes.

**Comment by darkliang** [comment]
I'm sorry being new to this, I'm not sure what Armbian support has to do with OpenWRT.

**Comment by ophub** [comment]
You can think of it as the same. Two different systems, but a twin brother's system for the box

**Comment by Ravjhay** [comment]
how to hack scatter game
